### ISSUE TITLE
Would you consider using warnings instead of errors for deprecated usages?

### ISSUE THREAD

**Issue by chrishulbert** [ReactiveCocoa/ReactiveSwift#10]
Hi,
Currently working on a swift 3 migration - when you go to version 1 of RAC5, would you please consider using warnings instead of compile-time errors for deprecated usage such as startWithNext ?
At least until, say, version 5.1 ?
It would make the migration of large codebases to swift 3 much easier.
Thanks a lot.

**Comment by andersio** [comment]
We have staged it in 4.2.x if you are talking about `startWithNext` for producers with non-`NoError` error types. It is a bug and I don't see the strong rationale to drag it longer.

**Comment by mdiep** [comment]
Does Swift have a way to make the deprecations warnings instead of errors?

Also, FWIW, there's probably more churn to come. You're welcome to use the Swift 3 version now, but there will likely be more breaking changes.

**Comment by andersio** [comment]
Just mark it as deprecated instead of unavailable. The compiler will issue a warning instead in this case.

**Comment by mdiep** [comment]
If we do that, then we need to keep those around until 6.0. (Removing the deprecations or making them unavailable would be a breaking change.)

That's my only hesitation.

**Comment by chrishulbert** [comment]
I'd be happy if they went back to being errors on version 5.1 - just that migrating a codebase from swift 2 to 3 is a nightmare, and updating all my 'startWithNext' is just making it that much harder. Up to you guys, i'm sure you've got your reasons. Thanks for the great project.

**Comment by mdiep** [comment]
> I'd be happy if they went back to being errors on version 5.1

Unfortunately, that breaks semantic versioning. If another project says it's compatible with 5.0, it could still use those operators, even though they create warnings. That project would then break if we moved them to errors in 5.1.
