### ISSUE TITLE
Error in switching event

### ISSUE THREAD

**Issue by EvilNOP** [ReactiveCocoa/ReactiveSwift#100]
```swift
searchResults.observe { event in
    switch event {
    case let .value(results):
        print("Search results: \(results)")

    case let .error(error):
        print("Search error: \(error)")

    case .completed, .interrupted:
        break
    }
}
```

Notice the case let .error have been change to case let .failed, please update the README.md.

**Comment by andersio** [comment]
Fixed in https://github.com/ReactiveCocoa/ReactiveSwift/commit/b3361c2bdad52c6f9488de5879cde5a0545e4bd6. Thank you for catching it.

😸
