### ISSUE TITLE
Checking out ReactiveSwift takes longer than expected

### ISSUE THREAD

**Issue by AndrewSB** [ReactiveCocoa/ReactiveSwift#102]
I'm dependent on `ReactiveSwift` through [`Moya`](GitHub.com/Moya/Moya), and I've noticed that `carthage update`s hang on `Checking out ReactiveSwift` for much longer than expected (1 minute+), it seems as if it's doing something with `git-remote-https`? Maybe checking out submodules or something?

I wanted to bring this to the maintainer's attention at the very least, and I was wondering if the checkout process for `ReactiveSwift` could be optimized for the next release?

Thanks!

**Comment by mdiep** [comment]
There isn't really anything to be done. It takes the time it takes. This larger does have a larger than average history, which might account for a slow initial clone.

**Comment by AndrewSB** [comment]
It would make sense if the initial clone was slow, but why would that make the `checkout` so long as well?
I feel as if it has to be doing something more than just a `git checkout`, since the repo has already been fetched through `carthage`.
RxSwift, for example, which has about 1/4 the commits this repo does takes about 2 seconds to process it's `checkout` on my machine.

**Comment by mdiep** [comment]
You're welcome to investigate! If there's something that can be done, I'd definitely be in favor of doing it.

**Comment by AndrewSB** [comment]
I'll give it a look @mdiep, I'll let you know if I find something!
