### ISSUE TITLE
Odd behaviour on `on`

### ISSUE THREAD

**Issue by gkaimakas** [ReactiveCocoa/ReactiveSwift#115]
I have the following snippet of code:

````Swift
	SignalProducer<Int, NSError>(value: 15)
			.on(starting: {
				print("starting")
			})
			.on(started: {
				print("started")
			})
			.on(value: { _ in
				print("value")
			})
			.on(failed: { _ in
				print("failed")
			})
			.on(completed: {
				print("completed")
			})
			.start()
````

That prints the following results on the console

````
starting
value
completed
started
````

Shouldn't the output be 
````
starting
started
value
completed
````

instead?

The same thing happens when the `producer` fails.

**Comment by mdiep** [comment]
This is because of how `SignalProducer.init(value:)` works. It sends the value _immediately_.

It goes something like this.

1. Call `starting`
2. Call `SignalProducer` to start
    1. `init(value:)` sends a value (`value`) and then completes (`completed`)
3. Call `started`

**Comment by gkaimakas** [comment]
@mdiep This is quite confusing. I have observed the same behaviour on `MutableProperty`

**Comment by andersio** [comment]
`started` is invoked after the starting side effect is done. So you would exhibit the same behaviour in any producer that sends events synchronously in the start hamdler.

**Comment by mdiep** [comment]
I think it'd be more surprising for `started` to not always fire.

**Comment by gkaimakas** [comment]
Shouldn't `started` fire after `starting`?

**Comment by andersio** [comment]
No.

> `started` is invoked after the starting side effect is done.

Look at the signature of `SignalProducer.init(_:)`. It accepts a `startHandler` that is passed an observer. This means events can be sent as part of the starting side effect, and `started` indicates the side effect is completed, following these events.

**Comment by mdiep** [comment]
Maybe this will help you make sense of it: the signal completed before it finished starting.
