### ISSUE TITLE
Un-genericize ScopedDisposable

### ISSUE THREAD

**Issue by robertjpayne** [ReactiveCocoa/ReactiveSwift#127]
I'm migrating a project from RAC to ReactiveSwift and one of the changes that boggles me a bit is why ScopedDisposable was turned into a generic, I'm just wondering the real world use case where anyone actually needs to explicitly ensure a ScopedDisposable only contains a disposable of X type?

My use case is maybe the outlier but I use ScopeDisposable to make for easy interrupts:

```
var requestDisposable: ScopedDisposable? = nil
...
func run() {
   self.requestDisposable = producer.start()
}
```

It's frustrating to have to now double wrap these `ScopedDisposable(AnyDisposable(producer.start()))` to get the same effect and I'm just struggling to see the use case where anyone is going to grab the `innerDisposable` and care what type it is?

**Comment by robertjpayne** [comment]
Ah I see the extension and constraint for `ScopedDisposable<AnyDisposable>()`

**Comment by ikesyo** [comment]
FYI the rationale behind the change: https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2750
