### ISSUE TITLE
CocoaPods Support?

### ISSUE THREAD

**Issue by ashfurrow** [ReactiveCocoa/ReactiveSwift#13]
Good morning! Lovely library, I see that ReactiveCocoa's new Swift 3 work depends on this project, neat. Would you consider adding CocoaPods support to ReactiveSwift? I would be happy to send a pull request, but wanted to check first. Thanks!

**Comment by sharplet** [comment]
I think adding CocoaPods support makes a lot of sense, especially given the discussion on https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3000.

**Comment by ashfurrow** [comment]
Wonderful, expect something later today.
