### ISSUE TITLE
(SWIFT_VERSION) to Swift 3

### ISSUE THREAD

**Issue by bharath555vasu** [ReactiveCocoa/ReactiveSwift#132]
“Use Legacy Swift Language Version” **(SWIFT_VERSION)** is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

After converting to **Swift 3 Build Failed** and additional **58 errors** are coming see below image.
![screen shot 2016-11-29 at 9 53 43 am](https://cloud.githubusercontent.com/assets/21052573/20696623/1f7d0096-b61a-11e6-8c97-137abbe5260a.png)

 Also mention is there any thing to import after pod install to use this library.

**Comment by andersio** [comment]
As we do not have a stable release yet, you would need to refer to the Swift 3 version by tag.
https://github.com/ReactiveCocoa/ReactiveSwift#cocoapods

Note that ReactiveCocoa hasn't been updated for ReactiveSwift 1.0.0-alpha.4 yet. So if you want to use ReactiveCocoa too, do not include 1.0.0-alpha.4 in your Podfile.
