### ISSUE TITLE
Deadlock in binding to a MutableProperty

### ISSUE THREAD

**Issue by sharplet** [ReactiveCocoa/ReactiveSwift#135]
I'm seeing a deadlock in a binding from a signal to a mutable property. Here's the relevant part of the stack trace:

![image](https://cloud.githubusercontent.com/assets/147686/20729626/d5d6dc8c-b650-11e6-8fec-940b170009d9.png)

(2) and (19) are the same signal, hitting the recursive send. Here's the current implementation of `<~`:

```swift
	public static func <~ <Source: SignalProtocol>(target: Self, signal: Source) -> Disposable? where Source.Value == Value, Source.Error == NoError {
		return signal
			.take(during: target.lifetime)
			.observeValues { [weak target] value in
				target?.consume(value)
			}
	}
```

I _think_ what's happening is:

1. Signal at (19) sends a value
2. The `observeValues` block is called with the value
3. Upon reading `target`, which has gone out of scope, the target's `deinit` gets called
4. This triggers `lifetime.ended` to complete
5. Because of `take(during:)`, the signal immediately tries to complete (lifetime has ended)
6. Deadlock, because the same signal is in the middle of sending a value

Unfortunately I haven't been able to write a test case that reproduces this.

**Comment by andersio** [comment]
Not sure if it is related: https://github.com/ReactiveCocoa/ReactiveSwift/issues/92#issuecomment-259833507.

But this should not be happening if the binding is truly the last weak reference to the `MutableProperty`.
