### ISSUE TITLE
Retain Action's state property

### ISSUE THREAD

**Issue by mdiep** [ReactiveCocoa/ReactiveSwift#142]
https://github.com/ReactiveCocoa/ReactiveSwift/pull/22#issuecomment-264883159

**Comment by andersio** [comment]
It is an unintentional, but does it need to be corrected? `bridgedAction` is actually the rare case IMO, while generally the `state` property is something that composed of properties owned by your view model (or view controller if one uses MVC).

**Comment by sharplet** [comment]
The change was unintentional, and I think surprising. My vote is for restoring the previous behaviour.

**Comment by andersio** [comment]
Note that with #117, only `MutableProperty` and existentials would be benefited from this.
