### ISSUE TITLE
[proposed question] How to dispose after observe

### ISSUE THREAD

**Issue by roodkcab** [ReactiveCocoa/ReactiveSwift#146]
I'd like to know how to dispose after `startWithValues` 

here's an example 

    A.combineLatest(B).startWithValues {
        let (a, b) = $0
        print(a, b)
    }

if A and B are both SignalProducer containing async operations
how to call dispose after startWithValues?

if we call dispose right after startWithValues i.e. `startWithValues {}.dispose()`
then it will just ignore startWithValues

or shall I use a CompositeDisposable to hold that disposable returned by startWithValues like below

    var dispose = CompositeDisposable()
    dispose += A.combineLatest(B).startWithValues {
        let (a, b) = $0
        print(a, b)
        dispose.dispose()
    }

the reason why I have to dispose it is to avoid duplicate signal, so maybe there's some other way to achieve that without dispose?

**Comment by andersio** [comment]
If you just need one value, use `take(first: 1)`. Or if you'd like the exact semantic without an intermediate disposable:
```swift
producer.startWithSignal { signal, disposable in
    signal.observeValues { disposable.dispose() }
}
```
Though I am not quite sure about what you would like to achieve though. If you give more information on how it is used and how it is expected to behave, we might be able to give better suggestions.

**Comment by roodkcab** [comment]
@andersio startWithSignal is exactly what I want! Thank u so much!
