### ISSUE TITLE
Bind textField in TableViewCell with Viewmodel

### ISSUE THREAD

**Issue by tunidev** [ReactiveCocoa/ReactiveSwift#150]
I am migrating to Swift 3 so I use now ReactiveSwift, I want to know the equivalence of this code in ReactiveSwift : 
   
      self.firstTextField.textSignal()
                .takeUntil(self.rac_prepareForReuseSignal) // Ignore after cell gets reused
                .distinctUntilChanged() // Only take value if different from previous one
                .skip(1) // Skip cell dequeue event
                .subscribeNext { _ in
                    firstField.stringValue = self.firstTextField.text
            }

**Comment by andersio** [comment]
You would need [ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveCocoa/) too.
