### ISSUE TITLE
How are delegates and callbacks "streams"?

### ISSUE THREAD

**Issue by snap9** [ReactiveCocoa/ReactiveSwift#151]
On the front page, https://github.com/ReactiveCocoa/ReactiveSwift, delegates and callbacks are listed under things that can be modeled as streams.

I can understand why this is true for delegates and callbacks **without return values** because you can just create a Signal or SignalProducer and throw events at them.

But what about delegates and callbacks **with return values**? I can't see how these can be modeled with ReactiveCocoa.

Ideas?

**Comment by andersio** [comment]
`Action` is one of the ways. For example: [https://github.com/ReactiveCocoa/ReactiveSwift/blob/2c0958a1e5b2813655990f9f37b845f37a6bd12b/README.md#action-a-serialized-worker-with-a-preset-action](you may see here that `Action` is capable of generating outputs specific for an invocation.)

**Comment by snap9** [comment]
@andersio Thanks, that could work. Is there a particular reason for why an `Action` based extension/subclass for UITableView (for replicating the delegate and data source) haven't been added to ReactiveCocoa? It feels like this would be a common thing people would want. All I see for UITableView in ReactiveCocoa is a hook to reloadData. Your thoughts? Thanks again.

**Comment by andersio** [comment]
We have limited resources. Right now the focus is on rolling out a stable ReactiveSwift release, and then one for ReactiveCocoa.

There is a rough plan on delegate interception (ReactiveCocoa #3333) which would allow these extensions. As for data sources though, my _personal_ stance is that these should not be included, but rather abstracted away with adapters and reactive collections. We are [making some progress](https://github.com/RACCommunity/ReactiveCollections/pulls), but I do not expect it to mainline anytime soon.

**Comment by snap9** [comment]
@andersio Hello, do you have any new updates/news/thoughts on delegate interception, data sources, and/or reactive collections? Thanks mate.

**Comment by andersio** [comment]
Delegate interception is in fact staging, albeit the reality that we are low on review bandwidth.

We also plan to offer collection digging (as a new framework) and collection binding (in RAC). The diffing part is staging in ReactiveCollections, while the binding part is pretty much still a WIP.
