### ISSUE TITLE
startWithSignal issue

### ISSUE THREAD

**Issue by maximbilan** [ReactiveCocoa/ReactiveSwift#162]
Hi,

I've updated really old project, I don't know details about this project and I've updated ReactiveSwift to the latest 1.0.0-rc.1. I've never used ReactiveCocoa, so it's hard to me fix this issue. I have the next lines:

```
let boardUpdatesSignal = NotificationCenter.default.reactive.notifications(forName: Notification.Name(rawValue: BBBoardManagerDidUpdateBoards), object: nil)
let collectionUpdatesSignal = NotificationCenter.default.reactive.notifications(forName: Notification.Name(rawValue: BBBoardManagerDidUpdateCollections), object: nil)

boardUpdatesSignal.combineLatest(with: collectionUpdatesSignal).throttle(2, on: QueueScheduler.main).startWithSignal { (signal, disposable) in
}
```

And I get the compilation error:
`Value of type 'Signal<(Notification, Notification), NoError>' has no member 'startWithSignal'`

Could you help me to fix this issue? Thanks in advance.

**Comment by andersio** [comment]
As shown in the error message, you are dealing with `Signal`s, so what you should use is `observe` and `observe(Values|Results|Completed|Failed)` instead of `start`.

**Comment by maximbilan** [comment]
Thanks.
