### ISSUE TITLE
rc 2 can't build success

### ISSUE THREAD

**Issue by lacklock** [ReactiveCocoa/ReactiveSwift#170]
headSerialDisposable.innerDisposable = headDisposable
<img width="521" alt="gt1111" src="https://cloud.githubusercontent.com/assets/6942765/21300588/40f9bc20-c5e0-11e6-8483-8e785a71c573.png">

**Comment by andersio** [comment]
Have you updated ReactiveCocoa to 5.0.0-alpha.5?
