### ISSUE TITLE
Compositional Property: producer never completes?

### ISSUE THREAD

**Issue by gavrix** [ReactiveCocoa/ReactiveSwift#172]
I've lost some context over last year or so, so my question maybe dumb.
However, `PropertyProtocol` declares the `producer` and `signal` and streams that send current and subsequent values and _complete when Property deinitializes_ 

Looking at the implementation of composed `Property`  I can see that `producer` and `signal` are simply propagated from what was given to Property at construction time, breaking the assumption that Property's producer completes after property was destroyed. Which means, the following test fails
```swift
let (signal, sink) = Signal<String, NoError>.pipe()
		
		
func createAndDestroyProperty() {
	let property = Property(initial: "", then: signal)
	property.producer
	.startWithValues({value in
		XCTAssert(value != "123" , "Should not have been triggered")
	})			
}

scoped()
sink.send(value: "123")
```

Am I missing something here?

**Comment by andersio** [comment]
Composed properties do not have its own lifetime, but rather a view to what it is derived from, akin to transformed `Signal`s.

**Comment by gavrix** [comment]
Ok, so I see that was intentional.
Out of curiosity, don't you think it may be confusing that given declaration `let p: Property<String>` the producer `p.producer` _may or may not_ complete depending on how that property was created? The type doesn't define full semantics of that thing. This reminds me of of `RACSignal` was split into `Signal` and `SignalProducer` so that type can clearly describe the semantics of the stream.
Have you considered splitting _composed_ `Property` into separate type to avoid that confusion?

**Comment by andersio** [comment]
`Property(capturing:)` is the only exception, and it is expected to be gone eventually with generalised existential.

**Comment by gavrix** [comment]
ok I see then.
But then, I believe `PropertyType` needs to be updated too.
```
public protocol PropertyProtocol: class, BindingSourceProtocol {
	associatedtype Value

	/// The current value of the property.
	var value: Value { get }

	/// The values producer of the property.
	///
	/// It produces a signal that sends the property's current value,
	/// followed by all changes over time. It completes when the property
	/// has deinitialized, or has no further change.
	var producer: SignalProducer<Value, NoError> { get }

	/// A signal that will send the property's changes over time. It
	/// completes when the property has deinitialized, or has no further
	/// change.
	var signal: Signal<Value, NoError> { get }
}
```

The docs are wrong and misleading.

**Comment by andersio** [comment]
Did that after answering you. 😅
#173

**Comment by gavrix** [comment]
Ah, good. I added comment there. 
Thank you for clarifying this to me! It's been a while since I last looked into sources, lost some context of what was changing.
