### ISSUE TITLE
Unable to compile with XCode 8.1 with CocoaPods installation of 4.0.1

### ISSUE THREAD

**Issue by sigmonky** [ReactiveCocoa/ReactiveSwift#174]
I am attempting a dirt simple implementation of ReactiveCocoa 4.0.1 using cocoapods and then trying to build the project using XCode 8.1

```
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target :reactiveprototype2 do
	pod 'ReactiveCocoa', '4.0.1'
end 
```
XCode prompts me to convert to Swift 3.0 syntax, but I ignore those prompts, deferring conversion with the 'later' option.

When attempting a build, I get this error message:
```
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to 
be configured correctly for targets which use Swift. 
Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version 
or use the Build Settings editor to configure the build setting directly.
```

What is the best course of action here?

**Comment by andersio** [comment]
If you are using Swift 3, specify `~> 5.0` or `5.0.0-alpha.5` specifically.

**Comment by sigmonky** [comment]
Thanks for the quick response. Updated as follows

```
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target :reactiveprototype do
	pod 'ReactiveCocoa', '5.0.0-alpha.5'
end 
````
still getting the same compile error

Am on Cocoapods 1.0.1. Could that be the issue?

**Comment by sigmonky** [comment]
After upgrading to Cocoapods 1.1.1, my app is now building. I also had a legion of problems with expired Ruby certs that I had to resolve. Have also installed Ruby 2.2.2p95. Cocoapods 1.1.1 requires at least Ruby 2.2.1. 

I would recommend adding this information to the installation documentation. It will save people alot of grief.
