### ISSUE TITLE
Bidirectional Bindings.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#181]
For two-way UI bindings, we'd need (as a summary of previous scattered discussions on Slack and various PR and issues):

1. [x] **Fine-grained Property Validations.**

2. [ ] **Decoupling of the presentation type and the actual stored type.**
    e.g. A property is stored as `Double`, but the View Model converts it into a `String` for presentation, and accepts `String` inputs that are convertible back into `Double` with its own rules.
   
3. [ ] **Write conflict handling.**

4. [ ] All of above in one thing, but configurable.

We could start iterating with basic building blocks, and eventually a two-way bindable construct. Some supporting constructs that might be needed:

1. [x] Changes to **`MutablePropertyProtocol` to support new features.**

1. [ ] **Standard binding "packages" for controls.**
    Let's call it `ControlPod` for the time being.
    e.g. `control.reactive.textPod` that packs `text`, `textValues` and `isEnabled` all together.

1. [ ] **Operator:** `<~>`.
    The operator allows `Bidirectional <~> ControlPod` and `Bidirectional <~> MutablePropertyProtocol`. Perhaps also `Action <~> ControlPod`?

**Comment by andersio** [comment]
A second thought though: All of these proposed constructs look representable in `Action` in some way. Perhaps extending `Action` would be better take, hmm? But we would need an `Action` that guarantees to cache the latest value.

**Comment by RuiAAPeres** [comment]
It feels to me, I might be wrong, that an Action is normally used between the UI and the ViewModel and tied to an user action (most of the times a tap on a `UIButton`).

**Comment by andersio** [comment]
It is one of its use case. But `Action` in general is a serialised worker that can have an internal state, and when fired it executes on a snapshot of the state, together with an arbitrary input.

See the example in the [README](https://github.com/ReactiveCocoa/ReactiveSwift#action-a-serialized-worker-with-a-preset-action).

**Comment by andersio** [comment]
[A gist](https://gist.github.com/andersio/fdbee89008a730e3e3a386d7d1fd5b3d) to illustrate the viability. I can think of various juicy ways to compose with wrapper based approach, esp. with conditional conformances. Not sure how the `Action` based variant can be composed though.

**Comment by andersio** [comment]
I have come to the conclusion that a generic two-way binding model (that works with mutable properties) would require recursive writebacks in properties... This isn't possible with `MutableProperty` yet, but is inherently available in any properties that work under the assumption of thread containment (i.e. no locking).

**Comment by andersio** [comment]
https://github.com/ReactiveCocoa/ReactiveSwift/commit/762e114d98aa21e4e83b900066fd7bb0746de1f8#diff-21725147fb11f1f3eb72b4e278ed5f76R18

Here is a 2-way binding prototype. Does it feel like something we'd be happy to work with? In a nutshell:
```
class TweetViewModel {
    let username: Upstream<MutableProperty<String>>

    init() {
        // Optional: a merge policy & a containing scheduler.
        username = MutableProperty("").makeUpstream()
    }
}

// Simple binding
viewModel.username <<~> textField
```

In a two-way binding, there is an upstream and 1+ downstream.

Both upstream and downstream can specify that it is contained by a specific scheduler, e.g. `QueueScheduler — UIScheduler`. The binding would resolve conflicts based on the merge policy specified by the upstream.

By default, everything uses `ImmediateScheduler`. If both ends are immediate, the merge policy is effectively ignored.

-

Should the merge policy and the containing scheduler be part of the `MutablePropertyProtocol` instead? In this case, `TransactionalProperty` would by default be two-way bindable. Perhaps also `MutableProperty`

But the problem is that merge policies cannot be inherited when transformed in `TransactionalProperty` unless the custom merge policy is removed, because backward transforms are failable, 

Another problem is that if we cover also availability of controls, it doesn't seem making sense for all `MutableProperty` and `TransactionalProperty` to have a permanent `isEnabled`, hmm.

**Comment by andersio** [comment]
Gonna rewrite.
