### ISSUE TITLE
Why is Observer called Observer?

### ISSUE THREAD

**Issue by mfclarke** [ReactiveCocoa/ReactiveSwift#193]
This has always confused me, and is always a strange thing to explain to a newbie.

"So, you observe a `Signal` to receive events, but you use the `Observer` to send events. No not the object observing a `Signal`, but a `Signal`'s `Observer` object"

Seems weird. Why not something like Sender?

**Comment by andersio** [comment]
`Signal` is just a composable construct that multicasts what are being put into it through its "event emitter" (i.e. "the `Signal`'s `Observer`"). So it is no different from any downstream observations in regard of being an act of observation.

**Comment by mdiep** [comment]
The `Observer` isn't sending the events; you're sending the events to the `Observer`.

Any API that uses a `Signal` but doesn't add an `Observer` implicitly adds an `Observer`.

**Comment by andersio** [comment]
@mdiep 
Would it help if we make a subclass of `Observer` for the event emitter (that overrides nothing)?

**Comment by mdiep** [comment]
I don't think anything needs to be done. I don't personally find this confusing.

**Comment by andersio** [comment]
When you observe a `Signal`, you **create** an `Observer` to react to the events.

When you create a `Signal`, a prepared `Observer` is **given** to you, and it multicasts the events you sent to it.

**Comment by mfclarke** [comment]
Thanks @andersio and @mdiep, this is much clearer now 👍
