### ISSUE TITLE
Ambiguous flatMap reference in RAC5

### ISSUE THREAD

**Issue by alper** [ReactiveCocoa/ReactiveSwift#194]
I'm just trying to rewrite this old code:
```
return NSURLSession.sharedSession()
  .rac_dataWithRequest(request)
  .flatMap(.Latest, transform: parseResponse)
  .mapError {error in NetworkError.fromError(error)}
  .observeOn(UIScheduler())
```
And hitting a bunch of stumbling blocks when trying to do that.

I get `'flatMap' produces 'SignalProducer<P.Value, AnyError>', not the expected contextual result type 'SignalProducer<JSON, NetworkError>'`

which I think means it is going towards this implementation of flatMap instead of the other ones:
`public func flatMap<P: PropertyProtocol>(_ strategy: FlattenStrategy, transform: @escaping (Value) -> P) -> SignalProducer<P.Value, Error> {`

No clue why it is not grabbing the right one. Also XCode seems to have a very hard time resolving all this stuff and keeps crashing and being unstable.

Commenting out the PropertyProtocol version of flatMap results in an "Ambiguous reference" since then it can't figure out anymore which of the flatmaps I should get. That leads me to believe that because of that ambiguity it defaults to the function that I don't want?

**Comment by sharplet** [comment]
What is the type of the `parseResponse` function? Given the first error message, I'm guessing that function may still be using `NSError` instead of `AnyError`.

**Comment by alper** [comment]
That is:
`func parseResponse(_ data: Data, response: URLResponse) -> SignalProducer<JSON, NetworkError> {`

NetworkError is a subclass of Error.

**Comment by sharplet** [comment]
Ok, so because `flatMap` can't change the error type, you'll need map the `AnyError` from `reactive.dataTask()` into a `NetworkError` _before_ you can call `parseResponse`. Something like this might work:

```swift
return URLSession.shared.reactive
  .dataTask(with: request)
  .mapError { NetworkError.fromError($0.error) }
  .flatMap(.latest, transform: parseResponse)
```

Also, is `parseResponse` synchronous or asynchronous? If it's synchronous, it would be simpler to have it return `Result<T, NetworkError>`, and then use `attemptMap` like this:

```swift
return URLSession.shared.reactive
  .dataTask(with: request)
  .mapError { NetworkError.fromError($0.error) }
  .attemptMap(parseResponse)
```

**Comment by alper** [comment]
Oddly enough I changed it to a map instead of a flatMap and that at least made the compiler happy:

```
    return URLSession.shared.reactive.data(with: request as URLRequest)
      .map { (d, u) -> JSON in
        // TODO fix
        return JSON(data: d)
      }
      .mapError { (e) -> NetworkError in
        return NetworkError.badRequest
      }
      .observe(on: UIScheduler())
```

I'll try your both suggestions.

**Comment by alper** [comment]
And then your first sample turns into something like this:

```
      return URLSession.shared.reactive.data(with: request as URLRequest)
        .mapError { NetworkError.fromError($0.error as NSError?) }
        .flatMap(.latest, transform: parseResponse)
        .observe(on: UIScheduler())
```

and then the compiler complains with:
`In argument type '(Data, URLResponse) -> SignalProducer<JSON, AnyError>', 'SignalProducer<JSON, AnyError>' does not conform to expected type 'PropertyProtocol'`

**Comment by andersio** [comment]
I have tried to reproduce it in playground, and it seems fine.

```swift
enum NetworkError: Error {
	init?(cocoa: AnyError) {
		return nil
	}
}

let urlReq = URLRequest(url: URL(string: "x-ras://")!)

func parseResponse(_ value: (Data, URLResponse)) -> SignalProducer<String, AnyError> {
	return SignalProducer.empty
}

URLSession.shared.reactive.data(with: urlReq)
	.flatMap(.latest, transform: parseResponse)
	.mapError { NetworkError(cocoa: $0)! }
	.observe(on: UIScheduler())

print("Hello")
```

**Comment by alper** [comment]
Thanks @andersio that and the signature change of parseResponse to a single parameter did the trick. And this is the resolution of a pretty long dead end during a swift 3 conversion.

**Comment by andersio** [comment]
@alper 
```swift
func parseResponse(data: Data, response: URLResponse) -> SignalProducer<String, AnyError> {
```

Named one works too, hmm.

**Comment by alper** [comment]
You're right…

I have no idea what was going wrong all this time and SourceKit was so slow and unstable that it's hard to work with it. Thanks a lot!

**Comment by doozMen** [comment]
@andersio why is the error init needed? It works for me but I cannot wrap my head around it.

**Comment by andersio** [comment]
@doozMen Could you be more specific about what you have a problem with?
