### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by ashfurrow** [ReactiveCocoa/ReactiveSwift#20]
Super excited about this project! I was wondering when you're thinking of tagging a release, even an prerelease version. Cheers!

**Comment by mdiep** [comment]
I thought I'd release a `3.0.0-alpha.1` version sometime this week. Letting the dust settle and trying to review some other PRs before swinging back around.

**Comment by liscio** [comment]
> I thought I'd release a `3.0.0-alpha.1` version sometime this week.

@mdiep Any reason it wouldn't be a `1.0.0-alpha.1`? Is it following the mindset that `1.0.0` was effectively the "swifty bits" of RAC 3, putting us at the 3rd major API release?

**Comment by neilpa** [comment]
I think we should start at `1.0` since this is a new library even though it's based on the existing RAC code.

**Comment by mdiep** [comment]
I thought 3.0 would be nice since (a) it's the 3rd major API release of this code and (b) it nicely mirrors Swift 3.0.

**Comment by neilpa** [comment]
I don't have a strong of an opinion either way. I'll also add that we may not always track Swift versions w/ this lib.

**Comment by mdiep** [comment]
> I'll also add that we may not always track Swift versions w/ this lib.

Totally.

I'm open to releasing as 1.0 if that's what people think is best.

**Comment by sharplet** [comment]
I also don't have strong feelings, but I think 1.0 makes a lot of sense 👍

**Comment by NachoSoto** [comment]
I vote for 1.0 too.

**Comment by ikesyo** [comment]
Let's make it sure that we use `1.0.0` for the tag to avoid this: https://github.com/Carthage/Commandant/issues/75 🙏

**Comment by mhuusko5** [comment]
Might today be release day for the new architecture/components? I have a couple projects building/working fine with ReactiveSwift/ObjC/Cocoa/ObjCBridge together. Would love to see even just some alpha tags (ReactiveSwift 1.0.0-alpha.1, ReactiveObjC 1.0.0-alpha.1, ReactiveCocoa 5.0.0-alpha.1, ReactiveObjCBridge 1.0.0-alpha.1?) pushed, if people are comfortable with that.

**Comment by chrisdhaan** [comment]
Any update when a tagged release may exist for this? Hoping to get the Reactive framework into a new project but need support for Swift 3.0

**Comment by mdiep** [comment]
I should be able to release an alpha version this weekend.

**Comment by chrisdhaan** [comment]
Awesome! Super excited! Love this framework.

**Comment by mdiep** [comment]
https://github.com/ReactiveCocoa/ReactiveSwift/releases/tag/1.0.0-alpha.1 🎉 

If you find something that should be covered in the release notes or migration guide, please open PR or leave a note here!

**Comment by ikesyo** [comment]
I will push the first alpha release to CocoaPods Trunk once #35 is merged.

**Comment by RuiAAPeres** [comment]
@mdiep awesome work! On the notes it reads:

> Signals complete when they have no observers and there are strong references to them

Shouldn't it be "and there are **no** strong references"

**Comment by RuiAAPeres** [comment]
Ah I see, nevermind my comment.

**Comment by ikesyo** [comment]
https://github.com/ReactiveCocoa/ReactiveSwift/issues/20#issuecomment-249349961: ReactiveSwift 1.0.0-alpha.1 is now on CocoaPods Trunk

```bash
$ pod trunk info ReactiveSwift

ReactiveSwift
    - Versions:
      - 1.0.0-alpha.1 (2016-09-24 11:53:35 UTC)
    - Owners:
      - Syo Ikeda <...>
      - Ash Furrow <...>
      - Nikita Leonov <...>
```
