### ISSUE TITLE
Action binding target?

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#209]
Just wondering if it is worth introducing some kind of `ActionBindingTarget` that supports binding also the availability of the action. So we could turn control bindings to be operator based (generic is supported), and drop `CocoaAction` in ReactiveCocoa.

For example:
```swift
submitButton.reactive.pressed = CocoaAction(viewModel.submit)
```

would become:

```swift
// Long form.
submitButton.reactive.pressed <~>> viewModel.submit

// Default action.
submitButton <~>> viewModel.submit
```

P.S. `<~>>` is a placeholder of the bidirectional binding operator. The double arrow indicates the upstream.

**Comment by RuiAAPeres** [comment]
I think this boils down to taste. I do like some well thought custom operators, although I am sure a lot of people don't. I am personally 👍 for this.
