### ISSUE TITLE
How to program UI now, without unsafeCocoaAction?

### ISSUE THREAD

**Issue by nikita-leonov** [ReactiveCocoa/ReactiveSwift#21]
It seems that `unsafeCocoaAction` was removed for the obvious reasons, but now it is unclear what to do with the programming of UI. Is there other sub-project with an extension of `Action` with  `unsafeCocoaAction` that should be used for this purpose?

**Comment by mdiep** [comment]
`unsafeCocoaAction` remains part of https://github.com/ReactiveCocoa/ReactiveCocoa since it's Cocoa specific.

**Comment by nikita-leonov** [comment]
Thanks, sounds reasonable. Do I understand it right that ReactiveCocoa will be only Cocoa-specific, while ReactveSwift will be its Swift based foundation? As a result, there will be no two `Action` classes in both ReactiveSwift and ReactiveCococa code-bases.

**Comment by mdiep** [comment]
ReactiveCocoa is now built on top of ReactiveSwift. All the cross-platform bits are in ReactiveSwift; all the Cocoa-specific bits are in ReactiveCocoa. So `Action` is in ReactiveSwift, but `CocoaAction` is in ReactiveCocoa.
