### ISSUE TITLE
Value of type 'UITextField' has no member 'reactive'

### ISSUE THREAD

**Issue by 861645007** [ReactiveCocoa/ReactiveSwift#212]
![ae55d7e2-1844-4ea4-a3d7-2c021b62828e](https://cloud.githubusercontent.com/assets/7790051/21635717/3472566c-d29a-11e6-8663-0c9ac08ecf5b.png)

**Comment by 861645007** [comment]
It can't show photo?????

**Comment by ikesyo** [comment]
That is a UIKit extension so defined in separate [ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveCocoa) framework.

**Comment by 861645007** [comment]
@ikesyo This means that I have to introduce ReactiveCocoa???

**Comment by ikesyo** [comment]
Yes.

**Comment by 861645007** [comment]
thank you @ikesyo

**Comment by 861645007** [comment]
@ikesyo  
and could you  tell me the relationship between reactiveswift and reativecocoa。

reactiveCocoa  is just an extension of UI？？？？

**Comment by ikesyo** [comment]
Please see ReactiveCocoa's README: https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/README.md#what-is-reactivecocoa

**Comment by shyamala-tj** [comment]
@Huanqiang me too facing the same issue.Do I need to add both ReactiveSwift and ReactiveCocoa framework to resolve the same?
