### ISSUE TITLE
Memory Leaks question

### ISSUE THREAD

**Issue by oinsider** [ReactiveCocoa/ReactiveSwift#216]
Hi all, 

I have this kind of view model classes for encapsulating the calculations of each view of my app. I init the model with a parent view model instance that provides the SignalProducer object based on a Signal. (I don´t retain the parent view model)

```
class ViewModel {
    let aProperty = MutableProperty<Int>(0)
    var disposable: Disposable?
    init(parentViewModel: ParentViewModel) {
        disposable =
            parentViewModel
                .requestEvents()
                .map { ParentViewModel.countStatus(property: $0) }
                .observe(on: UIScheduler())
                .start(Observer(
                    value: { [weak self] (statusCount)) in
                        self?.aProperty.value = statusCount
                    },
                    completed: {
                }))
    }
    deinit {
        disposable?.dispose()
    }
}
```

I think that shouldn't be any issue with this code in regards to memory leaks. But when I see the memory graph in Xcode is quite worrying. There are a lot of Observer instances and contiguousArrayStorage leaks. 

<img width="1404" alt="captura de pantalla 2017-01-09 a las 16 16 53" src="https://cloud.githubusercontent.com/assets/645151/21772398/66f38a58-d68b-11e6-9391-dda45bb90576.png">

In [this](https://github.com/ReactiveCocoa/ReactiveSwift/issues/94) issue, I understand that the signal contains a signal state that references to itself creating the 2-node cycle as long as the signal stays alive. 

Should I be worried about this memory issues or am I doing something wrong? What should be the correct approach for a good memory management?

Thanks!

**Comment by mdiep** [comment]
Your signal producer is never completing, from the looks of it. You probably need to use `take(during:)` or dispose of `disposable`.

**Comment by oinsider** [comment]
Hi @mdiep I just updated the example code. I dispose the signal on the instance deinitialization. Anyway, the  2-node cycles appear right after the initialization of the view models.

Thanks!

**Comment by mdiep** [comment]
Oh, I'm sorry. Now I understand what you're describing.

AIUI, Xcode's memory debugger reports false positives. That's what's happening here. It sees the intentional retain cycle and reports it as leaked memory. It doesn't know that the retain cycle is cleaned up later. I believe Instruments will yield different results.

**Comment by oinsider** [comment]
Oh, ok that has a lot of sense! thanks for your answer @mdiep  😀
