### ISSUE TITLE
Port SignalProducer.deferredRetry from Rex?

### ISSUE THREAD

**Issue by NachoSoto** [ReactiveCocoa/ReactiveSwift#224]
It would be nice to have this here: https://github.com/RACCommunity/Rex/blob/master/Source/SignalProducer.swift#L106-L126.

**Comment by andersio** [comment]
Can be renamed to `retry(upTo:interval:on:)`.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
