### ISSUE TITLE
Asynchronous operators and producer interruption.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#227]
Interrupting a `SignalProducer` applied with an asynchronous operator currently delivers `interrupted` (usually) immediately and synchronously.

```swift
it("should deliver the interrupted event immediately") {
	let scheduler = TestScheduler()
	var signalInterrupted = false
	var observerInterrupted = false

	let (signal, _) = Signal<Int, NoError>.pipe()

	SignalProducer(signal)
		.observe(on: scheduler)
		.on(interrupted: { signalInterrupted = true })
		.startWithInterrupted { observerInterrupted = true }
		.dispose()

	expect(signalInterrupted) == false
	expect(observerInterrupted) == true // ⁉️

	scheduler.run()
	expect(signalInterrupted) == true
	expect(observerInterrupted) == true
}
```

I am not sure if this is ideal. Say when applying `observe(on:)` to a `SignalProducer`, my expectation would be **all** event being delivered on the specified scheduler. But it clearly is not the case.

Moreover, the current implementation also _short-circuits_ the `interrupted` event delivery. So even if there is actually a `completed` or `failed` event propagating from the upstream(s), the event would still be dropped if the interrupt is initiated before it arrives.

IMO, the `interrupted` event should respect all the applied operators. It should also originate from the ultimate upstream(s) to maintain a consistent event order.

`failed` and `interrupted` are defined to be [delivered immediately](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Documentation/DesignGuidelines.md#failures-behave-like-exceptions-and-propagate-immediately), but as implied by the context the immediacy is only with regard to time-shifting. On the other hand, asynchronous operators have a [strong implicit guarantee that all events should be delivered on the specified scheduler](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Documentation/DesignGuidelines.md#observe-events-on-a-known-scheduler).

#### API changes
This might break existing use that depends on the fraudulent behavior, e.g. `debounce` (Fixed in #228).

/cc @ReactiveCocoa/reactiveswift

**Comment by mdiep** [comment]
Oof. That's tricky. I'm not sure which is right. But it seems like a 2.0 change if we make it.

**Comment by mdiep** [comment]
Per #424, this has been resolved.
