### ISSUE TITLE
How to perform 'then' event the last signal producer failed?

### ISSUE THREAD

**Issue by IanLuo** [ReactiveCocoa/ReactiveSwift#235]
Currently I have to return the next signal producer in both `flatMap` and `flatMapError` to handle both cases to perform the next signal producer,  if I use `then`, the next won't perform if the last one emit error.

So any suggestions?

**Comment by sharplet** [comment]
It's probably not the most intention-revealing code, but you could use something along the lines of `foo.materialize().then(next)`.

**Comment by IanLuo** [comment]
thanks, it works.
