### ISSUE TITLE
Reactive with generic base, possible?

### ISSUE THREAD

**Issue by ianbytchek** [ReactiveCocoa/ReactiveSwift#238]
Consider the following situation.

```swift
class Foo<T>: NSObject {}
```

I need a reactive extension for `Foo`. It seems very obvious, but the questions is rather ambiguous – I can't find much information on this. Compiler complains with the following messages:

```swift
extension Reactive where Base:Foo {} // Error: reference to generic type 'Foo' requires arguments in <...>
extension Reactive where Base:Foo<T> {} // Error: use of undeclared type 'T'
    
extension Reactive where Base:Foo<Any> {
    func test() { Swift.print(self) }
}
    
let foo = Foo<NSObject>()
foo.test() // Error: 'NSObject' is not a subtype of 'Any'
```

Am I being dumb and missing something obvious or is there a trick?

**Comment by andersio** [comment]
You would need to introduce a protocol that `Foo` conforms to, so as to constrain the type parameter.

**Comment by ianbytchek** [comment]
Wouldn't it be a little unuseful in a real life situation? I'm trying to figure out if this is a language limitation or not. Swift bug tracker has a lot of generic-related issues, perhaps this is one of them?

**Comment by andersio** [comment]
It is a language limitation. You cannot parameterize an extension at this moment.

**Comment by ianbytchek** [comment]
Continues at https://bugs.swift.org/browse/SR-3716.

**Comment by andersio** [comment]
It had a place in the Swift Core Team Doug Gregor's Generic Manifesto.

**Comment by ianbytchek** [comment]
[This](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160229/011666.html) one?

**Comment by andersio** [comment]
Yes.

**Comment by ianbytchek** [comment]
Just remembered when came across [this on SO](https://stackoverflow.com/a/49992354/458356)!

```swift
extension Reactive
{
    public func foo<T>: Signal<T, NoError> where Base: MyGeneric<T> {
        // …
    }
}
```

**Comment by fritzgerald** [comment]
here is the solution I found that allow to create computed properties and not pollute the reactive namespace.

```
class GenericView<T>: UIView { }

extension GenericView {
  struct Reactive<T> {
    let base: GenericView<T>
    
    fileprivate init(_ base: GenericView<T>) {
      self.base = base
    }
  }
  
  var reactive: Reactive<T> {
    return Reactive(self)
  }
}

extension GenericView.Reactive {
  var reactiveComponent: Observable<Element?> {
    ...
  }
}
```
