### ISSUE TITLE
Best practice to replace `CocoaAction`?

### ISSUE THREAD

**Issue by justinmakaila** [ReactiveCocoa/ReactiveSwift#24]
I noticed that `CocoaAction` was removed from `ReactiveSwift`. I'm trying to find a way to replace this functionality:  

```swift
signUpButton.addTarget(viewModel.signUpButtonAction, action: CocoaAction.selector, for: .touchUpInside)
```
I'm thinking it'd be best to just handle in an `@IBAction` and call `apply(_:).start()` on the action, but wanted to ask to see if there was a prescribed way to achieve it.

**Comment by mdiep** [comment]
`CocoaAction` is a part of [ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveCocoa/), since it's Cocoa-specific.

You should include ReactiveCocoa as a dependency. ☺️

**Comment by justinmakaila** [comment]
👍 I didn't realize how the separation from `RAC` to `RAS` happened; makes total sense. Thanks!
