### ISSUE TITLE
Trying to understand an issue

### ISSUE THREAD

**Issue by craigzour** [ReactiveCocoa/ReactiveSwift#242]
Hi,

I would like you guys to take a look at the following code sample that crashes when the `threshold` is above a certain value.

```swift
let threshold: UInt64 = 10000

func nextValue(previousValue: UInt64) -> SignalProducer<UInt64, NoError> {
    return SignalProducer(value: previousValue + 1)
}

func getMaxValue(previousValue: UInt64) -> SignalProducer<UInt64, NoError> {
    return nextValue(previousValue: previousValue).flatMap(.concat) { value -> SignalProducer<UInt64, NoError> in
        if value < threshold {
            return getMaxValue(previousValue: value)
        } else {
            return SignalProducer(value: value)
        }
    }
}

waitUntil(timeout: 60) { done in
    getMaxValue(previousValue: 0).startWithValues { value in
        print("DEBUG >>> \(value)")
        done()
    }
}
```

Here is a screenshot with one part of the stack trace:

<img width="997" alt="screen shot 2017-02-01 at 11 02 10 am" src="https://cloud.githubusercontent.com/assets/1763961/22514974/07c8a806-e86f-11e6-9c8d-199c9a29c4c1.png">

Complete strack trace: https://gist.github.com/craigzour/36c77b3c162c2dd731ca4b47a7c827c4

I am wondering if this can be the root cause of some other code I have in my project and which runs on top of Reactive Swift 1.0 now that I migrated it to Swift 3 (before, with Swift 2.3 and ReactiveCocoa 4.2.2 there was no such issue). 
Here is the complete stack trace for the main issue: https://gist.github.com/craigzour/7248faef9de9460aca2973efe43fd62d

**Comment by mdiep** [comment]
In the code you posted above, you're blowing the stack.

I'm not sure if that's the case in the other stack trace you posted.
