### ISSUE TITLE
Strange build warnings in Xcode 8

### ISSUE THREAD

**Issue by SparrowBlaze** [ReactiveCocoa/ReactiveSwift#25]
I'm probably doing something wrong, but I keep getting build warnings such as "/Path/To/ReactiveCocoa-master/Carthage/Checkouts/ReactiveSwift/ReactiveSwift.xcodeproj _The file “iOS-Framework.xcconfig” couldn’t be opened._ (/Path/To/ReactiveCocoa-master/Carthage/Checkouts/ReactiveSwift/Carthage/Checkouts/xcconfigs/xcconfigs/iOS/iOS-Framework.xcconfig)"

Before, it was saying that it couldn't be opened because it couldn't resolve the path. I've since resolved those paths in the navigator, and now it just says it doesn't want to open them. I'm getting these in iOS-Framework.xcconfig, Debug.xcconfig, and Release.xcconfig.

Anyone know more than me about these?

**Comment by ikesyo** [comment]
You might not get the submodules recursively. Would `git submodule update --init --recursive` or `carthage checkout` in `/Path/To/ReactiveCocoa-master` help?

**Comment by SparrowBlaze** [comment]
It wouldn't build at all (got errors not warnings) when the submodules weren't there, so I put them in manually... I can confirm that the files are indeed there, and Xcode doesn't deny that, it just says it can't open them. Should I wipe the whole thing and try it with Carthage or Swift Package Manager instead?

**Comment by SparrowBlaze** [comment]
Well, it works now. So much for a dedicated Frameworks folder for my other projects... heh
