### ISSUE TITLE
`Property`'s signal behaviour

### ISSUE THREAD

**Issue by RuiAAPeres** [ReactiveCocoa/ReactiveSwift#253]
In the following setup:

```swift
let (signal, observer) = Signal<Foo, NoError>.pipe
let skipRepeatedValues = signal.skipRepeats()

let a: Foo // where Foo is `Equatable` and a value type

let property = Property(initial: a, then: skipRepeatedValues)
property.signal.observe { foo in 
   print(foo)
}

observer.send(value: a)
```

As it stands, the `a` sent in the last line, will be printed. My question is: is this the desired behaviour? My initial expectation was:

1. initial value is `a`.
2. I am skipping repeated values
3. Sending/Generating a new value that is equal to `a` shouldn't be propagated. 

On the other hand, if I do:

```swift
observer.send(value: a)
observer.send(value: a)
```

The second will be skipped.

**Comment by NachoSoto** [comment]
That sounds like a bug to me.

**Comment by NachoSoto** [comment]
Oh wait, never mind, I read this wrong. `skipRepeats` is only applied to the signal that's concatenated to the initial value. So this is working as expected.

**Comment by mdiep** [comment]
Yeah, you'd need to `skipRepeats` on the `Property`.

```swift
let (signal, observer) = Signal<Foo, NoError>.pipe

let a: Foo // where Foo is `Equatable` and a value type

let property = Property(initial: a, then: signal).skipRepeats()
property.signal.observe { foo in 
   print(foo)
}

observer.send(value: a)
```

**Comment by RuiAAPeres** [comment]
Ah I see https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Property.swift#L535,
makes sense. Thanks @mdiep and @NachoSoto. 👍
