### ISSUE TITLE
Compiler error calling SignalProducer.start

### ISSUE THREAD

**Issue by ninjudd** [ReactiveCocoa/ReactiveSwift#256]
I just updated from `1.0.0-alpha.4` to `1.0.0`, and now I'm getting a compiler error I can't figure out.

The following code used to work:

```swift
func send(request: URLRequest) -> SignalProducer<(Data, URLResponse), NSError> {
    return SignalProducer({ observer, disposable in
        let signal = self.session.reactive.data(with: request)
        disposable.add(signal.start(observer))
    })
}
```

But now I get the following Swift Compiler Error:

> Cannot invoke 'start' with an argument list of type '(Observer<(Data, URLResponse), NSError>)'
> Overloads for 'start' exist with these partially matching parameter lists: (Observer<Self.Value, Self.Error>), (@escaping (Event<Self.Value, Self.Error>) -> Void)

I've tried adding more type information and calling `startWithSignal` directly, but no luck. Any ideas how to fix this?

**Comment by NachoSoto** [comment]
You probably want to use `Error` instead of `NSError`.

**Comment by ninjudd** [comment]
I tried that too. With this code:

```swift
func send(request: URLRequest) -> SignalProducer<(Data, URLResponse), Error> {
    return SignalProducer({ observer, disposable in
        let signal = self.session.reactive.data(with: request)
        disposable.add(signal.start(observer))
    })
}
```

I get the following error:

> Using 'Error' as a concrete type conforming to protocol 'Error' is not supported

**Comment by ninjudd** [comment]
And with this code:

```swift
func send<Error>(request: URLRequest) -> SignalProducer<(Data, URLResponse), Error> {
    return SignalProducer({ observer, disposable in
        let signal = self.session.reactive.data(with: request)
        disposable.add(signal.start(observer))
    })
}
```

I get this error:

> Cannot invoke 'start' with an argument list of type '(Observer<(Data, URLResponse), Error>)'

**Comment by ikesyo** [comment]
Not `Error`, but `AnyError`.

**Comment by ikesyo** [comment]
`URLSession.reactive.data` now returns `SignalProducer<(Data, URLResponse), AnyError>` ( as I said above) so you should change the return type of your function to `SignalProducer<(Data, URLResponse), AnyError>` as well.

**Comment by ninjudd** [comment]
I have to say, `AnyError` completely confuses me. Is there a good resource to better understand when to use `AnyError` and why it is preferable to `NSError`? Should I be replacing every single `SignalProducer<_, NSError>` with `SignalProducer<_, AnyError>`?

**Comment by mdiep** [comment]
I _think_ the primary driver is that `NSError` isn't available on all platforms.

**Comment by andersio** [comment]
Swift 3.0 bridges `NSError` to a couple of concrete `Error` types if possible. Ideally, if existentials (protocol types) are self-conforming, we could use `Error` directly. But it wasn't the case (yet), so we have to wrap the error.

I do wonder if the signature should be more specific, i.e. `SignalProducer<(Data, URLResponse), URLError>` instead.

**Comment by sharplet** [comment]
@ninjudd Like the host of other cases in Swift where it's encouraged to use bridged native types, `NSError` got the same treatment in [SE-0112](https://github.com/apple/swift-evolution/blob/master/proposals/0112-nserror-bridging.md). Unfortunately, that proposal landed _after_ WWDC 2016 (but still in time to be included in Swift 3), and as a result there's not a lot of documentation out there for functionality.

As a result, there should actually be very little occasion to use `NSError` directly. `AnyError` is a workaround, as @andersio mentioned, for a limitation of Swift which prevents `Signal<T, Error>` from being valid. The idiomatic way to work with `AnyError` is to grab the `var error: Error` value it wraps, and then using pattern matching on specific error types like `URLError`, `CocoaError`, `POSIXError`, et al.
