### ISSUE TITLE
Playground bootstrap missing

### ISSUE THREAD

**Issue by alper** [ReactiveCocoa/ReactiveSwift#258]
The playground documentation says to run the `script/bootstrap` which is not there anymore.

The carthage bootstrapping works fine though, so either:

- restore the `script/bootstrap`
- remove it from the documentation

**Comment by mdiep** [comment]
What version are you using? The documentation should refer to git commands now. (And I don't see any remaining references to `script/bootstrap` locally.)

**Comment by alper** [comment]
Oh sorry, you are right and I was behind. Thanks!
