### ISSUE TITLE
Sometimes Atomic...isn't, really

### ISSUE THREAD

**Issue by sharplet** [ReactiveCocoa/ReactiveSwift#269]
This code has a subtle thread-safety bug:

```swift
let strings = Atomic(["one", "two"])

strings.value = ["this", "is", "atomic"]

strings.value[1] = "isn't" // not actually atomic
```

Mutating the array through its subscript causes both a get and a set. This causes the lock to be acquired and released twice. The only way to do this safely is using `modify`:

```swift
strings.modify { $0[1] = "foo" }
```

Is this enough of a problem for us to consider removing the computed `value` property? I don't think there's any way we can guarantee this safe and keep the current API. One option would be to make `value` read-only, and provide a new `setValue(_:)` method.

**Comment by mdiep** [comment]
*shakes fist* L-valueeees!

**Comment by andersio** [comment]
The same thing happens to `MutableProperty` too. I'd say it is not worth the effort though.

**Comment by andersio** [comment]
It feels like we should [wait for the language to solve it](https://github.com/apple/swift/blob/master/docs/proposals/Accessors.rst), since the semantics of the public API are not the fault.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
