### ISSUE TITLE
Rename `UIScheduler` to `MainQueueScheduler`

### ISSUE THREAD

**Issue by dmcrodrigues** [ReactiveCocoa/ReactiveSwift#277]
ReactiveSwift should be 100% agnostic of any specific domain, `UIScheduler` is associated to `libdispatch`'s main queue which is the queue where all UI operations need to be scheduled but that domain is specific to iOS and macOS, for example on Linux does not make much sense having a scheduler called `UIScheduler` which explicitly redirect us to user interface and implicitly to main queue.

This probably was kept for historical reasons but I think we should rename to be clear about the queue where things are in fact scheduled and possibly provide an alias in `ReactiveCocoa` to keep `UIScheduler` since it fits in the domain.

**Comment by ikesyo** [comment]
`MainQueueScheduler` seems confusing as we have `QueueScheduler.main`.

**Comment by mdiep** [comment]
`UIScheduler` isn't quite a main queue scheduler. As @ikesyo pointed out, that exists as `QueueScheduler.main`. `UIScheduler` really is UI-specific—that's the reason for its "as soon as possible" policy.

I think the two options are to either leave it untouched or to move it into ReactiveCocoa. Truthfully, I don't know enough about Linux UI development to know whether it'd be useful. (Although I assume it'd be tied to a specific thread as well.)

**Comment by andersio** [comment]
I'd argue that the current `UIScheduler` is essentially `QueueScheduler.main` with a specific order-preserving optimization, which can be extended to `QueueScheduler`.

It doesn't really tie to the main thread, as child queues of the main queue do not inherit the queue specifics.

**Comment by mdiep** [comment]
> I'd argue that the current UIScheduler is essentially QueueScheduler.main with a specific order-preserving optimization, which can be extended to QueueScheduler.
> 
> So perhaps we fold UIScheduler into QueueScheduler, heh?

No, I think that optimization changes the semantics, requiring it to be a separate scheduler.

**Comment by andersio** [comment]
Let's say GTK, it still has the "main thread" requirement.

https://developer.gnome.org/gdk3/stable/gdk3-Threads.html

**Comment by dmcrodrigues** [comment]
> UIScheduler really is UI-specific

That's exactly my main concern, why should we have anything UI-specific here? ReactiveSwift should be all about _streams of values over time_ and leave anything UI-specific for other projects like we have in ReactiveCocoa. 

> Let's take GTK+ as an example, it still has a "main thread" requirement.

**Comment by mdiep** [comment]
I don't think ReactiveSwift needs to exclude anything UI-related. Bindings, e.g., are basically a UI feature.

ReactiveSwift shouldn't have anything that's platform-specific. That's where I think the line is.

**Comment by dmcrodrigues** [comment]
> I don't think ReactiveSwift needs to exclude anything UI-related.

I disagree mainly because UI is almost entirely platform-specific and many projects do not have any kind of interface, e.g. frameworks, command line tools like Carthage for example, so this kind of scheduler will not only be redundant for many but may also introduce unnecessary confusion.

> ReactiveSwift shouldn't have anything that's platform-specific.

And in the end, that's exactly what `UIScheduler` is because is tightly coupled to iOS and macOS even without referring to UIKit and AppKit, _main queue_ is the _main thread_ on these platforms but that does not necessarily apply to others.

**Comment by andersio** [comment]
> main queue is the main thread on these platforms but that does not necessarily apply to others.

As long as libdispatch and Foundation are still part of Swift, apparently [libdispatch assumes the main queue is associated with the main runloop or the main thread](https://github.com/apple/swift-corelibs-libdispatch/blob/master/man/dispatch_queue_create.3#L109), and main runloop is still a thing in Foundation.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
