### ISSUE TITLE
async / await semantics for ReactiveSwift

### ISSUE THREAD

**Issue by larryonoff** [ReactiveCocoa/ReactiveSwift#278]
Hello community. I'm long term user of ReactiveCocoa / ReactiveSwift. But I still think that Reactive pipes are quite complex to understand / support. C# introduces very clear and useful approach of working with asynchronous code.

What community thinks about introducing async / await semantics as a part of standard library or some related library?

So I would like to start some discussion related to this topic.

I've created simple code example below.

```swift
let producer: SignalProducer<Value, Error>

do {
   guard let value = try await(producer) else {
      return
   }
} catch let error as Error {
   print(error)
} catch { }
```

**Comment by ikesyo** [comment]
Question: What is the value, is it the first or last value of the producer?

I'm not a fan of the syntax and I think that `first()`, `last()`, `single()` and `wait()` operators should be used selectively.

**Comment by larryonoff** [comment]
@ikesyo it's a good argument, but `first()`, `last()`, `single()` and `wait()`, are very specific operators and return `Result`. They cannot be used with `try` / `catch`. 

So I have two ideas about this:
 1. Introduce operators like `first()` / `last()`, but for `try` / `catch`.
 2. Rename these operators to something like away / async. But I'm not sure that it's good, because doesn't provide similar semantics yet.

**Comment by ikesyo** [comment]
> They cannot be used with try / catch.

`Result` has `dematerialize` function for try / catch: https://github.com/antitypical/Result/blob/3.1.0/Result/Result.swift#L42

**Comment by larryonoff** [comment]
Thank you for mentioning!

Look how weird it will look like.

```
let producer: SignalProducer<Value, Error>

do {
   // 1. await version
   guard let value = try await(producer) else {
      return
   }
   
   // 2. already existing version
   guard let value = try producer.first()?. dematerialize() else {
      return
   }
} catch let error as Error {
   print(error)
} catch { }
```

**Comment by mdiep** [comment]
This might be a good candidate for https://github.com/RACCommunity.

**Comment by andersio** [comment]
The proposed `await` does not give a clear indication of which value should be captured, while as @ikesyo said it can be done by introducing throwing versions of `first` and `last` instead of a free function.

**Comment by larryonoff** [comment]
@mdiep RACCommunity is a great idea! I just wanted to discuss this with community to define some base API.

**Comment by larryonoff** [comment]
@andersio you're absolutely correct! what about
* `awaitFirst`
* `awaitLast`
?

**Comment by andersio** [comment]
One thing you might want to keep in mind is that semaphores are not eligible of resolution of priority inversion, so as these semaphore-fuelled blocking operators. IOW they are not always safe on all Cocoa platforms.

**Comment by larryonoff** [comment]
@andersio very good notice. I'm a bit stuck after this :)

**Comment by andersio** [comment]
The point is that due to how Darwin schedules threads, blocking execution to wait for another thread nondeterministically is just not safe. `Signal` is a thread aware construct that accepts events from any threads.

**Comment by larryonoff** [comment]
I'm closing this issue since I'm not sure that my proposal is good now.
