### ISSUE TITLE
Compilation error with Xcode 8.3 beta 2, related to @inline(__always)

### ISSUE THREAD

**Issue by trinhngocthuyen** [ReactiveCocoa/ReactiveSwift#283]
I am using Xcode 8.3 beta 2 and there is a compilation error **"let 'value' is private and cannot be referenced from an '@inline(__always)' function"**
<img width="1124" alt="issue_rac_xcode83" src="https://cloud.githubusercontent.com/assets/8844044/23348766/cf6876aa-fcdf-11e6-9c2d-5a76f1454fd6.png">
This issue was reported to Apple at https://bugs.swift.org/browse/SR-4013, and was resolved as "won't do".
Is there any way to overcome it (without removing the inlining specification)?
Thanks!

**Comment by andersio** [comment]
`master` already resolved it, and we will release 3.1 soon.

**Comment by andersio** [comment]
1.1.0 has been released. 😁
