### ISSUE TITLE
debounce/throttle operator that always emits the last value

### ISSUE THREAD

**Issue by NachoSoto** [ReactiveCocoa/ReactiveSwift#287]
I just found myself needing such an operator. I have a `SignalProducer<[Data], NoError>` created with this custom operator:
```swift
public func collectIncrementally() -> Signal<[Value], Error> {
    return self
        .map { [$0] }
        .scan([], +)
}
```

I want to limit how often I get updated arrays, but I do want to make sure that the last value (which will contain all the elements), is always emitted.

**Comment by NachoSoto** [comment]
Actually I misread the documentation, but I'm still not 100% sure either `debounce` or `throttle` will behave this way, so I guess this is a question now, not a feature request :P

**Comment by NachoSoto** [comment]
Yeah, it does look like if the source signal terminates **before** the given interval, no more cached values are sent. This is not documented, and I'm not sure if it's desired behavior. Either way, it would be nice to have an operator that doesn't behave this way.
I looked at `Rx`'s versions and they don't seem to have this either.

**Comment by andersio** [comment]
It was documented before the revision. Guess we should put it back, alongside an option. A `discardsWhenTerminated` label, perhaps?

https://github.com/ReactiveCocoa/ReactiveSwift/commit/5f7109d57306f9204030172f3e8b6df37b1e5f1a#diff-09166f905ad1f830ac2dc91f2663c1a5L1728

**Comment by NachoSoto** [comment]
> Guess we should put it back, alongside an option. A discardsWhenTerminated parameter with a default of true, perhaps?

That makes sense to me 👍

**Comment by Qata** [comment]
@andersio Would it be welcome if I picked up this issue and created an implementation?

**Comment by andersio** [comment]
@Qata Sure. 👍

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
