### ISSUE TITLE
DispatchQueue autorelease pool

### ISSUE THREAD

**Issue by NachoSoto** [ReactiveCocoa/ReactiveSwift#288]
[Peter's tweet](https://twitter.com/steipete/status/837547966059565056) got me thinking, so I checked `ReactiveSwift`'s implementation. We use `DispatchQueue(label:qos:target:)`, which has an optional [`autoreleaseFrequency`](https://developer.apple.com/reference/dispatch/dispatchqueue/2300059-init) parameter.

Of course, [docs are absolute useless](https://developer.apple.com/reference/dispatch/dispatchqueue.autoreleasefrequency), but I'm guessing the default value is `DispatchQueue.AutoreleaseFrequency.inherit`, which would match `DISPATCH_QUEUE_CONCURRENT`, and `.workItem` matches the new `DISPATCH_QUEUE_CONCURRENT_WITH_AUTORELEASE_POOL`.

My instinct tells me it'd be a good idea to pass `.workItem` instead, but I'm opening this issue for people who know better than I do to weigh in.

**Comment by mdiep** [comment]
> I'm opening this issue for people who know better than I do to weigh in.

Who's that? 🤔

**Comment by andersio** [comment]
https://github.com/apple/swift-corelibs-libdispatch/blob/master/dispatch/queue.h#L537

**Comment by mdiep** [comment]
Could this help with the ReactiveCocoa MapKit tests that occasionally leak/fail?

**Comment by andersio** [comment]
Possibly?

**Comment by liscio** [comment]
Here's the actual Swift source which specifies the default value as `.inherit`, FWIW:

https://github.com/apple/swift/blob/5accebf556f40ea104a7440ff0353f9e4f7f1ac2/stdlib/public/SDK/Dispatch/Queue.swift#L146

Setting `.workItem` as the default would certainly be a big help for folks like me with large, mixed codebases, however I don't know whether it's worth applying this in blanket form without first understanding the consequences.

I'd vote for exposing the parameter (as we did with `target` recently) and perhaps defaulting to `.inherit` (as the default queues currently do). Then, we can adjust & audit the internal spots where queues are created. That, or default to `.workItem` and see if it blows anything up first.

But I think Apple chose to leave it as `.inherit` for a reason. Perhaps it leads to performance or other issues? 🤷‍♂️

**Comment by NachoSoto** [comment]
I agree, let's at least expose it. I would vote for `.workItem` as the default though, but I'm possibly missing downsides as well.

**Comment by mdiep** [comment]
Exposing it sounds like a good first step. Then a few brave souls can try it out and report back before we make the switch. 😉

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
