### ISSUE TITLE
Buffering Action

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#291]
It seems a buffering `Action` might be a useful addition. As compared to a regular `Action`, it

1. does not automatically disable during execution;
2. buffers inputs received when the `Action` is executing; and
3. has an optional queue coalescer.

Possible use cases:

1. Queues of alert/modal prompts.
1. Asynchronous worker requiring mutual exclusion in general, e.g. creating/restoring an `NSWindow` w.r.t. a given object, without the use of infinite `retry` to workaround disabled actions.

A possible implementation would be:

1. Adding a new wrapper `Buffered<Value>` with a constraining protocol `ActionBuffering`.
2. Specialization in `Action` when `Value: ActionBuffering`
3. An `apply` overload which takes `Value.Value` and returns a `SignalProducer` that emits `Error` instead of `ActionError<Error>`.

e.g.

```swift
let documentOpener: Action<Buffered<Token>, (), NoError>

documentOpener = Action(bufferingUpTo: .max) { token -> SignalProducer<(), NoError> in
    return retrieveDocument(for: token).flatMap(.concat, transform: openWindow(for:))
}

// No ambiguity here, since `Buffered<Value>` != `Value`.
let worker: SignalProducer<(), NoError> = documentOpener.apply(restoredToken)
worker.start()
```

**Comment by mdiep** [comment]
Another possible implementation would be to add a configuration type.

```
extension Action {
  // These names are all terrible
  enum SomeName {
    case disabled // send disabled if already executing
    case joined // send completed when the current execution ends
    case buffered // execute after the current execution ends
  }
}
```

But I'm not sure we need this. Without strong demand for such behavior, I'd be very hesitant to add it.

**Comment by sharplet** [comment]
This seems similar to how `FlattenStrategy` is used. It also reminds me of `RACCommand`'s concurrent execution mode. Thoughts on modelling this after `FlattenStrategy` and adding a new case called `reject` (or maybe`disable`, etc.) for the current behaviour?

**Comment by sharplet** [comment]
FWIW this is something I've reached for in the past too (specifically the buffering/concat behaviour).

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
