### ISSUE TITLE
Binary attached to 1.1.0 release is actually 1.0

### ISSUE THREAD

**Issue by NachoSoto** [ReactiveCocoa/ReactiveSwift#293]
This cost me 30 minutes of my morning 😞 
This combined with https://github.com/Carthage/Carthage/issues/1836 only reproducing some times.

**Comment by andersio** [comment]
Removed for now.

**Comment by mdiep** [comment]
I just rebuilt 1.1.0 and attached a binary release.

Are you sure that it was 1.0? The version in Info.plist wasn't updated, so it still says 1.0. And the new 1.1 binary is the same size as the previous 1.1 binary, which is different than the size of the 1.0 binary. 😕

**Comment by NachoSoto** [comment]
Huh maybe I was just seeing https://github.com/Carthage/Carthage/issues/1836? But in pretty sure I wasn't. The dependency didn't get updated until I added `--no-use-binaries`.
