### ISSUE TITLE
Dealing with Error's

### ISSUE THREAD

**Issue by DarkDirectX** [ReactiveCocoa/ReactiveSwift#295]
If I have multiple sources of Errors, like I need create network request, perform this, deserialize JSON response and map to object, how I can deal with errors? Like create network can fail with one error, network with NetworkError and etc.. 
Create big error enum for all errors or what I need to do?

**Comment by andersio** [comment]
`Result.AnyError` would help in this case. It is an existential wrapper that can store any values that conform to `Error`.

**Comment by DarkDirectX** [comment]
Thank you!)
