### ISSUE TITLE
Add a flatten strategy to limit concurrency

### ISSUE THREAD

**Issue by mdiep** [ReactiveCocoa/ReactiveSwift#297]
`concat` limits concurrency to 1 signal. `merge` allows unlimited concurrency. It'd be nice to have something in-between.

ReactiveObjC has this as [`flatten:`](https://github.com/ReactiveCocoa/ReactiveObjC/blob/a417e72712fa4eeea977daa8fdc46417db794aaf/ReactiveObjC/RACSignal%2BOperations.h#L211-L224).

This is useful for things like https://github.com/Carthage/Carthage/pull/1841.

**Comment by NachoSoto** [comment]
Or change `.merge` to `.merge(maxConcurrency: UInt)` with `static let merge: FlattenStrategy = .Merge(UInt.max)`.

**Comment by mdiep** [comment]
And `static let concat = .merge(1)`?

**Comment by NachoSoto** [comment]
As long as it's not less performance, merging (no pun intended) the implementations would be amazing.

**Comment by andersio** [comment]
I'd call it `bound`. 🙂

**Comment by andersio** [comment]
Implemented in #298.
