### ISSUE TITLE
Replacing `CocoaAction` with a generic cross platform solution.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#307]
One idea without introducing a new type is overloading the `<~` operator (or a new one):
```swift
extension Reactive where Base: UIButton {
    let pressed: (signal: Signal<(), NoError>, enabled: BindingTarget<Bool>)
}

action <~ button.reactive.pressed
```

But the problem is kinda obvious: it works if and only if the `Action` does not need to take any input from the control. In other words, a straightforward way for composition is needed.

The proposed solution is a wrapper of a `Signal` and an availability binding target, which provides a `map` operator.
```swift
extension Reactive where Base: UIButton {
    let pressed: Actionable<Base>
}

// Action<Void, ?, ?> <~ ActionTrigger<UIButton>
action <~ button.reactive.pressed

// Action<ButtonState, ?, ?> <~ ActionTrigger<ButtonState>
action <~ button.reactive.pressed.map { ButtonState($0.state) }
```

Comparing to `CocoaAction`, the call site is more legible IMO.
```swift
button.reactive.pressed = CocoaAction(action) { ButtonState($0.state) }
```

**Comment by mdiep** [comment]
I don't really follow. I'd need to see more. 😕

**Comment by andersio** [comment]
Simply speaking, we may drop the need of `CocoaAction` and make things to read more natural (when a transform from the control to the action input is involved).

**Comment by mdiep** [comment]
I'm open to the idea of it. But it depends on what the specifics look like. ☺️

**Comment by andersio** [comment]
I have been thinking about this (with two-way bindings) lately, and apparently this would be better coupled with ReactiveCocoa.
