### ISSUE TITLE
Race condition on `enabledIf` property of Action

### ISSUE THREAD

**Issue by almassapargali** [ReactiveCocoa/ReactiveSwift#309]
With code like this: 
```swift
let notResponding = MutableProperty(true)
let acceptAction = respondAction(respondable, true, enabledIf: notResponding)
let declineAction = respondAction(respondable, false, enabledIf: notResponding)
notResponding <~ acceptAction.isExecuting.producer, declineAction.isExecuting.producer)
    .map { !($0 || $1) }
```

I get `Signal.sendLock` as soon as any of actions stars. I think it's locking when user defined `isEnabled` and action's own `isEnabled` changes at the same time, since following code works:

```swift
let notRespondingAccept = MutableProperty(true)
let notRespondingDecline = MutableProperty(true)
let acceptAction = respondAction(respondable, true, enabledIf: notRespondingAccept)
let declineAction = respondAction(respondable, false, enabledIf: notRespondingDecline)
notRespondingAccept <~ declineAction.isExecuting.producer.map { !$0 }
notRespondingDecline <~ acceptAction.isExecuting.producer.map { !$0 }
```

I'm on `github "ReactiveCocoa/ReactiveSwift" "1.1.0"`

**Comment by andersio** [comment]
There is one single internal property overseeing the state. So if you indirectly pipe `isExecuting` into the `Action` as the user-controled availability, it deadlocks.

Could you state what you want to achieve here, so that we may perhaps figure out an alternative?

**Comment by almassapargali** [comment]
So those two actions eventually get bound to two buttons `accept | decline`. And if user presses accept, I want decline be disabled while accepting in progress.

**Comment by almassapargali** [comment]
Personally I think ReactiveSwift should provide a way to allow only one of multiple actions at a time, and they way I coded it looks totally ok from developers perspective (imho). Maybe we can allow that code, but somehow avoid deadlocking?

**Comment by andersio** [comment]
One alternative I can think of is having both of them covered by the same `Action`, and differentiate the course of action by the input (e.g. an enum) instead.

**Comment by almassapargali** [comment]
Wow, great idea, how I missed that. Thank you very much, it really eliminates need for other action and property. I think I should close this one since it really led me to more complex implementation, and now after thinking the proper way to solve

> provide a way to allow only one of multiple actions at a time

would be one Action with enum as state or input.
