### ISSUE TITLE
Have an error "Extension type 'Disposable?' is ambiguous without more context" when i use "<~" as well as in old version

### ISSUE THREAD

**Issue by Copperfiled** [ReactiveCocoa/ReactiveSwift#315]
```
let a = MutableProperty(0)

let signal = theView.closeButton.reactive.controlEvents(.touchUpInside).signal

a <~ signal
```

**Comment by Copperfiled** [comment]
` let a = MutableProperty(0)

let signal = theView.closeButton.reactive.controlEvents(.touchUpInside).signal
       

 a <~ signal
        `

**Comment by andersio** [comment]
`controlEvents(_:)` is a `Signal` of `UIButton`. You need to transform it to a `Signal` of `Int` before you can bind it to a `MutableProperty<Int>`.
