### ISSUE TITLE
[RFC] Documentation improvements

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#329]
#### Changes
1. Group methods by the extension constraints. Say `skipNil()` is now under the section `Error == NoError`.

    https://andersio.github.io/ras-1.1.1/Classes/Signal.html
    https://andersio.github.io/ras-1.1.1/Structs/SignalProducer.html

1. Remove `SignalProtocol`, `SignalProducerProtocol`, `EventProtocol` and `OptionalProtocol` from the documentation, since these are implementation details.
   
   This requires affected constraints to be expressed in a parametric form. The current implementation uses [the form in the Swift Generic Manifesto](https://github.com/apple/swift/blob/master/docs/GenericsManifesto.md#parameterized-extensions). For example, `Value: OptionalProtocol` would be expressed as `<U> Value == U?` instead.

1. Reactive extensions of `NotificationCenter` and `URLSession` would now show up as individual top-level declarations.

    https://andersio.github.io/ras-1.1.1/Reactive%20Extensions/NotificationCenter.html

/cc @ReactiveCocoa/reactiveswift

**Comment by mdiep** [comment]
I'm not totally sure what you're suggesting. 😕 

Probably because I'm mostly unfamiliar with the generated docs.

**Comment by andersio** [comment]
@mdiep TL;DR
[I have customized Jazzy to generate better docs for RAS and RAC.](https://github.com/RACCommunity/jazzy/pull/1)

1. Methods are now grouped by the extension constraints. Say `skipNil` is under `Value: OptionalProtocol`.

   Now: http://reactivecocoa.io/reactiveswift/docs/latest/Classes/Signal.html
   New: https://andersio.github.io/ras-1.1.1/Classes/Signal.html

   But since `OptionalProtocol` is more like an implementation detail until we have parametric extensions, the constraint is substituted by its parametric form `<U> Value == U?`.

2. Reactive extensions now get their own separate pages on a per-type basis.

    Now: http://reactivecocoa.io/reactiveswift/docs/latest/Structs/Reactive.html
    New: https://andersio.github.io/ras-1.1.1/Reactive%20Extensions/NotificationCenter.html

**Comment by mdiep** [comment]
I like it. 👍

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
