### ISSUE TITLE
`skip(while:)` doesn't skip empty string

### ISSUE THREAD

**Issue by JyggalagIRL** [ReactiveCocoa/ReactiveSwift#336]
I'm try to fix a bug by figuring out if there is some strong with `skip(while:)` operator, so I write follow tests: 
```
        describe("strings skip nil and empty") {
            it("skip nil and empty", closure: {
                let (signal, observer) = Signal<String?, NoError>.pipe()

                var string: String? = nil
                var exec: Int = 0
                signal
                    .skipNil()
                    .skip(while: { $0.isEmpty })
                    .observeValues {
                        print($0)
                        string = $0
                        exec += 1
                    }

                observer.send(value: "5")
                expect(string).to(equal("5"))
                expect(exec).to(equal(1))

                observer.send(value: nil)
                expect(string).to(equal("5"))
                expect(exec).to(equal(1))

                observer.send(value: "")
                expect(string).to(equal("5"))
                expect(exec).to(equal(1))

                observer.send(value: "3")
                expect(exec).to(equal(2))
                expect(string).to(equal("3"))
            })
        }
```
tests failed when I send an empty string:
<img width="1298" alt="2017-04-20 4 27 46" src="https://cloud.githubusercontent.com/assets/18493506/25221435/b33fb372-25e7-11e7-9b55-919289068af7.png">

but when I replace `skip(while:)` with `filter(_predicate:)`:
```
signal
    .skipNil()
    .filter { !$0.isEmpty }
    .observeValues {
        print($0)
        string = $0
        exec += 1
    }
```
the tests passed.

Am I understanding `skip(while:)` wrong?

**Comment by andersio** [comment]
[skip(while:)](http://reactivecocoa.io/reactiveswift/docs/latest/Structs/SignalProducer.html#/s:FV13ReactiveSwift14SignalProducer4skipFT5whileFxSb_GS0_xq__)

> Do not forward any values from self until predicate returns false, at which point the returned signal behaves exactly like signal.

**Comment by JyggalagIRL** [comment]
Thanks @andersio !
I'm neither familiar with RAC nor good at English. In documents it says `Do not forward any values from self until predicate returns false`, which I understand `skip(while: { string in string == nil })` behaves the same as `skipNil()`. Have I a got some mistakes in my understanding of `skip(while:)`, could you explain more about it?

**Comment by andersio** [comment]
It means, given `self.skip(while: shouldContinue)`, that no value from `self` would be forwarded until `shouldContinue` returns false. Then from that point, all the values would be forwarded, regardless of the results of the `shouldContinue`.

It is a one-time toggling.

**Comment by JyggalagIRL** [comment]
`It is a one-time toggling.`, got it!
Thanks again @andersio , you helped me a lot!
