### ISSUE TITLE
How to avoid deadlock?

### ISSUE THREAD

**Issue by JyggalagIRL** [ReactiveCocoa/ReactiveSwift#341]
Hey, a newbie of RAC get stuck again. There is a requirement need I clean the password in the text filed every time it failed on validation(meanwhile an error produced). I consider the clean password code should be put in error handling operation, but it deadlock when I changing the property(password)'s value in the internal signal.

The following test demonstrate how deadlock occurs:
```
class Deadlock: QuickSpec {
    override func spec() {
	it("should not deadlock") {
            let (signal, observer) = Signal<String, NSError>.pipe()

            var password: String? = nil

            _ = signal
                .filter { $0.characters.count >= 6 }
                .flatMapError { error -> SignalProducer<String, NoError> in
                    observer.send(value: "")
                    return SignalProducer.empty
                }
                .observeValues { password = $0 }

            observer.send(value: "123456")
            expect(password).to(equal("123456"))

            observer.send(error: NSError(domain: "", code: 0, userInfo: nil))
            expect(password).to(equal("123456"))
        }
    }
}
```
How can I refactor my code to avoid deadlock?

**Comment by andersio** [comment]
`Signal` does not support sending values recursively. So doing:

```swift
.flatMapError { error -> SignalProducer<Int, NoError> in
       observer.send(value: 0)
```

is bound to deadlock. Try to use `ValidatingProperty` which is specifically built for this purpose. If you need a quick start, check the `ReactiveSwift-UIExamples.playground`.

**Comment by JyggalagIRL** [comment]
Thanks for your help!

**Comment by andersio** [comment]
P.S. I think `ValidatorOutput.coerced` would fit this case. But one caveat is that `ValidatingProperty` considers `coerced` a valid value. So you might need to interpret `property.results` differently, other than using the convenience instance properties.

**Comment by JyggalagIRL** [comment]
OK, I'll try it out.
BTW, RAC's documents seems to be too "abstractive" for me to understand. I'm currently adopting RAC's pattern hardly by viewing code in some open source projects (e.g. [kickstarter/ios-oss](https://github.com/kickstarter/ios-oss)). Where do you suggest that I can get some best practices (in using RAC's types and operators) from?

**Comment by andersio** [comment]
The UI Example playground would be one.
