### ISSUE TITLE
Include in Apple's new Swift Source compatibility suite

### ISSUE THREAD

**Issue by NachoSoto** [ReactiveCocoa/ReactiveSwift#347]
See https://github.com/apple/swift-source-compat-suite/ 😎

**Comment by NachoSoto** [comment]
Actually looks like https://github.com/kickstarter/Kickstarter-ReactiveExtensions is already there, which depends on `ReactiveSwift`, so I guess we're getting compiled transitively?

**Comment by mdiep** [comment]
> so I guess we're getting compiled transitively?

I was wondering that myself

**Comment by mdiep** [comment]
ReactiveSwift.xcodeproj is in their project, so we must be.

**Comment by mbrandonw** [comment]
Ha, looks like it! Only thing is it would be just testing the reactiveswift sha we're pinned to so it might still be nice to have them target your master?

**Comment by NachoSoto** [comment]
Oh good point, totally.

**Comment by andersio** [comment]
ReactiveCocoa is not included though.

**Comment by andersio** [comment]
Opened PR: https://github.com/apple/swift-source-compat-suite/pull/12

**Comment by NachoSoto** [comment]
Awesome! I imagine having tests run will be important too, specially with optimizations.

**Comment by andersio** [comment]
The original list does not include any tests though, only builds.

**Comment by andersio** [comment]
Merged.
