### ISSUE TITLE
Binding MutableProperty and Signal need to manually swap once time.

### ISSUE THREAD

**Issue by asDButcher** [ReactiveCocoa/ReactiveSwift#352]
I uses the MutableProperty to provided the reformed data for UI, but the value is not assigned at the first time I bind it to core data value, how can I force all signal send value to observers?
Currently I'm doing by myself with swap method but It's looks so terrible because I wrote same code at same place.

```
self.age <~ self.birthdayDate
            .map({ (date) -> String in
                let (weeksOld, yearsOld) = self.weeksAndYearsOld(from: date)
                let finalRet = yearsOld > 0 ? "\(yearsOld) years old" : "\(weeksOld) weeks old"
                return "\(finalRet)"
            })
        self.age.swap({
            let (weeksOld, yearsOld) = self.weeksAndYearsOld(from: self.birthdayDate.value)
            let finalRet = yearsOld > 0 ? "\(yearsOld) years old" : "\(weeksOld) weeks old"
        }())
```

**Comment by andersio** [comment]
Using `Property` and `MutableProperty`would always send the current value. What is `self.birthdayDate`?

**Comment by andersio** [comment]
Since you mentioned Core Data, using `DynamicProperty` or `producer(forKeyPath:)` does not fire a fault.

https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3309

**Comment by asDButcher** [comment]
@andersio My problem is I need to manually assign the initial value by swap method, the observer(MutableProperty) only get updates after the value of self.birthdayDate changed, but I need it update once when init.

**Comment by andersio** [comment]
It should not be necessary. When you bind a property to another, the current value is propagated immediately.

**Comment by asDButcher** [comment]
@andersio Alright, then what I need to do is use DynamicProperty instead of MutableProperty?

**Comment by andersio** [comment]
Not really. What I mean is if `self.birthdayDate` is a `MutableProperty` or `Property`, `<~` should write the current value immediately as the binding is established. Since you use `map`, it should not change the guarantee at all.

```
let date = MutableProperty(Date())
let age = MutableProperty("")

age <~ date.map { date in "\(date)" }
print(age.value) // PRINT: The current date.
```

**Comment by asDButcher** [comment]
@andersio The self.birthdayDate is a MutableProperty and it will accepting value from NSManagedObject, now I know the problem, thanks.

**Comment by andersio** [comment]
If what you do is like `birthdayDate <~ managedObject.reactive.producer(forKeyPath: ...)`, wrap it with `managedObject.{will|did}AccessValue(forKey: nil)`.
