### ISSUE TITLE
Signal.flatMap(.concat) doesn't send values

### ISSUE THREAD

**Issue by larryonoff** [ReactiveCocoa/ReactiveSwift#356]
Hello Community,

Could you please help me with the issue below.

I have the following code:
```swift
let collection: MutableProperty<MyCollection?> = MutableProperty(nil)
let batchUpdatesInput: Signal<BatchUpdates, NoError> = collection
            .signal
            .skipNil()
            .flatMap(.concat) { $0.updates }

view.reloadUpdates <~ batchUpdatesInput
```

`MyCollection` has property `var updates: Signal<BatchUpdates , NoError>` which I never complete.

My issue occurs when `collection: MutableProperty<MyCollection?>` is changed, `batchUpdatesInput` stops sending updates to `reloadUpdates` binding. What really confuses me that when I add logEvents into `.flatMap(.concat) { $0.updates. logEvents() }` it logs new values, but `batchUpdatesInput` doesn't trigger any values.

I've tried to replace ` .flatMap(.concat) { $0.updates }` with `.flatMap(.concat) { $0.updates.materialize().skip { $0.isTerminating }.dematerialize() }`. But it didn't help.

So I've rewritten this code in the following way and it works.
```swift
        let batchUpdatesInput = SignalProducer<BatchUpdates, NoError> { [weak collection = state.collection] observer, disposable in
            guard let collection = collection else {
                observer.sendCompleted()
                return
            }

            let serialDisposable = SerialDisposable()
            disposable += collection.signal.observeValues { collection in
                guard let collection = collection else { return }

                serialDisposable.inner = collection.updates.observe(observer)
            }
        }
```

So my questions is what I'm doing wrong?

PS. I want using standard operators instead of manually writing signals. :)

Thanks for help!

**Comment by andersio** [comment]
What you want is probably `flatMap(.latest)` instead. The concat strategy does not start forwarding from the next, until the current one has terminated.

**Comment by larryonoff** [comment]
@andersio thank you very much. It works!
