### ISSUE TITLE
Compatibility CI tests

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#357]
Akin to the Swift source compatibility suite, perhaps we may add CI tasks which build a set of depending projects, e.g. Carthage, to test for API compatibility.

That said if we do this, we would need to figure out how API breaking changes in `master` can be managed in the future.

/cc @ReactiveCocoa/reactiveswift

**Comment by NachoSoto** [comment]
That sounds like a good idea! Sorry I missed this when you created it.
