### ISSUE TITLE
What happened to rac_textSignal?

### ISSUE THREAD

**Issue by emojiface** [ReactiveCocoa/ReactiveSwift#37]
Hi, I'm porting a project using ReactiveCocoa to ReactiveSwift. I can't find rac_textSignal, what should be used instead?

**Comment by ikesyo** [comment]
This is a duplicate of https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3197. See that issue for the details.

**Comment by emojiface** [comment]
Hey, @ikesyo, thanks for the response. I'm trying to add ReactiveObjC and ReactiveObjCBridge using CocoaPods, is this supported, or would I need to clone ReactiveSwift, add the two submodules, and drag into Xcode manually?
