### ISSUE TITLE
[Idea] NoValue enum

### ISSUE THREAD

**Issue by ikesyo** [ReactiveCocoa/ReactiveSwift#389]
This is similar to `NoError` enum. With this one can write something like this:

```swift
let noValueProducer1 = SignalProducer<NoValue, NoError>.empty
let noValueProducer2 = SignalProducer<NoValue, FooError>(error: FooError())
let noValueProducer3 = SignalProducer<NoValue, FooError>(value: ...) // Cannot be called

typealias Completable<E> = SignalProducer<NoValue, E>
```

We may replace `Signal/Producer<(), Error>` with `Signal/Producer<NoValue, Error>`.

**Comment by andersio** [comment]
We can use `Never`.

**Comment by ikesyo** [comment]
Ah that makes sense.

**Comment by andersio** [comment]
`Result.NoError` can be replaced by `Never` too.

**Comment by andersio** [comment]
Hmm, `NoValue` reads better though. Moreover, `Never` for now is just intended for return types, and it is not yet a real bottom type.

**Comment by mdiep** [comment]
I think `Never` reads fine. If that provides the same guarantee, I'd prefer it.

**Comment by andersio** [comment]
`Never` is just `NoError` with compiler sugar.

**Comment by mdiep** [comment]
I believe this is resolved by #392. I don't see any other operators that could use `Never`.

**Comment by andersio** [comment]
`flatMap` could use `Never`. 🙂

**Comment by andersio** [comment]
Ah, and a new overload of `startWith*` and `observe*` that returns a `Result<(), Error>`.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
