### ISSUE TITLE
Action compositions: wrapping one Action in another, fallback-if-disabled, etc

### ISSUE THREAD

**Issue by tikitu** [ReactiveCocoa/ReactiveSwift#395]
Hi folks,

I'm finding several cases where I'd like to "open up" the internals of `Action` so I can combine them in various ways. One case was in #366 ("given two actions, apply whichever of them is enabled"), and now I have another: wrap an existing Action, disabling it in more cases than the original.

I can solve that with a similar workaround to #366, but it's a bit hacky. To do it "properly" I think I would need to add to `Actions.swift`, to get access to the private internals there. Would y'all be interested in a pull request, once I've worked something out? Or is that a direction you'd rather not take the API in?

(For a first step I'm thinking just to add an initializer `Action.init(wrapping base: Action, enabledIf enabled: Property<Bool>`), with semantics that it's enabled if `enabled` *and* `base.isEnabled` are truthy. If I'm lucky, doing that might give me insight in more fundamental building-blocks that could be exposed for something like #366, but I'm not holding my breath.)

**Comment by andersio** [comment]
I am not quite sure about initialiser vs operator at this point, but I do see the value of `Action` composition.

**Comment by tikitu** [comment]
Good enough for me! I'll try to put together a PR this week: even if it's not accepted, I hope it will be useful to work through a concrete use case.

**Comment by andersio** [comment]
I am personally interested in transforming and trivialising input, output and error, and I think these could help impose encapsulation. Let's see how we can push this forward.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
