### ISSUE TITLE
Is this a bug?  if it is not, what is the principle? 

### ISSUE THREAD

**Issue by cstars135** [ReactiveCocoa/ReactiveSwift#399]
why `skipRepeatsProperty`  first received 3, why not  property?

```
 let property = MutableProperty(0)
    let skipRepeatsProperty = property.skipRepeats()
    property.producer.startWithValues {
        print("Property received \($0)")
    }
    skipRepeatsProperty.producer.startWithValues {
        print("Skip-Repeats property received \($0)")
    }
    print("Setting new value for property: 3")
    property.value = 3
```

**Comment by andersio** [comment]
```
Property received 0
Skip-Repeats property received 0
Setting new value for property: 3
Skip-Repeats property received 3
Property received 3
```

Nothing seems wrong.

**Comment by cstars135** [comment]
Property received 3
Skip-Repeats property received 3
why not this order ?  I don't get it.

**Comment by andersio** [comment]
The `Signal` contract does not guarantee observers to be ordered with regard to each other. But the implementation calls out the observers in observation order.

In this case, `skipRepeatsProperty` is the first observer to `property`, before the first observer with `print`.
