### ISSUE TITLE
Can't build playground

### ISSUE THREAD

**Issue by Tibbs** [ReactiveCocoa/ReactiveSwift#403]
I follow the instructions:
1. Clone the ReactiveSwift repository.
2. git submodule update --init --recursive (tied Carthage as well)
3. Open ReactiveSwift.xcworkspace
4. Build Result-Mac scheme
5. Build ReactiveSwift-macOS scheme = FAILS

Building ReactiveSwift-macOS scheme fails with lots of errors, for example:

~/ReactiveSwift/Sources/Event.swift:126:1: error: constrained extension must be declared on the unspecialized generic type 'Event' with constraints specified by a 'where' clause
extension Signal.Event where Value: Equatable, Error: Equatable {
^         ~~~~~~~~~~~~
~/ReactiveSwift/Sources/Event.swift:147:1: error: constrained extension must be declared on the unspecialized generic type 'Event' with constraints specified by a 'where' clause
extension Signal.Event: CustomStringConvertible {
^         ~~~~~~~~~~~~
~/ReactiveSwift/Sources/Event.swift:176:1: error: constrained extension must be declared on the unspecialized generic type 'Event' with constraints specified by a 'where' clause
extension Signal.Event: EventProtocol {
^         ~~~~~~~~~~~~
~/ReactiveSwift/Sources/Deprecations+Removals.swift:123:34: error: same-type requirement makes generic parameter 'Wrapped' non-generic
extension Optional where Wrapped == Disposable {
                                 ^
~/ReactiveSwift/Sources/Deprecations+Removals.swift:176:30: error: same-type requirement makes generic parameter 'Value' non-generic
extension Signal where Value == Bool {
                             ^
~/ReactiveSwift/Sources/Deprecations+Removals.swift:63:30: error: same-type requirement makes generic parameter 'Error' non-generic
extension Signal where Error == NoError {
                                                                    
and so on all together 151 errors

I tried everything, deleting and cloning again, git submodule update/carthage checkout, delete derived data, etc nothing works.
Any idea what could be wrong?

**Comment by ikesyo** [comment]
Looks like you use Xcode 8.2 but current `master` requires Xcode 8.3 (Swift 3.1).

**Comment by andersio** [comment]
Note that the latest Swift 3 compatible release is 1.1.3.

**Comment by Tibbs** [comment]
@andersio and @ikesyo Thank you for your help. It is much better now but still fails with the following error:
Playground execution failed: error: /var/folders/y4/3xk57cbn7f3927lr9jjrt9hm0000gr/T/./lldb/1768/playground11.swift:4:8: error: no such module 'ValidatingProperty_PageSources'
import ValidatingProperty_PageSources

**Comment by andersio** [comment]
Looks like the playground could be out of date if you are working with `master`.

**Comment by plivesey** [comment]
Is there a workaround for this? I'm using Xcode 8.3.2. I tried on master and got:

```
error: no such module 'Result'
```

I then tried reverting back to `1.1.3`: `$ git checkout 1.1.3`. I'm still getting the same error.

**Comment by MattNewberry** [comment]
@plivesey I had this same problem as well... I eventually discovered you must open the playground from within `ReactiveSwift.xcworkspace`, rather than opening `ReactiveSwift.playground` directly.

**Comment by n8gray** [comment]
FYI, I had the `error: no such module 'ValidatingProperty_PageSources'` problem with the ReactiveSwift-UIExamples playground and fixed it by adding `import Foundation` at the top of `FormView.swift`.

**Comment by abhikp** [comment]
+1 tol @n8gray

**Comment by devSC** [comment]
I clone the lastest project then have the `error: /var/folders/p3/3ypxc_bd6wb761_tllb4qldc0000gn/T/playground27-60762a..swift:4:8: error: no such module 'ValidatingProperty_PageSources'
import ValidatingProperty_PageSources
` problem when i use Xcode 9.0.1 how can i fix this?

**Comment by samwize** [comment]
I had build errors in `UIKitExtensions.swift`. Looks like Signal has deprecated it's old init. I change the code to as follows:

```
extension Reactive where Base: UISwitch {
	public var isOnValues: Signal<Bool, NoError> {
		return Signal { observer, lifetime in
			let target = CocoaTarget { observer.send(value: ($0 as! UISwitch).isOn) }
			base.addTarget(target, action: #selector(target.execute), for: .valueChanged)
//            return AnyDisposable { _ = target }
		}
	}
}
```

Change similarly for `UITextField` extension too. Build ReactiveSwift again (make sure without errors) and playground should run.
