### ISSUE TITLE
Concerning `Observer.send`...

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#425]
Reading again the Swift API guidelines

> When the first argument forms part of a prepositional phrase, give it an argument label. The argument label should normally begin at the preposition, e.g. x.removeBoxes(havingLength: 12).

> Otherwise, if the first argument forms part of a grammatical phrase, omit its label, appending any preceding words to the base name, e.g. x.addSubview(y)

makes we wonder if `send(value:)` and `send(error:)` fit in these rules. Seems like according to the later rule, they should be `sendValue(_:)` and `sendError(_:)` instead.

**Comment by mdiep** [comment]
> Seems like according to the later rule

It does seem like that's the case. I don't especially like that though. 😕

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
