### ISSUE TITLE
Use cases / Examples

### ISSUE THREAD

**Issue by gkaimakas** [ReactiveCocoa/ReactiveSwift#45]
Would it be possible to provide some sort of guidance on when/how to use various aspects of the framework?

Examples on `Action`, `Lifetime` etc would be helpful a lot for someone who is at the process of learning the framework

**Comment by liscio** [comment]
@gkaimakas This is something I hope to address in the UI programming guidelines PR that's open against ReactiveCocoa right now, however there's definitely a case to be made for making a non-UI version that can be referenced as a part of that guide.

Frankly it's difficult to find the "right answers" for a few specific cases (`Property` vs `SignalProducer` use, etc.) but the ones you specify are pretty easy to explain.
