### ISSUE TITLE
Something wrong with linking ReactiveSwift / ReactiveCocoa

### ISSUE THREAD

**Issue by applehawk** [ReactiveCocoa/ReactiveSwift#450]
dyld: Symbol not found: __TMp13ReactiveSwift13BindingTarget
  Referenced from: /Users/vlad/Library/Developer/CoreSimulator/Devices/E3D38621-5AAB-4FD1-BC0C-638E9309591B/data/Containers/Bundle/Application/802247FE-9438-4438-98A1-03844F9C1B01/MyApp.app/PlugIns/Messenger.appex/../../Frameworks/ReactiveCocoa.framework/ReactiveCocoa
  Expected in: /Users/vlad/Library/Developer/CoreSimulator/Devices/E3D38621-5AAB-4FD1-BC0C-638E9309591B/data/Containers/Bundle/Application/802247FE-9438-4438-98A1-03844F9C1B01/MyApp.app/PlugIns/Messenger.appex/../../Frameworks/ReactiveSwift.framework/ReactiveSwift
 in /Users/vlad/Library/Developer/CoreSimulator/Devices/E3D38621-5AAB-4FD1-BC0C-638E9309591B/data/Containers/Bundle/Application/802247FE-9438-4438-98A1-03844F9C1B01/MyApp.app/PlugIns/Messenger.appex/../../Frameworks/ReactiveCocoa.framework/ReactiveCocoa

 My Cartfile file looks like:
> github "mylifeasdog/Facebook-SDK-Swift" "master"
github "johnsundell/unbox" ~> 2.3.0
github "johnsundell/wrap" ~> 2.1.1
github "antitypical/Result" ~> 3.0.0
github "Swinject/Swinject" "2.0.0"
github "Alamofire/Alamofire" ~> 4.0.1
github "stripe/stripe-ios" ~> 10.0
github "soffes/SAMKeychain" == 1.5.2
github "onevcat/Kingfisher" == 3.1.4
github "Skyscanner/SkyFloatingLabelTextField"
github "ReactiveCocoa/ReactiveCocoa" "e744315"
github "ReactiveCocoa/ReactiveSwift" == 1.0.1

My Cartfile.private
>github "Quick/Quick"
github "Quick/Nimble"
github "facebook/ios-snapshot-test-case"

My Cartfile.resolved
> github "Alamofire/Alamofire" "4.4.0"
github "BoltsFramework/Bolts-ObjC" "1.8.4"
github "Quick/Nimble" "v7.0.1"
github "Quick/Quick" "v1.1.0"
github "ReactiveCocoa/ReactiveCocoa" "e7443157ad1257e93c660586c41e1da710547676"
github "ReactiveCocoa/ReactiveSwift" "1.0.1"
github "Skyscanner/SkyFloatingLabelTextField" "v3.1.0"
github "Swinject/Swinject" "2.0.0"
github "adomanico/facebook-ios-sdk" "830cc8eff7c3d4615bd4d6a8cad238bf9f17bdb5"
github "antitypical/Result" "3.2.3"
github "facebook/ios-snapshot-test-case" "2.1.4"
github "johnsundell/unbox" "2.5.0"
github "johnsundell/wrap" "2.1.1"
github "mylifeasdog/Facebook-SDK-Swift" "fed643b634bfe204b65840728c0eb4868ceab21a"
github "onevcat/Kingfisher" "3.1.4"
github "soffes/SAMKeychain" "v1.5.2"
github "stripe/stripe-ios" "v10.1.0"

**Comment by ikesyo** [comment]
Could you please update ReactiveCocoa to the latest 5.0.4 release first? The version you use is too old (early development version of RAC 5).

**Comment by applehawk** [comment]
In this case, Cartfile:
github "mylifeasdog/Facebook-SDK-Swift" "master"
github "johnsundell/unbox"
github "johnsundell/wrap"
github "antitypical/Result"
github "Swinject/Swinject" "2.0.0"
github "Alamofire/Alamofire" ~> 4.0.1
github "stripe/stripe-ios" ~> 10.0
github "soffes/SAMKeychain" == 1.5.2
github "onevcat/Kingfisher" == 3.1.4
github "Skyscanner/SkyFloatingLabelTextField"
github "ReactiveCocoa/ReactiveCocoa" == 5.0.4
github "ReactiveCocoa/ReactiveSwift" == 1.1

>my Cartfile.resolved:
github "Alamofire/Alamofire" "4.4.0"
github "BoltsFramework/Bolts-ObjC" "1.8.4"
github "Quick/Nimble" "v7.0.1"
github "Quick/Quick" "v1.1.0"
github "ReactiveCocoa/ReactiveCocoa" "5.0.4"
github "ReactiveCocoa/ReactiveSwift" "1.1.0"
github "Skyscanner/SkyFloatingLabelTextField" "v3.1.0"
github "Swinject/Swinject" "2.0.0"
github "adomanico/facebook-ios-sdk" "830cc8eff7c3d4615bd4d6a8cad238bf9f17bdb5"
github "antitypical/Result" "3.2.3"
github "facebook/ios-snapshot-test-case" "2.1.4"
github "johnsundell/unbox" "2.5.0"
github "johnsundell/wrap" "2.1.1"
github "mylifeasdog/Facebook-SDK-Swift" "fed643b634bfe204b65840728c0eb4868ceab21a"
github "onevcat/Kingfisher" "3.1.4"
github "soffes/SAMKeychain" "v1.5.2"
github "stripe/stripe-ios" "v10.1.0"

And this is works fine! Thanks... Something wrong with Carthage I think
