### ISSUE TITLE
selective throttling

### ISSUE THREAD

**Issue by gerfarfel** [ReactiveCocoa/ReactiveSwift#457]
Question: is there a recommended way to meet the following conditions?

1. Start with a signal (generated by a gesture recognizer) that sends _began_, _changed_, and _ended_ values.
2. Throttle the _changed_ values based on time (e.g., no more than 10 _changed_ values per second).
3. Pass through all _began_ and _ended_ values, and (ideally) pass through the last _changed_ before an _ended_.
4. Maintain the sequential order of the values (including between the _ended_ value of one gesture and the _began_ of the next one) – i.e., _changed_ values shouldn't show up before _began_ or after _ended_ values.

All the approaches I've come up with either run the risk of missing _began_ or _ended_ values, or of delivering the values out of order. Thanks...

**Comment by mdiep** [comment]
There's not as easy way to do that.

I think you'd need to:

1. Create two copies of the start signal
2. Filter only began/ended values on one
3. Filter only changed values on the other
4. Throttle the values
5. Combine the two signals
6. Scan the tuple of events to see what's changed and only forward the valid events

**Comment by gerfarfel** [comment]
Thanks for our thoughts on this. The problem with throttling just the changed values is that they can be delayed and end up showing up out of sequence with the begin/end values. I'm sure I can find a reasonable way to work around this issue, but I wanted to makes sure I wasn't missing an obviously better way to do it.
