### ISSUE TITLE
Auto-interrupt `Signal`.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#461]
In 2.0 alpha 3, we have automatic silent disposal of `Signal` when its input (generator) observer deinitializes _and_ the `Signal` is not retained, regardless of still having observers or not.

Despite having this new semantic over 1.x, there is still a hole left for leaks. Specifically, a signal would be kept alive if it is retained, even if the input observer has deinitialized. (recall: the new semantic works if both — not either — conditions are satisfied.)

Whether or not active observers should be notified of the disposal is also debatable.

So I'd propose to have `Signal`s automatically & unconditionally interrupted by the deinitialization of the input observer (unless a terminal event has been sent, of course). With this, `Signal` would now be cleaned up by either ends completely cease the interests to send/observe.

@ReactiveCocoa/reactiveswift

**Comment by mdiep** [comment]
That makes sense to me. 👍

**Comment by andersio** [comment]
@mdiep Sadly, it would be still kind of a leak (the signal and the core), but at least the observers and disposables are released.

**Comment by mdiep** [comment]
I wouldn't call it a leak if something is holding on to the signal.

**Comment by andersio** [comment]
Implemented.
