### ISSUE TITLE
[Question] Combine two lines code to one

### ISSUE THREAD

**Issue by KimSmitth** [ReactiveCocoa/ReactiveSwift#464]
I have current code to decide the current user has logged in and  where we should go when the button tapped.
````swift
let useLoggedIn = Signal
            .merge(self.viewDidLoadProperty.signal)
            .map { AppEnvironment.current.currentUser != nil }
        
self.goToCheckInPage = Signal.combineLatest(useLoggedIn, self.checkInButtonTappedProperty.signal).filter{$0.0 == true}.ignoreValues()
        
self.goToLogInPage = Signal.combineLatest(useLoggedIn, self.checkInButtonTappedProperty.signal).filter{$0.0 == false}.ignoreValues()
````

Is there a more elegant way to do this?

**Comment by mdiep** [comment]
What are `goToCheckInPage` and `goToLogInPage`?

**Comment by KimSmitth** [comment]
Just two signal with noValue: 

var goToCheckInPage: Signal<(), NoError>
 
var goToLogInPage: Signal<(), NoError>

**Comment by mdiep** [comment]
You could move the combine latest into the other signal—even keeping the current structure.

```swift
let checkIn = self
    .viewDidLoadProperty.signal // No need to use merge for this
    .map { AppEnvironment.current.currentUser != nil }
    .combineLatest(with: self.checkInButtonTappedProperty.signal)

self.goToCheckInPage = checkIn.filter { $0.0 }.ignoreValues()
self.goToLogInPage = checkIn.filter { !$0.0 }.ignoreValues()
```

But I think there are probably larger improvements that you could make to your architecture. You might want to take a look at using `Action` with your button (via ReactiveCocoa) if you haven't already done so.

**Comment by KimSmitth** [comment]
Got it! Thanks!
