### ISSUE TITLE
The fate of `startWith*` and `observe*`?

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#465]
Since we last spoke about this in https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3013, it has been a while. Are we still committing to dropping the convenience shorthands with disambiguated trailing closures, for a mega `start` overload akin to the `on` operator?

Do note that this:
1. cannot be migrated.
2. Except for `start(value:)`, all other variants are no longer eligible of trailing closure.

It is also worth noting that our friends in RxSwift choose to drop the shorthands.

On the other hand, should we consider adding convenience shorthands for `on`? Say `onValues`, `onFailure`, etc.

```swift
extension SignalProducer {
    public func start(
        events: ((Event<Value, Error>) -> Void)? = nil,
        values: ((Value) -> Void)? = nil,
        results: ((Result<Value, Error>) -> Void)? = nil,
        completed: (() -> Void)? = nil,
        failed: ((Error) -> Void)? = nil,
        interrupted: (() -> Void)? = nil,
        _: () = ()
    ) -> Disposable
}

extension SignalProducer where Error == NoError {
    public func start(values: @escaping (Value) -> Void) -> Disposable
}

extension Signal {
    public func observe(
        events: ((Event<Value, Error>) -> Void)? = nil,
        values: ((Value) -> Void)? = nil,
        results: ((Result<Value, Error>) -> Void)? = nil,
        completed: (() -> Void)? = nil,
        failed: ((Error) -> Void)? = nil,
        interrupted: (() -> Void)? = nil,
        _: () = ()
    ) -> Disposable
}

extension Signal where Error == NoError {
    public func observe(values: @escaping (Value) -> Void) -> Disposable
}
```

@mdiep @NachoSoto @RuiAAPeres @liscio
/cc @ReactiveCocoa/reactiveswift

**Comment by sharplet** [comment]
IMO it feels like unnecessary churn unless there's a clear benefit. Being able to unambiguously use trailing closure syntax is pretty important to me, and could be to many of our users.

**Comment by liscio** [comment]
@sharplet is it equally common for you to use alternatives to `startWithValues(_:)`?

I feel like the trailing closure version of `start` defaulting to take values seems sensible, and using labels for the rest of the options.

However, I'm not sure how you'd mix the `results:` parameter with the `values:` parameter in a single `start()` function as above, @andersio. For instance, does this make much sense?

```
someProducer.start(values: { value in
  // do something with value
},
results: { result in
  // do something with value on .success
})

// do both closures execute above on every value?
```

Also, if we were able to pick a single "trailing closure winner" for both the `NoError` and "not `NoError`" cases (if the latter is even *possible* to specify), then it would make sense that `start(_:)` takes the `result:` closure when Error is not NoError, and the `value:` closure otherwise.

**Comment by sharplet** [comment]
I don't know, I probably couldn't pin down "equally common". However, I _think_ I tend to use plain old `start()` most, and handle side effects elsewhere, for example with `Property`, `Action`, or bindings.

**Comment by andersio** [comment]
@liscio `results` maps `value` to `Result.success` and `failed` to `Result.failure`.

**Comment by gkaimakas** [comment]
Would it make any sense to drop all the start / observe closures and only have a single `start()` / `observe()` function? 

Then the work of observing the events, values, errors etc could be done with the `on` operator.

When I started using ReactiveCocoa I thought that that was the use of the `on` operator.

```Swift
producer
    .on(value: { })
    .on(error: { })
    .on(result: { })
    .start()
```

seemed more appropriate at the time.

**Comment by mdiep** [comment]
I think which overload is most coming depends on how you reactive your code is. At work, we've been mostly been using `startWithResult`.

My opinion is that the unambiguous trailing closure syntax is useful for this method.

**Comment by kaybutter** [comment]
It should also be noted that in most cases the shorthands work better with Xcode's autocompletion. The `.on(...)` method autocompletes all the parameters even if I only need one or two and I then have to go and delete all the parameters I don't want. It's not a huge problem but then again I don't use `.on` as much as I use the start methods. 🤔
