### ISSUE TITLE
`race` inner signal interruption

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#467]
What is the expected behaviour of inner signal interruption? `latest` and `concurrent` do not propagate inner signal interruption to the product, but `race` is inconsistent with them.

```swift
let (outer, outerObserver) = Signal<Signal<(), NoError>, NoError>.pipe()

let (a, aObserver) = Signal<(), NoError>.pipe()
let (b, bObserver) = Signal<(), NoError>.pipe()

outerObserver.send(value: a)
outerObserver.send(value: b)

var isInterrupted = false
outer.observeInterrupted { isInterrupted = true }

aObserver.sendInterrupted()
expect(isInterrupted) == true // ???

bObserver.send(value: ())
bObserver.sendInterrupted()
expect(isInterrupted) == true // ???
```

**Comment by mdiep** [comment]
The documentation says:

```
	/// - warning: `interrupted` events on inner producers will be treated like
	///            `completed` events on inner producers.
```

I think we should go by that. Both `expect`s should be `false`.

**Comment by andersio** [comment]
It doesn't appear to be the case.

https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Flatten.swift#L692

**Comment by andersio** [comment]
Apparently the documented semantic is _first to send an event wins_. So the implementation is right.
