### ISSUE TITLE
Deprecated protocol warnings

### ISSUE THREAD

**Issue by crvo84** [ReactiveCocoa/ReactiveSwift#491]
Getting some deprecated protocol warnings for ReactiveSwift.
ReactiveCocoa 5.0.0
CocoaPods 1.0.1
Xcode 8.3.3

<img width="332" alt="screen shot 2017-07-19 at 10 43 01 am" src="https://user-images.githubusercontent.com/6656010/28376359-8ece3648-6c6f-11e7-94cc-aca658370f19.png">

**Comment by andersio** [comment]
These are unfortunately deliberate. Swift doesn't provide means for library developers to do only public deprecations.

However, if you use the latest version of ReactiveCocoa 5.x and ReactiveSwift 1.x, the warnings should have been suppressed.
