### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by NachoSoto** [ReactiveCocoa/ReactiveSwift#504]
This is going to be very interesting for `ReactiveSwift` :)

https://gist.github.com/lattner/31ed37682ef1576b16bca1432ea9f782
https://github.com/apple/swift/pull/11501

**Comment by mdiep** [comment]
If accepted, we'll want to add bridging initializers that take async blocks and convert them into `SignalProducer`s. Do you see other implications?

On the whole, async/await doesn't seem very interesting to me.

**Comment by NachoSoto** [comment]
That's the only idea I have so far too, but I'm sure we'll come up with more as it evolves.

I'm sure it won't replace the need for `ReactiveSwift`, but I think I combination of both might simplify code. Error handling on the other hand is still going to suck most likely (due to untyped errors).

**Comment by andersio** [comment]
blocking imperative operators can be turned into async methods?

**Comment by jjoelson** [comment]
@mdiep: In my experience using Reactive Extensions in C#, conversion in both directions can be helpful. In C# you can actually directly await an observable, which by default yields the last value prior to completion, though [you can modify that behavior](https://rehansaeed.com/reactive-extensions-part5-awaiting-observables/):

    // Returns the first element of an observable sequence.
    string result = await observable.FirstAsync();
     
    // Returns the first element of an observable sequence, or a default value if no such element exists.
    string result = await observable.FirstOrDefaultAsync();
     
    // Returns the last element of an observable sequence. 
    // This is the default action of awaiting an observable.
    string result = await observable.LastAsync();
     
    // Returns the last element of an observable sequence, 
    // or a default value if no such element exists.
    string result = await observable.LastOrDefaultAsync();
     
    // Returns the only element of an observable sequence, and throws an exception if there is not exactly 
    // one element in the observable sequence.
    string result = await observable.SingleAsync();
     
    // Returns the only element of an observable sequence, or a default value if the observable sequence 
    // is empty; this method reports an exception if there is more than one element in the observable sequence.
    string result = await observable.SingleOrDefaultAsync();

This lets you easily use observables in imperative-looking code, which is sometimes quite nice.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
