### ISSUE TITLE
Integer overflow with `timer` function on specifying seconds interval greater than 21474.836471

### ISSUE THREAD

**Issue by stephanecopin** [ReactiveCocoa/ReactiveSwift#506]
Hey guys,

I think this is just a documentation mistake at https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/FoundationExtensions.swift#L155-L157 and https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/SignalProducer.swift#L2478-L2480.
The documentation specifies 200,000 as the maximum interval, however 10% of 200,000 is 20,000 (rather than 2,000), so the `Int` conversion will overflow with any [micro/milli]seconds values greater than 21474.836471.
Not sure if just the documentation should be updated, or a more in depth change should be made. I feel like an interval like 21,600 seconds (6h00) is more likely to be set by someone than 200,000, for applications that are allowed to run in the background for example.

Thoughts?

**Comment by andersio** [comment]
@liscio

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
