### ISSUE TITLE
Ignoring errors?

### ISSUE THREAD

**Issue by aehlke** [ReactiveCocoa/ReactiveSwift#521]
ReactiveCocoa used to have an `ignoreError()` method that was dropped in the move to ReactiveSwift. Are we intended to take a different approach as a best practice, and if so, what would that be? Or has it just not been made a priority to port this method?

**Comment by andersio** [comment]
I am not sure if `ignoreError` ever exists. You probably got it from Rex.

`ignoreError` is essentially a convenience of:

```
producer.flatMapError { _ in SignalProducer<U, NoError>.empty }
```

**Comment by NachoSoto** [comment]
We don't want to encourage the use of such operator, which is why it's not included. We recommend always explicitly handling errors as necessary.

**Comment by aehlke** [comment]
Ahh yes I must have, got it - thanks!
