### ISSUE TITLE
EXC_BAD_ACCESS on iOS 9 and iOS 8 in startWithResult

### ISSUE THREAD

**Issue by AlexanderKaraberov** [ReactiveCocoa/ReactiveSwift#527]
Sorry beforehand if this is a Swift related crash and it has nothing to do with the ReactiveSwift. In this case feel free to close this issue with a comment.

When I call `startWithResult` on `SignalProducer` and do pattern match on success/failure I receive `EXC_BAD_ACCESS (code=1, address=0x0)` right after I try to `print()` value of the `Result`. Crash is inside of `const ClassMetadata *swift::_swift_getClass(const void *object)` function from Swift's `runtime/SwiftObject.mm` which is called from `init<T>(stringInterpolationSegment expr: T)` of the `StringInterpolation` i.e. basically at this line: `print("Response: \(value)")`.
If I do `po` in LLDB on `Result` instance which I got in callback closure I observe this error:
> (lldb) po result
expression produced error: error: /var/folders/57/swpvtsx11n9_zqwfgy4d9lrc0000gn/T/expr9-ad1128..swift:1:72: error: 'Result' is not a member type of 'Result'
Swift._DebuggerSupport.stringForPrintObject(Swift.UnsafePointer<Result.Result<Swift.Array<AppTargetName.Session>, Result.AnyError>>(bitPattern: 0x4dce860)!.pointee)

On iOS 10 and 11.0 everything works fine.
If instead of printing a `value` directly in the closure of `signalWithResult` I'll access it later e.g. in the next run loop cycle then everything is fine and the `value` contains correct data. 

Any suggestion would be extremely helpful.

**Comment by andersio** [comment]
Does it consistently happen with all the use of `startWithResult`? :|

**Comment by AlexanderKaraberov** [comment]
@andersio I would rather say that it consistently happen with all the use of `Result` inside `ReactiveSwift` and it happens that `startWithResult` is the one using it. Just to double-check I tested that `Result` library is loaded and I can use it in the same function which calls `startWithResult`. My wild guess it has something to do with dynamic lib (as I said this issue is happened only in iOS 8 and 9).  If I do jump to definition i see this:
`public func startWithResult(_ action: @escaping (Result.Result<Value, Error>) -> Swift.Void) -> Disposable`
which looks odd, because all other definitions use Result and not Result.Result, e.g. `SignalProducer where Error == Result.NoError`, but as I said it might be a long shot.

**Comment by AlexanderKaraberov** [comment]
@andersio  Did more testing. Yes this consistently happen during all usages of `startWithResult` when I try to `print()` value or `po` it in the LLDB. Even when I create a SignalProducer in one controller and then pass it to another one and then from there call `startWithResult` - behaviour is the same: `EXC_BAD_ACCESS` in `_swift_getClass` and error in LLDB.

**Comment by andersio** [comment]
It does look more like a Swift issue than a RAS specific one. I recommend creating a reduced test case and submit it to bugs.swift.org instead. 😕

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
