### ISSUE TITLE
The reason and use cases behind special treatment for .interrupted event.

### ISSUE THREAD

**Issue by kAzec** [ReactiveCocoa/ReactiveSwift#53]
Hi, recently I'm digging around the sources and found these comments in [Signal.swift](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Signal.swift#L63)

```
// Normally we disallow recursive events, but `interrupted` is
// kind of a special snowflake, since it can inadvertently be
// sent by downstream consumers.
//
// So we'll flag Interrupted events specially, and if it
// happened to occur while we're sending something else,  we'll
// wait to deliver it.
```

I understood that `.interrupted` is special and doing this prevents undesired deadlocks under certain conditions. 

However, these certain conditions, aka when `it can inadvertently be sent by downstream consumers`, still remains vague to me.

Can you please provide some actual scenes or explain these comments a little further to help clarifying?

Sorry if the question is naive or the answer to it is obvious. 

Thanks.

**Comment by mdiep** [comment]
I don't fully understand this part of the code yet, but `.interrupted` can propagate up the signal chain when something is disposed or interrupted.

**Comment by andersio** [comment]
You are allowed to interrupt a `SignalProducer` in the observer of the produced signal. If we do not permit this specific case of signal recursion, we would have a deadlock in `sendLock`.

**Comment by kAzec** [comment]
Oh, thanks, now I see.

**Comment by andersio** [comment]
A code snippet to illustrate this if you are interested.
```
let (signal, observer) = Signal<Int, NoError>.pipe()
var disposable: Disposable?

disposable = SignalProducer<Int, NoError>(signal: signal)
	.startWithValues { _ in
		print(disposable)
		disposable?.dispose()
	}

observer.send(value: 1)
```

The `value` event is pushed to the produced signal, causing a disposal of the producer within the `sendLock`. Since by default everything is synchronous, if we do not treat `interrupt` specially, we would stuck at attempting to lock `sendLock` again.

**Comment by kAzec** [comment]
Understood. And also under the following condition which may be more common:

```swift
signalProducer
    .startWithSignal { signal, interrupter in
        signal.observe { event in
            // ...
            interrupter.dispose()
        }
    }
```
