### ISSUE TITLE
crash on iphone5s with iOS 8.1，don't appear on iOS 8.3

### ISSUE THREAD

**Issue by FlutterDown** [ReactiveCocoa/ReactiveSwift#537]
RAC:6.0.2 or 6.1.0-alpha.2
RAS: 2.0.1 or RAS 2.1.0-alpha.2

will crash with log:
fatal error: Unexpected pthread mutex error code: 11: file /Users/xcar/development/***/Pods/ReactiveSwift/Sources/Atomic.swift, line 190

**Comment by andersio** [comment]
Please provide the stack trace or a reproducible test case if possible.

**Comment by andersio** [comment]
Please try #538 out if possible. Thanks. :)

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
