### ISSUE TITLE
Intermittent test deadlocks on Linux builds

### ISSUE THREAD

**Issue by soxjke** [ReactiveCocoa/ReactiveSwift#544]
Some `PropertySpec` cases are deadlocking on Linux builds. As an example one can look into https://travis-ci.org/ReactiveCocoa/ReactiveSwift/jobs/291414085 where test run is deadlocking for
```
Test Case 'XCTestCase.MutableProperty, should not deadlock' started at 2017-10-23 08:37:59.778
```

Probably, some test revision needed, because from a first glance test case seems to be OK, but still deadlocking somehow.

**Comment by andersio** [comment]
I assume it could be related to priority inversion and the restricted concurrency. :s
