### ISSUE TITLE
no such module 'ValidatingProperty_PageSources'

### ISSUE THREAD

**Issue by devSC** [ReactiveCocoa/ReactiveSwift#546]
I clone the lastest project then have the error: /var/folders/p3/3ypxc_bd6wb761_tllb4qldc0000gn/T/playground27-60762a..swift:4:8: error: no such module 'ValidatingProperty_PageSources' import ValidatingProperty_PageSources problem when i use Xcode 9.0.1 how can i fix this?

**Comment by andersio** [comment]
It is possible that the playground sources have not been updated to Swift 4.0. I will check ASAP.

**Comment by czgarrett** [comment]
I'm getting the same thing.  Any update on this?

**Comment by samwize** [comment]
Fixed the problem. Check https://github.com/ReactiveCocoa/ReactiveSwift/issues/403#issuecomment-356863058

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
