### ISSUE TITLE
Deprecated combineLatest not converted to Swift 3

### ISSUE THREAD

**Issue by vadim-fueled** [ReactiveCocoa/ReactiveSwift#55]
```
@available(*, unavailable, renamed:"SignalProducer.combineLatest")
public func combineLatest<S: Sequence, Value, Error>(producers: S) -> SignalProducer<[Value], Error> where S.Iterator.Element == SignalProducer<Value, Error> { fatalError() }
```
Should have `(_ producers: S)` instead of `(producers: S)`, otherwise instead of `'combineLatest' has been renamed to 'SignalProducer.combineLatest'` Xcode shows confusing `Argument labels '(_:)' do not match any available overloads`.

Probably there are other cases like this.

**Comment by andersio** [comment]
Oh, yeah. Thank you for catching this.
