### ISSUE TITLE
SignalProducer documentation needs updating for use of Lifetime in startHandler initialiser

### ISSUE THREAD

**Issue by github-user32** [ReactiveCocoa/ReactiveSwift#556]
I've been trying to understand the new use of Lifetime in SignalProducer initialisation and ran into some confusion.

It looks like the SignalProducer documentation is a little out of date, in regards to its:
   `public init(_ startHandler: @escaping (Signal<Value, Error>.Observer, Lifetime) -> Void)`
initialiser.

In the description for the third` init()` function at [http://reactivecocoa.io/reactiveswift/docs/latest/Structs/SignalProducer.html](http://reactivecocoa.io/reactiveswift/docs/latest/Structs/SignalProducer.html):
 - the '`startHandler`' parameter refers to a disposable, but probably should be referring to a `Lifetime`. Might be helpful here to also mention (if my understanding is correct?) that any disposables added to the lifetime will be disposed of when the signal ends.

- The Note section refers to a `CompositeDisposable`, which I think (?) may not be relevant any more. Should the note somehow mention the interaction between the disposable returned by start and the lifetime?

My understanding of Lifetime is still a little unclear, so I don't feel I can provide precise wordings to correct things - sorry!

In the API contract [https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Documentation/APIContracts.md#the-signalproducer-contract](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Documentation/APIContracts.md#the-signalproducer-contract)
in the '**Disposing of a produced signal will interrupt it**' section, the second paragraph ends with "_, and will also dispose of everything added to the CompositeDisposable in SignalProducer.init._"
I think this may no longer be correct, and possibly should be referring to a `Lifetime` rather than a `CompositeDisposable`?

**Comment by andersio** [comment]
Resolved by #557.

**Comment by github-user32** [comment]
No worries. Thanks for the quick fix!
