### ISSUE TITLE
Modernise mapError(_:), filterMap(_:), etc. signatures into map(error:), filter(map:) and so on

### ISSUE THREAD

**Issue by ianbytchek** [ReactiveCocoa/ReactiveSwift#561]
It keeps method names clean and gives them context though argument name and type. Aesthetically they are more pleasant to read and use. Overloading is used everywhere in most Apple frameworks and not foreign to ReactiveSwift either – many methods already follow this approach, like `take(first:)`, `take(last:)`, `collect(count:)`, `observe(on:)`, etc. So, the change would standardise syntax a little further as well. 

`mapError(_:)` → `map(error:)`
`filterMap(_:)` → `filter(map:)`
`observeResult(_:)` → `observe(result:)`
`observeCompleted(_:)` → `observe(completed:)`
`observeFailed(_:)` → `observe(failed:)`
`observeValues(_:)` → `observe(values:)`

**Comment by mdiep** [comment]
We believe these names match the Swift API Design Guidelines. Specifically [this part](https://swift.org/documentation/api-design-guidelines/#omit-first-argument-if-partial-phrase):

> Otherwise, if the first argument forms part of a grammatical phrase, omit its label, appending any preceding words to the base name, e.g. `x.addSubview(y)`

Note the Swift standard library might be gaining a `filterMap` method in Swift 5.

**Comment by NachoSoto** [comment]
Also, we purposely avoid overloads with different labels to avoid ambiguities when calling these with trailing closure syntax.

**Comment by andersio** [comment]
Overloading does not work well with multi-line closures due to type inference limitations. So these overloads of the same base name are going to clash very often unless one specified the label.

ICYMI there is a new method in Swift 4 called `Dictionary.mapValues`. We are more or less aligned with stdlib on how to deal with name conflicts.

**Comment by ianbytchek** [comment]
Love how with every post here I end up learning a bunch of new information! 😄 Agree with everything, thanks for detailed feedback!
