### ISSUE TITLE
Question about flatMap on completed or then with closure

### ISSUE THREAD

**Issue by benji-bou** [ReactiveCocoa/ReactiveSwift#568]
Hi, 
When I need to call in sequence some SignalProducer (when one finished start second). The `then` operator fit perfectly for this. But in some cases I need to perform task before creating the next SignalProducer. 
The most understandable is something like a flatMapCompleted. 
I ended up creating an extension like this 
```
extension SignalProducer {
    func then<U>(_ replacement: @escaping () -> (SignalProducer<U, Error>)) -> SignalProducer<U, Error> {
        return SignalProducer<U, Error> { observer, lifetime in
            self.startWithSignal { signal, signalDisposable in
                lifetime += signalDisposable
                
                signal.observe { event in
                    switch event {
                    case let .failed(error):
                        observer.send(error: error)
                    case .completed:
                        lifetime += replacement().start(observer)
                    case .interrupted:
                        observer.sendInterrupted()
                    case .value:
                        break
                    }
                }
            }
        }
    }
    
}

```
Which is, in fact, a copy/paste of `_then` internal method using a closure instead of SignalProducer as parameter. 

Do you see a better/cleaner way to do this? Or maybe I miss an operator who already do the job?

Best

**Comment by brow** [comment]
Instead of…
```swift
myProducer.flatMapCompleted { replacementProducer(getInput()) }
```
How about…
```swift
myProducer
  .then(SignalProducer(getInput))
  .flatMap(.latest, replacementProducer)
```
This uses `SignalProducer.init(_ action:)`, which "creates a producer for a `Signal` that immediately sends one value, then completes". The value is constructed lazily using `action`, which has type `() -> Value`.

**Comment by benji-bou** [comment]
Hey brow, 

Oh yes, I did not think about building an extra layer of SignalProducer
It works perfectly. 

Thank you 

Best
