### ISSUE TITLE
Memory leak between BinderTarget and MutableProperty

### ISSUE THREAD

**Issue by artursDerkintis** [ReactiveCocoa/ReactiveSwift#571]
So I found an issue in this line of code.
`self.someView.reactive.isHidden <~ self.viewModel.someViewIsHidden.producer.map { $0 }`
The retain cycle is never released and the owner `self` is retained in memory. 
Am I not doing it right or its an issue?

**Comment by brow** [comment]
That line alone does not imply a retain cycle. Where in your code is this line?

Why is the explicit `self.` required? Is this inside an escaping closure?

**Comment by artursDerkintis** [comment]
It's basically in a function without any closures or anything. Just plainly attacing UI to data.

**Comment by brow** [comment]
Why do you suspect that this line is responsible for the retain cycle?

**Comment by artursDerkintis** [comment]
I was debuting the code and it in Visual Memory Graph it showed that the owner ViewController is not being released and new ones are created (its like details screen for Table View). 
So I pinpointed the issue to that line. 
Also once I replaced that particular line with this:
`observer += self.viewModel.someViewIsHidden.producer.startWithValues { [weak self] isHidden in
     self?.someView.isHidden = isHidden 
}`
it wasn't leaking anymore and it worked as expected.

Let me know if something is unclear.

**Comment by brow** [comment]
Ah, thanks for the details. I cannot think of a case where replacing
```swift
observation += self.viewModel.someViewIsHidden.producer.startWithValues { [weak self] isHidden in
self?.someView.isHidden = isHidden
} 
```
with 
```swift
self.someView.reactive.isHidden <~ self.viewModel.someViewIsHidden.producer.map { $0 }
```
should cause `self` to be retained. Perhaps someone else has ideas?

**Comment by artursDerkintis** [comment]
Well I was thinking that there's no way it could leak either, but I was wrong.

**Comment by andersio** [comment]
Which version in particular?

**Comment by andersio** [comment]
I tried to reproduce it on RAC 7.0.1 but the Memory Graph Debugger isn't reporting any leak, and my memory hoarding test VC goes away as normal. So it could be better if there is more information.

What is the type of `someView`? Did you use any other framework that could possibly do ObjC swizzling? It appears that the only difference here would be the binding using `reactive.lifetime`.

**Comment by artursDerkintis** [comment]
It turned out to be a problem in other place in code. Closing this
