### ISSUE TITLE
Consolidate `Scheduler` protocols.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#572]
Lately I have been thinking if we could consolidate the two scheduler protocols into one. The time-based scheduling methods are always meant to be async, so even if the backing worker is not able to schedule by a specific deadline, we could very well provide default implementations that fallbacks to GCD global queues for the timed enqueuing (not the execution).

**Comment by mdiep** [comment]
It doesn't make sense to me to add `schedule(after: Date, action: () -> Void)` to `ImmediateScheduler` or `UIScheduler`.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
