### ISSUE TITLE
How to ignore first signal after second begins?

### ISSUE THREAD

**Issue by ABeard89** [ReactiveCocoa/ReactiveSwift#578]
I've looked around, and I can't find a solution to my current problem. I'd really appreciate some help on this.

I have three signals,

- `P`: Process has started
- `S1`: Subprocess 1's state changes
- `S2`: Subprocess 2's state changes

I want to:

1. When `P` starts: listen to values of `S1`.
2. When `S2` starts: ignore `S1` and listen to values of `S2`.

I figure I probably have to map `P` to a stream of `SignalProducer`s and then `flatten` `S1` and `S2` to get the `latest` stream.

Is that strategy correct? If so, how do I go about that?

    // Have
    let p: Signal<(), NoError> = ...
    let s1: Signal<MyState, NoError> = ...
    let s2: Signal<MyState, NoError> = ...
    
    // Need
    let state: Signal<MyState, NoError> = p
        .map { _ in
            // Combine signals somehow
            // Flatten with latest to listen for the newer stream?
            // Return producer of flattened values?
        }
        .flatten(.latest) // Reset every time P is restarted.

**Comment by iv-mexx** [comment]
What you need is the `take(untilReplacement)` operator which will take the first signal until the first value on the second signal and then send the values of the second signal:

```

let state: Signal<MyState, NoError> = p.flatMap(.latest) { _ in
    return s1.take(untilReplacement: s2)
}
```

**Comment by ABeard89** [comment]
Oh wow! That’s much simpler than I thought it’d be. Didn’t know `take(untilReplacement:)` was a thing, but that makes perfect sense.

Thanks a lot for your help! This was driving me nuts.
