### ISSUE TITLE
Inconsistent disposal behavior between `QueueScheduler`'s `schedule(after:action:)` and `schedule(after:interval:action:)`

### ISSUE THREAD

**Issue by jjoelson** [ReactiveCocoa/ReactiveSwift#582]
As [this question on StackOverflow](https://stackoverflow.com/questions/47977290/queuescheduler-not-firing-when-interval-is-set) observes, the behavior of `schedule(after:action:)` is different from `schedule(after:interval:action:)` with respect to disposal. The former returns a `Disposable` that you *may* use to cancel the action before it occurs whereas the latter returns a `Disposable` that you *must* retain in order to avoid immediate cancellation. 

`schedule(after:interval:action:)`'s behavior feels strange, as there is nowhere else within `RAS` that I can think of where merely failing to *retain* a `Disposable` causes it to, in effect, be disposed. This looks to me as though `DispatchSourceTimer`'s behavior of cancelling upon `deinit` is leaking through. 

If this is a bug, ought `schedule(after:interval:action:)`  be implemented in terms of `schedule(after:action:)` (the way `TestScheduler` appears to do it)? And if not, might it make sense to remove the `@discardableResult` annotation to signal to users that they probably want to hold on to the returned `Disposable`? It doesn't seem to me as though cancelling the scheduled action immediately is behavior users would ever want.

(Apologies for not submitting a pull request per the contribution guidelines, but I am unsure of whether this is actually a bug or not. I am happy to submit a pull request if it is agreed that this is a bug!)

**Comment by andersio** [comment]
I agree that this is not the expected behavior, since disposables are generally not supposed to exercise side effect unless being explicitly disposed of. It could very well be an oversight in Swift 3 migration.

**Comment by jjoelson** [comment]
I noticed that `TestScheduler` implements it recursively in terms of `schedule(after:action:)`:
```
private func schedule(after date: Date, interval: DispatchTimeInterval, disposable: SerialDisposable, action: @escaping () -> Void) {
    precondition(interval.timeInterval >= 0)

    disposable.inner = schedule(after: date) { [unowned self] in
        action()
        self.schedule(after: date.addingTimeInterval(interval), interval: interval, disposable: disposable, action: action)
    }
}

public func schedule(after date: Date, interval: DispatchTimeInterval, leeway: DispatchTimeInterval = .seconds(0), action: @escaping () -> Void) -> Disposable? {
    let disposable = SerialDisposable()
    schedule(after: date, interval: interval, disposable: disposable, action: action)
    return disposable
}
```
Could this work for `QueueScheduler` as well? It would obviate the need to use and store timers at all.

**Comment by andersio** [comment]
Relying on GCD is preferred, because the ad hoc recursive version would accumulate the actual scheduling delay unless there is special workaround.

**Comment by jjoelson** [comment]
Good point. I will submit a pull request to keep a collection of active timers, sometime in the next few days.
