### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by EvgenyMatviyenko** [ReactiveCocoa/ReactiveSwift#589]
I am using ReactiveSwift for implementing view models in my app.
I need to create a Signal that depends on itself. Here is a solution I use to solve the problem:
```swift
let (_chatDeleted, _chatDeletedObserver) = Signal<Void, NoError>.pipe()

// `chatEntities` requires `chatDeleted` which is not created yet
let chatEntities = chatsProvider.fetchChats(reload: Signal.merge([chatAdded, _chatDeleted]))

let chatDeleted = deleteItemIndex
  .withLatest(from: chatEntities.producer) // `chatDeleted` requires `chatEntities` here
  .map { $1[$0] }
  .flatMap(.concat) { chatEntity in
    return chatsProvider.deleteChat(chatEntity: chatEntity)
  }
  .on(value: _chatDeletedObserver.send) // Ugly way to forward events to `chatEntities` here
```
I know that some FRP frameworks have a way to resolve this in a convenient way. For example, Sodium framework has [CellLoop](https://github.com/SodiumFRP/sodium/blob/master/java/src/main/java/nz/sodium/CellLoop.java) unit that allows declaring forward references and using them before adding any logic. 
Does ReactiveSwift deal with this problem anyhow? Is there any way to avoid "proxy" signals as in the example above?

**Comment by mdiep** [comment]
In general, I think you're best off structuring your code to avoid these issues entirely. ReactiveSwift doesn't have anything to make this easy, and I'm not convinced that it should.

But it's tough to look at a small snippet of code and give good advice about how to change things to improve the situation.

In this case, I'd wonder if you should need to pass `_chatDelete` to `chatsProvider`. If you're calling `chatsProvider.deleteChat`, can't it know that it needs to reload the chats? You might still use a pipe to accomplish this, but it wouldn't be circular.

**Comment by EvgenyMatviyenko** [comment]
Yes, it makes sense to move `chatDelete` to `chatsProvider` in this example. But there are some cases when it isn't possible to avoid this.
