### ISSUE TITLE
Playground execution failed:  

### ISSUE THREAD

**Issue by Wangming2014** [ReactiveCocoa/ReactiveSwift#592]
Playground execution failed:

error: /var/folders/8r/0lfvf_7s4jg48jzfpk1gsdyc0000gp/T/playground14-d5ad80..swift:4:8: error: no such module 'ValidatingProperty_PageSources'
import ValidatingProperty_PageSources
       ^

**Comment by Wangming2014** [comment]
Please help me!

**Comment by mdiep** [comment]
Closing in favor of #593.
