### ISSUE TITLE
Xcode 9.3 beta: Swift error with SignalProducer.on()

### ISSUE THREAD

**Issue by rae** [ReactiveCocoa/ReactiveSwift#595]
See the [logged Swift bug](https://bugs.swift.org/browse/SR-6796). A workaround is mentioned, but it's not clear to me how it would be applied to ReactiveSwift. I think it means adding parens around arguments to on().

I realize you could close this as being fixed in the next Xcode beta, but any help on this would be appreciated by people currently having to use Xcode 9.3 beta now.

**Comment by NachoSoto** [comment]
Thanks, see #590.
