### ISSUE TITLE
Propose to add frequently used new operators

### ISSUE THREAD

**Issue by ra1028** [ReactiveCocoa/ReactiveSwift#597]
I would like to propose some of the frequently used operators for Signal and SignalProducer.
If willing to agree with me on this, so I'll send Pull Request.

## `void()`
Map unused values to Void.
```swift
func void() -> Signal<Void, Error>
```

## `skipError()`
Create a NoError signal, drop errors.
```swift
func skipError() -> Signal<Value, NoError>
```

##  `merge(with:)`
Merges `self` and given signal into a single `Signal`.
Similar functions( `combineLatest(with:)` , `zip(with:)` ) are already exists, but `merge(with:)` is not exist.
```swift
func merge(with other: Signal<Value, Error>) -> Signal<Value, Error>
```

**Comment by NachoSoto** [comment]
- `void()`: I support this. I don’t like that name in particular, but I’m sure we can find a more precise one. In my codebase I have this as `var voidValues: Signal<Void, E> {}`, but I don’t love that name either.
- `skipError`: this has been suggested many times, but I’m strongly against it. It encourages bad practices by simply ignoring errors. Instead, each user should implement this as they see fit. For example, in my codebase I have `logAndIgnoreErrors()`, which is only exposed for `Error: ReportableError` (my own type), and it sends _non-fatal_ errors to Crashlytics. Ignoring them without any consequence is a bad practice IMO.
- `merge(with:)`: I have this same one in my codebase, so 👍

**Comment by mdiep** [comment]
> `void()`: I support this. I don’t like that name in particular, but I’m sure we can find a more precise one. In my codebase I have this as `var voidValues: Signal<Void, E> {}`, but I don’t love that name either.

Agreed. I think we just need the right name. We've previously referred to `Signal<(), E>` as a _trigger_, so that might be a clue towards a good name.

I've been wanting to add a `func map<NewValue>(value: NewValue) -> Signal<NewValue, Error>` to map to constant values. Maybe that'd be enough for this? `.map(value: ())`

> `skipError`: this has been suggested many times, but I’m strongly against it.

Agreed. 👎 

> `merge(with:)`: I have this same one in my codebase, so 👍

👍

**Comment by NachoSoto** [comment]
> I've been wanting to add a func map<NewValue>(value: NewValue) -> Signal<NewValue, Error> to map to constant values. Maybe that'd be enough for this? .map(value: ())

Oooh yeah, I like that a lot better, a more general and useful operator :) I'd overload `map` with it, or name it  `replaceValues(_ newValue: NewValue)`, not sure what I like better.

**Comment by brow** [comment]
Is `x.void()` equivalent to `x.map { _ in }`? What are the advantages of writing the former instead of the latter?

👎 `skipError`

👍 `merge(with:)`

**Comment by mdiep** [comment]
> I'd overload map with it, or name it replaceValues(_ newValue: NewValue), not sure what I prefer.

I like overloading because it aids in discoverability and makes the API surface smaller in some ways.

I could see adding a `skip(value:)` too.

**Comment by ra1028** [comment]
Thanks.

`map (value:)` or `map(to:)` is seems better than `void()` :+1:

> It encourages bad practices by simply ignoring errors. Instead, each user should implement this as 
Yeah, definitely.
It's convenient, but might be better not to implement.
 
`merge (with:)` seems to be :+1: for majority.

**Comment by ra1028** [comment]
> Is x.void() equivalent to x.map { _ in }? What are the advantages of writing the former instead of the latter?

I think it makes sense for ease of readability.
It's similar to relation between `filterMap(_ :)` and `skipNil()`
