### ISSUE TITLE
Ambiguous reference to 'observeValues'

### ISSUE THREAD

**Issue by danielaRiesgo** [ReactiveCocoa/ReactiveSwift#598]
To any signal with an error that is not NoError, every time I want to use `.observeValues` I get a compiler error saying:
    Ambiguous reference to member 'observeValues'
    Found this candidate ReactiveSwift.Signal<Value, NoError>
    Found this candidate ReactiveSwift.Signal<Never, NoError>

ReactiveSwift version: 3.1.0
ReactiveCocoa version: 7.1.0

It can be reproduce with the following code:
```
let signal = UIButton().reactive.controlEvents(.touchUpInside).mapError { _ in NSError(domain: "My domain", code: 3, userInfo: .none) }

signal.observeValues { _ in print("error") } 
```

**Comment by jjoelson** [comment]
In order to discourage users from ignoring errors, [`observeValues` is only defined for `NoError` Signals](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Signal.swift#L515). You might want to take a look at `observeResult` which has the same signature as `observeValues` except it's closure takes a `Result<Value, Error>` that you can switch over in order to handle errors.

**Comment by NachoSoto** [comment]
Yeah this is by design. In fact I think the problem is that Swift is providing a bogus diagnostic, [as usual](https://bugs.swift.org/browse/SR-5198).

**Comment by mdiep** [comment]
Could we provide an unavailable version that explains it while leaving the `NoError` version in tact?

**Comment by danielaRiesgo** [comment]
Yeah, I know about `observeResults` but the error I think is not good. I think in the previous versions you got a warning saying you should better use `observeResult`, but know it just tells you that there is ambiguity for signals that don't even match yours. It's strange.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
