### ISSUE TITLE
Addition of creation operators.

### ISSUE THREAD

**Issue by minuscorp** [ReactiveCocoa/ReactiveSwift#599]
I really love the simplicity of `ReactiveSwift` but sometimes I feel it lacks of some of the great conventions that `RxSwift` provides.

I was thinking of focusing in initialization methods of `Signal`. In `RxSwift` we have three options:

- `.create`

- `.just`, `.never`, `.error`, `.empty`

- `.using`

- `.deferred`

Both `.create`, `.never` and `.empty` constructors are already implemented by the library (if I'm right on this), and `.deferred` might be just implemented by the way  `SignalProducer`s work, didn't it?
So the main objective with this issue is to open a discussion about filling the gaps and implementing, if approved, the _missing_ constructors for the library.

Kind regards and keep up the great work! 🚀

**Comment by ikesyo** [comment]
I’m not sure about `.using`, but `Signal.just` and `Signal.error` would be nonsense since there is no observers at the time of creation / sending the events. Maybe what you want is `SignalProducer.init(value:)` and `SignalProducer.init(error:)`.

**Comment by minuscorp** [comment]
You're right, I missed that the `SignalProducer` already has this behavior! So.. maybe we're only missing the `.using` operator?

About the `.using` operator, is used rarely but it is extremely useful, as reaches a very concrete objective, explained deeply in [here](http://reactivex.io/documentation/operators/using.html), it creates an observable that:
> The Using operator is a way you can instruct an Observable to create a resource that exists only during the lifespan of the Observable and is disposed of when the Observable terminates.

**Comment by NachoSoto** [comment]
I'm slightly confused why Rx would have Observables that follow RAII, but you can also do this with the lazy `SignalProducer` constructor.

**Comment by minuscorp** [comment]
How do you attach the lifetime of a `SignalProducer` to the lifetime of another one, either `Signal` or `SignalProducer`?

**Comment by sharplet** [comment]
> How do you attach the lifetime of a `SignalProducer` to the lifetime of another one, either `Signal` or `SignalProducer`?

I'd use the `take(until:)` operator for this.

**Comment by minuscorp** [comment]
`take(until:)` completes the attached `Signal` or `SignalProducer` upon `.next` or `.completed` events are sent from the parent resource, so I think it not covers the behavior.

**Comment by Qata** [comment]
@minuscorp `take(until: signal.then(.empty)`

**Comment by minuscorp** [comment]
No need to add anything then! 😄
