### ISSUE TITLE
Rename `Event.failed` to `Event.error`

### ISSUE THREAD

**Issue by inamiy** [ReactiveCocoa/ReactiveSwift#60]
This is just a matter of taste, but `observer.sendFailed()` has been renamed to `observer.send(error:)`, so I think `Event.failed` should be renamed to `Event.error` as well (and also other methods like `on(failed:)`).

Or, renaming `observer.send(error:)` to `observer.send(failed:)` improves consistency too.
(I prefer `send(error:)` though)

**Comment by andersio** [comment]
The event was intentionally named `failed` as being one of the terminating event.

https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2505
https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2360
https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2349

**Comment by ikesyo** [comment]
And also #8.

**Comment by mdiep** [comment]
I think it makes sense as-is. _failed_ is the event; _error_ is the instance that initiates/describes it. An error causes the stream to fail.

**Comment by inamiy** [comment]
Thanks for references.
I still find the naming inconsistency in [Observer.swift#L78-L104](https://github.com/ReactiveCocoa/ReactiveSwift/blob/dfb2f9ae68c04c38c768e8a25fffa0d72f7fa5b5/Sources/Observer.swift#L78-L104) ("send" should be followed by event name), but it might be an exception for argument label case.

Anyway, this is too trivial issue to discuss, so I will close.
