### ISSUE TITLE
Convenience default implementations for mutable properties

### ISSUE THREAD

**Issue by sharplet** [ReactiveCocoa/ReactiveSwift#615]
While experimenting with #613, I found that this little extension made it a lot easier to work with custom mutable property types:

```swift
extension MutablePropertyProtocol where Self: ComposableMutablePropertyProtocol {
    var value: Value {
        get { return withValue { $0 } }
        set { modify { $0 = newValue } }
    }

    func withValue<Result>(_ action: (Value) throws -> Result) rethrows -> Result {
        return try modify { try action($0) }
    }
}
```

Making your own custom mutable property is probably not a common use case, but nevertheless this seems like a useful extension, and could potentially remove some duplication in the codebase.

Thoughts?

**Comment by andersio** [comment]
The original plan was that `ComposableMutablePropertyProtocol` would replace `MutablePropertyProtocol` eventually, but the work hasn't been done.

**Comment by mdiep** [comment]
Those seem like reasonable default implementations. 👍 

Why are you making custom mutable property types?

**Comment by sharplet** [comment]
> Why are you making custom mutable property types?

It cut down on some boilerplate while I've been experimenting with ideas for #613.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
