### ISSUE TITLE
Discussion: Swift 3 function names/prepositions + trailing closure syntax

### ISSUE THREAD

**Issue by mhuusko5** [ReactiveCocoa/ReactiveSwift#62]
Pre-Swift 3 a func like `skipWhile(_ condition: () -> Bool)` would be, well.. _that_. And thus usage would be `.skipWhile { ... }` – terse yet clear at call site.

Now it's `skip(while condition: () -> Bool)` per Swift 3 naming practices, rendering usage either `.skip(while: { .. })` (losing crispness of trailing closure) or `.skip { .. }` (losing info). The latter wouldn't even be usable if a `skip(until condition: () -> Bool)` func were introduced because of the ambiguity.

Is anyone else concerned?

**Comment by andersio** [comment]
How is `skip(until:)` different from `skip(while:)`?

**Comment by mhuusko5** [comment]
Good point!! That's not so good of an example for my compiler ambiguity concern then.

Nevertheless my concern still stands (and this is towards Swift 3 naming, not anything ReactiveSwift has done specifically/wrong) that is the `while` portion of the func `skip(while condition: () -> Bool)` is important (it is; it's what indicates you should be return `true` for skips, not `false` like a hypothetical `skip(until:)` func), then allowing for the use of `.skip { .. }` is counter to that API importance; it's unclear at the call site.

Returning to `skipWhile(_ condition: () -> Bool)` would be the clearest, but probably (not sure the conventions had these cases in mind) against Swift 3 naming conventions.

Changing to `skip(while condition: () -> Bool, _: _ = true)` on the other hand would only permit usage as `.skip(while: { .. })`. A personal preference, but I feel unlikely to garner support.

**Comment by mdiep** [comment]
I don't find `.skip { … }` to be worrisome. But we have left some of the `startX` methods with the old-style names for this reason.

I'd rather us stick with the language conventions by default. If it proves to be a problem, we can consider changing it for RAC 6.

**Comment by mdiep** [comment]
I'm going to close this, since there's no action to be taken. Feel free to open a new issue if you run into a case that seems confusing!
