### ISSUE TITLE
Necessity of `Property.signal`.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#620]
I do wonder if we might need a reflection regarding Properties offering both `SignalProducer` and `Signal`. It seems to cause more confusion than anything else beneficial (if any...). :confused:

`property.signal` only gives you any changes occurred from the time of subscription. Some might have interpreted it as _"use it when you don't care about the initial value"_. Such use of `Signal` therefore makes the observation subjects to ordering concerns, if any side effect is to mutate the property _before_ the observation happens.

If we really mean to promote "`SignalProducer` unless absolute necessary", shouldn't our API design reflect that? Observations made via `SignalProducer` are generally invariant of such side effects due to the replay latest semantic. More importantly, if one doesn't need the replay semantic, one might be better off with `Signal` or any hot entity anyway.

P.S. I do notice that there is an example with heavy use of property signals, i.e. Kickstarter iOS. But apparently they are using it primarily as a `PublishSubject` rather than relying on the replay latest semantic of `Property`.

cc @ReactiveCocoa/reactiveswift

**Comment by mdiep** [comment]
I do think `.signal` is sometimes the correct thing to use, so I'd be hesitant to remove it, even though you can always use `.producer.skip(first: 1)`.

But I do wonder if there are better names than `.signal` and `.producer`. 🤔 

> If we really mean to promote "SignalProducer unless absolute necessary", shouldn't our API design reflect that?

I don't think we've ever said that, although producers are definitely far more common.

I guess I do see room for improvement here, I just don't know what direction we should go with it. It might be time to reflect on the `Signal`/`SignalProducer` distinction on the whole and see if it can be improved.

**Comment by kean** [comment]
Hey! I'm new to ReactiveSwift, but I have some experience with RxSwift. I found this issue when I was looking for a reason why `Property` has both `signal` and `signalProducer`.

What I find confusing is not the fact that `Property` offers `signal` (which kinda makes sense - you can read its initial value and the immediately subscribe to the new values, but it won't work correctly in a multithreaded environment though). What I find confusing is that `Property` exposes `signalProducer`.

Isn't the whole point of `SignalProducer` to represent cold sequences which you start when subscribing to them (e.g. network requests, something that has side-effects, etc)? This doesn't seem to be what's happening here at all. The `Property` always seems to be hot, even if backed by a `SignalProducer` (it gets started immediately upon properties' initialization if I'm not misunderstanding something). Doesn't it make `Property` essentially a `Signal` with some sort of `(replay: 1)` behaviour?

> Also, a somewhat related question, is there a way to have replay behavior without using `Property` (and exposing last recorded value). In the codebase on which I'm currently working on it seems to lead to everyone abusing properties and just reading current values of the properties without subscribing to new values (change doesn't get propagated), which seems like something that reactive programming is designed to prevent, but here it ends up facilitating this.

**Comment by kean** [comment]
Interesting, thanks for clarifying some of those points. The ‘Property’ - as you seem to agree - can always be considered hot, so it seems like a missed opportunity to fall back to ‘SignalProducer’ and lose guarantee of hotness when working with properties. 

Our current code base is riddled with ‘SignalProducers’ which are actually backed by properties and we seem to be loosing the advantages of distinguishing between the two (‘Signal’ and ‘SignalProducer’). Essentially we’re back to where we started - not knowing for sure whether the sequence is going to be cold or hot.

The replay behavior does seem weird, maybe even orthogonal to the question of coldness and hotness? I’m not an expert, so probably there is a definitive answer to that.

**Comment by kean** [comment]
@sharplet Thanks for clarifying some of those points! The `Property` - as you seem to agree - can always be considered hot, so it seems like a missed opportunity to fall back to `SignalProducer` and lose the guarantee of hotness when working with properties (which seems to happen a lot in our project!). But I understand your point about modelling replay behaviour as a `SignalProducer` - subscribing to it does make the property emit a value.

**Comment by jjoelson** [comment]
I think I agree with @mdiep that it might make sense to change the names. `signal` and `producer` really mean `futureValues` and `currentAndFutureValues`, and if those were the names then no one would ever be confused as to which they ought to use in any given situation.

It's true that `currentAndFutureValues` needs to be a `SignalProducer` rather than a `Signal` for reasons that would be obvious to anyone if they were *implementing* it. But it's a bit strange to *name* the property `producer` and expect users to work backwards and figure out that that probably means it sends the current value when started.

**Comment by sharplet** [comment]
I think `futureValues` is a good name for `signal` — with that, how about renaming `producer` to just `values`? I think the _behaviour_ of "current and future values" is a sensible & useful default, so giving it a shorter and more accessible name makes sense.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
