### ISSUE TITLE
How can i set the border color for a UILabel using 

### ISSUE THREAD

**Issue by MithunMadhav1112** [ReactiveCocoa/ReactiveSwift#621]
How can i set the border color for a UILabel. The properties such as backgroundColor can be accessed like

`someLabel.reactive.backgroundColor <~  // update it using a signal that gives the background color`

But how can a similar operation be done for changing the border color or any of the properties of UIView's layer ?

**Comment by MithunMadhav1112** [comment]
The properties such as backgroundColor can be accessed like

someLabel.reactive.backgroundColor <~  // update it using a signal that gives the background color

But how can a similar operation be done for changing the border color or any of the properties of UIView's layer ?

**Comment by mdiep** [comment]
This is really a question for https://github.com/ReactiveCocoa/ReactiveCocoa, which is where the Cocoa bindings live.

ReactiveCocoa doesn't currently have any bindings on `CALayer`. Someone would need to add them.

**Comment by MithunMadhav1112** [comment]
So there is no way to alter CALayer properties when using ReactiveCocoa ?

**Comment by mdiep** [comment]
Not currently. Someone would need to add bindings for those to ReactiveCocoa.

**Comment by brow** [comment]
@MithunMadhav1112 You can add also an extension like this in your own target:

```swift
extension Reactive where Base: CALayer {
  public var borderColor: BindingTarget<CGColor?> {
    return makeBindingTarget { $0.borderColor = $1 }
  }
}
```

And then you can write:
```swift
someLabel.layer.reactive.borderColor <~ something
```
