### ISSUE TITLE
Drop the mandatory error parameter constraint to the `Swift.Error` protocol.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#622]
Self conforming existential does not seem to be arriving any time soon.

It appears to me that from a usability perspective, dropping the `Swift.Error` conformance requirement has a benefit in allowing `Error` existential to be used directly, especially when interoperating with conventional Swift and Objective-C frameworks. There is probably no downside, given that [`Swift.Error` has barely any semantic value](https://developer.apple.com/documentation/swift/error).

Note: [The `Result`-in-stdlib discussion seems to be heading the same direction.](https://forums.swift.org/t/adding-result-to-the-standard-library/6932/137)

Note 2: [It seems that the `Error` existential could potentially get special-cased though, if the stdlib indeed moves forward with the error type being constrained.](https://forums.swift.org/t/adding-result-to-the-standard-library/6932/79).

**Comment by mdiep** [comment]
I feel strongly that we should leave this constraint. (I also feel strongly that the Stdlib should have it for `Result`'s error.)

**Comment by NachoSoto** [comment]
+1

**Comment by Qata** [comment]
+1, failing with arbitrary data structures would be more helpful in a lot of circumstances.

**Comment by andersio** [comment]
@NachoSoto Do you mean +1 to  @mdiep or +1 to the thread? 😛

**Comment by NachoSoto** [comment]
To @mdiep's comment.

**Comment by mdiep** [comment]
If Swift adds typed throws where the types don't need to conform to `Error`, then I'd support removing this constraint.

**Comment by mdiep** [comment]
I think so. Especially since `Result` also has the `Error` constraint.
