### ISSUE TITLE
An operator like take(while:) that includes the last value

### ISSUE THREAD

**Issue by sharplet** [ReactiveCocoa/ReactiveSwift#627]
I have a custom operator in my project called `take(until: isLastValue)` that is just like `take(while:)` with an inverted predicate, but also emits the value for which the predicate is first true. I don't know if that's the best name, but it's useful behaviour.

A couple other ideas:

- `take(upTo:)`
- `take(upToAndIncluding:)`
- `take(while: predicate, includeLastElement: true)`

Any thoughts/preferences on this operator? If we agree on a name, this could be a good starter pull request.

**Comment by mdiep** [comment]
Make `take(through:)`? Swift stdlib uses `upTo:` to mean not included, so I think that's out.

**Comment by leonid-s-usov** [comment]
What if the predicate returned some ternary value, implicitly convertible from bool for backward compatibility?

**Comment by brow** [comment]
Another possibility is to give the client back the remainder of the stream of values to process as they like:
```swift
func take(
  while: (Value) -> Bool, 
  then: (SignalProducer<Value, Error>) -> SignalProducer<Value, Error> = { _ in .empty })
```

In that case:
* `take(while:)` behaves as before
* `take(while: predicate, then: { $0.take(first: 1) }` includes the last value
* Various other treatments of the remainder are possible

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
