### ISSUE TITLE
How  to turn an Error into a successful Value event

### ISSUE THREAD

**Issue by john-twigg-ck** [ReactiveCocoa/ReactiveSwift#639]
If like to be able to map/flatmap/redirect the error of my producer/signal into a now normally operating stream with a new value.
```

let producer = SignalProducer<Int,MyError>( ... ) 

enum MyStatus {
   case success(Int)
   case tryAgain
}

let successfullProducer : SignalProducer<MyStatus,NoError> = producer.mapResult { (result: Result<Int, MyError>) -> MyStatus in 
    switch result {
       case let Result.success(data):
            return MyStatus.success(int)
       case let Result.error(_)
            return MyStatus.tryAgain
   }
}
```

Notice how the error has been redirected into a successful value in the `successfullProducer` which on longer produces errors.

The problem I see with the Producer APi's is that they only transform errors to other errors, but never let you redirect the error into a successful stream value again.

This is useful for things like `MutableProperty` binding targets which only take `NoError` signals. So if I receive an error on a stream, I'd like to bind that to a Mutable property and display an error state.

Thoughts? Am I missing something?

**Comment by brow** [comment]
Are you aware of `SignalProducer.flatMapError`? That can swallow an error and replace it with a new producer, which can send zero, one, or many values.

**Comment by john-twigg-ck** [comment]
Correct me if I'm wrong, you the API says you cannot change the Value type

`public func flatMapError<F>(_ transform: @escaping (Error) -> SignalProducer<Value, F>) -> SignalProducer<Value, F>`

So it can only swallow the errors and only return the SAME `Value` type. I'm looking for a API like

`public func flatMapError<V,F>(_ transform: @escaping (Error) -> SignalProducer<V, F>) -> SignalProducer<V, F>`

Where the Error is transformed onto a NEW Value type.
