### ISSUE TITLE
Provide producer constructor from signal and initial value

### ISSUE THREAD

**Issue by ianbytchek** [ReactiveCocoa/ReactiveSwift#645]
👊 me if I'm missing the obvious… It seems a common pattern (in my work at least) to create producers out of signals with some initial value. Mostly when creating custom reactive extensions. It's simple enough with the below, but can something like this be included into official API?

```swift
extension SignalProducer
{
    public init(_ signal: Signal<Value, Error>, _ initial: Value) {
        self.init({ observer, disposable in
            disposable += signal.observe(observer)
            observer.send(value: initial)
        })
    }
}
```

**Comment by mdiep** [comment]
Side note: if you really want `initial` to be the initial value, you’d need to send it before observing the signal. As is, there’s a race condition between the two.

This doesn’t seem any any better to me than `SignalProducer(signal).prefix(value: initial)`. Is there a reason why you think this would be better?

**Comment by ianbytchek** [comment]
> 👊 me if I'm missing the obvious…

Argh, this moment again! Now I know new old methods – couple more years and I'll learn how to use the framework… and thanks for the side note!
