### ISSUE TITLE
How can I combine a throttled and non-throttled stream?

### ISSUE THREAD

**Issue by jasonboyle** [ReactiveCocoa/ReactiveSwift#650]
I have a stream that is throttled via `throttle(while:on:)` on `QueueScheduler.main` such that only the last event received on the current run loop is delivered on the next run loop.  However, I would like to force the stream to emit the current value immediately (without waiting for the next run loop) at certain times, specifically when another stream emits a value.  I've tried using combineLatest with a stream that is not throttled.  However, my testing indicates that the combined stream's events are delivered only on the subsequent run loop.

I've tried adding `.observe(on:)` with both `UIScheduler` and `ImmediateScheduler` following the call to throttle in an attempt to redirect the stream to a different scheduler, but these attempts were not successful.

Is this the expected behavior when combining a throttled and non-throttled stream, and what can I do to make this work?  Thank you!

```
valueStream.throttle(while: active.negate(), on: QueueScheduler.main)
    .combineLatest(with: sampleStream)
    .map { $0.0 }
```

**Comment by mdiep** [comment]
You want the value from `valueStream` on the current run loop?

Throttling on `QueueScheduler.main` will always delay the value to the next run loop. You'd need to use `UIScheduler` for the `throttle` to have values from `valueStream` not do a thread hop.

**Comment by jasonboyle** [comment]
Hi @mdiep, thanks for the response.  I do want the steam's events to be delayed until the next run loop, at least those coming from `valueStream` in my code snippet.  However I want to combine these delayed events with non-delayed events from `sampleStream`.

I've tried using `.observe(on:)` as follows, unfortunately without success:

```valueStream.throttle(while: active.negate(), on: QueueScheduler.main)
    .observe(on: UIScheduler())
    .combineLatest(with: sampleStream)
    .map { $0.0 }```

**Comment by mdiep** [comment]
What scheduler is `sampleStream` on?

**Comment by jasonboyle** [comment]
It's using the default scheduler (created via Signal.pipe).

**Comment by mdiep** [comment]
You shouldn't need the `observe`. If `sampleStream` has already sent a value, then the `combineLatest` should execute right away. I would verify the timing before/after the `combineLatest` with a `.logEvents` or `.map` to make sure that the throttle is sending a value when you expect.

**Comment by jasonboyle** [comment]
Ah, you're right!  The throttled valueStream was providing the same value when sampleStream fired (since it's next value had yet to arrive on the subsequent run loop).  I was able to solve my problem by using _this_ stream to sample the original stream.  Thanks so much for your help @mdiep.
