### ISSUE TITLE
Synchronous SignalProducer doesn't complete

### ISSUE THREAD

**Issue by zintus** [ReactiveCocoa/ReactiveSwift#657]
Given code
```
let (signal, observer) = Signal<(), NoError>.pipe()

let interrupted = SignalProducer<(), NoError>.never
    .take(until: signal)

let op = SignalProducer<(), NoError>(value: ())
    .concat(interrupted)
    .flatMap(.latest) { _ -> SignalProducer<(), NoError> in
        return SignalProducer(value: ())
            .on(terminated: {
                observer.sendCompleted()
            })
    }
    .logEvents()

_ = op.collect().first()

print("finished!")
```

One can see that `finished!` is never printed

Am i right that this code is correct and should finish execution?

**Comment by andersio** [comment]
The behavior is correct. You should keep in mind that `SignalProducer` is lazy, in the sense that everything is setup only when it is actually started.

In this specific case, the `concat` semantic is that its RHS starts only **after** its LHS completes. Therefore, every work you derive from the `()` value using `flatMap` happens **before** the `interrupted` producer is started, including the termination of `signal`.

So now when the `interrupted` producer gets to start, the `signal` has already terminated, and `take(until: signal)` becomes a no-op.

**Comment by zintus** [comment]
@andersio 
Thanks a lot for timely response!

Your explanation helps alot, thanks for clarification. With that in mind, does following snippet of code makes sense to you? Are there any ways to simplify this?

Intention is to start inner producer (inside `flatMap`) every time there is chance that we succeed doing work (in snippet role of such source of information carried out by `.never`). And terminate such process after first inner producer that completes/fails.
```
let guardian = MutableProperty(true)

let interrupted = SignalProducer<(), NoError>.never
	.take(until: guardian.producer.filter { !$0 }.map { _ in () })

let op = SignalProducer<(), NoError>(value: ())
	.concat(interrupted)
	.flatMap(.latest) { value -> SignalProducer<(), NoError> in
		return SignalProducer(value: value)
			.on(terminated: {
				guardian.value = false
			})
	}
	.logEvents()

_ = op.collect().first()
```

**Comment by mdiep** [comment]
Can you use `take(first:)` or `take(while:)` or something instead?

I'm not sure what exactly you're trying to accomplish, but it seems like you have a pretty roundabout approach.

**Comment by zintus** [comment]
`take(first: 1)` works really well if inner signal sends one value before completion (which is accidentally exactly my case)

But how solve this in general case? My code above was attempt to do `flatMap(.latest)` which completes once inner signal complete.

**Comment by zintus** [comment]
Anyway, original question is sorted, thanks for help! 🎉
