### ISSUE TITLE
lifetime of signals collection and merge/combine

### ISSUE THREAD

**Issue by demonar** [ReactiveCocoa/ReactiveSwift#658]
@andersio , @mdiep , we are migrating from the objc version of reactive to the latest stable, i have only one question about the lifetime of signals, let's say that i create an array of signals/producers, when i use either combineLatest or merge or another method that returns a signal/producer of that array, if i set the lifetime on the resulting signal/producer, does that propagate to the original signals/producers in cascade?

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
