### ISSUE TITLE
Replace replicating overloads for contextual lookup with free functions.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#659]
It bothers me with the fact that we _have_ to replicate so many overloads just to support these trivial 
but important use cases:

```swift
notifications
    .withLatest(from: .value(context))

submission
    .then(.empty)
    .then(.init(error: .unknown))
```

I wonder if we should instead explore using free functions to support these:

```swift
notifications
    .withLatest(from: constant(context))

submission
    .then(empty())
    .then(failing(with: .unknown))

public func constant<Value, Error>(_ value: Value) -> SignalProducer<Value, Error> { ... }
public func failing<Value, Error>(with error: Error) -> SignalProducer<Value, Error> { ... }
public func empty<Value, Error>() -> SignalProducer<Value, Error> { ... }
```

**Comment by brow** [comment]
One thing I'd appreciate about the free functions is that they'd autocomplete in Xcode.

Since `.init(value:…` doesn't autocomplete, I usually type `SignalProducer.init`, and then sometime later go back and delete "SignalProducer" (if I remember to).

**Comment by mdiep** [comment]
Our original reasoning for using static functions and `init`s was that it better fits the Swift API design guidelines and the design of the standard library. I think that's still true, which is why I'd argue to keep that style. Apart from that, I don't really have an opinion.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
