### ISSUE TITLE
Archiving project leads to error internally in ReactiveSwift Pod

### ISSUE THREAD

**Issue by zackshapiro** [ReactiveCocoa/ReactiveSwift#663]
I can build and run with Reactive Swift fine but when I go to archive, I get an error inside of  `Action.swift`:

> Cannot load underling module for 'Result'

I'm using:

* ReactiveSwift 4.0.0

* Result 4.0.0

* Swift 4.1

* Deployment target is 10.3

This is an Objc project I've recently added Swift to.

I've cleaned, deleted derived data, closed and reopened Xcode. Any idea what's going on here?

**Comment by wudijimao** [comment]
Same....

**Comment by wudijimao** [comment]
With ReactiveSwift 4.0.0  fixed.  I use 3.1.0 before.   I think it is a problem about “modular_headers” setting in pod_file.
