### ISSUE TITLE
Custom Instrumentation

### ISSUE THREAD

**Issue by liscio** [ReactiveCocoa/ReactiveSwift#666]
While watching the WWDC sessions on custom instruments back in June, this is something that I couldn't stop thinking about. I'm just capturing it here so it doesn't get lost…

Using a combination of `os_signpost`, `os_log`, and by developing an appropriate "expert system" using the CLIPS language, I think that we could really boost users' ability to debug performance and other issues in `ReactiveSwift`.

Some challenges to overcome:

1. The cross-platform, and cross-API (i.e. deployment target) nature of `ReactiveSwift` will make this awkward to use. Furthermore, limitations in the Swift language (and the `os_signpost` Swift API) will make it very difficult to avoid a littering of `#if` statements in key pieces of code.[^1]

2. Choosing the meaningful events to instrument. We obviously want to count the # of `Signal`s that get created, capture the `Lifetime` objects'…lifetime, and so on.

3. Deciding whether to adopt a global, or per-signal-"family" (i.e. all `Signal{,Producer}`s spawned from a root) approach to tracing.

4. Gathering the "expert knowledge" required to build a useful expert system in CLIPS. For example, we could flag or discard certain "problem events" based on conditions that define how harmless or problematic they are.

Anyway, I think this would be a highly valuable addition to `ReactiveSwift` for a release that follows the Xcode 10 / Swift 4.2 timeframe…

In addition to creating the tools, it would be very useful to also collect a set of "best practices" for avoiding common performance pitfalls while using `ReactiveSwift`. My toy [ConcurrentTest](https://github.com/liscio/ConcurrentTest) repo might be a good starting point for a test app to demonstrate performance pitfalls/etc when threading, and might serve as a good way to demonstrate Instruments doing its job.

(Edit: Magic issue number! :metal:)

---

[1] It's not easy to create a simple wrapper around `os_signpost` because it uses variable arguments. See [1](https://stackoverflow.com/questions/46498121/passing-variadic-args-in-swift-4-for-os-log), and [2](https://stackoverflow.com/questions/50937765/why-does-wrapping-os-log-cause-doubles-to-not-be-logged-correctly). We _might_ be able to do this using a fixed/pre-defined set of tracing methods, though.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
