### ISSUE TITLE
Why are CocoaTarget and DelegateProxy internal?

### ISSUE THREAD

**Issue by ryanmeisters** [ReactiveCocoa/ReactiveSwift#676]
I'm new to ReactiveSwift. I previously used RxSwift extensively and found it very useful to be able implement reactive wrappers over APIs that used the delegate pattern. It looks like `DelegateProxy` in ReactiveSwift is internal, so that wouldn't be possible without copy-pasting it into my project or something. Is there another recommended way to achieve the same thing?

I'm also wondering about `CocoaTarget`, which seems like it would be useful in implementing my own reactive extensions. I was just going to implement my own `tapSignal` extension for `UIBarButtonItem`. Using the implementation of `controlEvents(for:)` as an example, CocoaTarget seems like a nice way to intercept target and action from the bar button item.

**Comment by ryanmeisters** [comment]
Yeah, I'm still getting my head around actions, but creating an action for this purpose felt like overkill

this is what I ended up doing
```
buttonItem.reactive.pressed = CocoaAction(Action<Void, Void, NoError> { [weak self] in
    self?.dismiss(animated: true, completion: nil)
    return .empty
})
```
and what I wanted was
```
buttonItem.reactive.tapped
    .take(duringLifetimeOf: self)
    .observeValues { [unowned self] _ in self.dismiss(animated: true) }
```
which feels cleaner to me in this case

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
