### ISSUE TITLE
How to coalesce a number of occurrences of the same signal into one per time interval?

### ISSUE THREAD

**Issue by bitjeep** [ReactiveCocoa/ReactiveSwift#681]
ReactiveSwift newb here with a question.  I'm trying to coalesce redraw requests (triggered by a signal) into a single signal which is handled once per time interval.  There's no value associated with the signals, so I really just need to have the redraw trigger if there were one or more signals which occurred in the previous time interval.  What would the code for this look like?

Here's what I have now:

```
var redrawSignal: Signal<Void, NoError>
private var redrawObserver: Signal<Void, NoError>.Observer

init() {
    (redrawSignal, redrawObserver) = Signal<Void, NoError>.pipe()

    // TODO: Need to coalesce multiple redraw calls here into one per time interval
    redrawSignal.take(duringLifetimeOf: self).observeValues { [weak self] in
        self?.doRedraw()
    }
}

func someDataUpdated() {
    redrawObserver.send(value: ())
}

func someOtherDataUpdated() {
    redrawObserver.send(value: ())
}

func doRedraw() {
    . . .
}
```

**Comment by mdiep** [comment]
You could use `.sample(on: .timer(interval: 1, on: QueueScheduler.main)).skipRepeats()`. Does that match what you're trying to do?

**Comment by bitjeep** [comment]
I changed the redraw signal handler to the following:

```
redrawSignal.sample(on: .timer(interval: 1, on: QueueScheduler.main)).skipRepeats() {
    . . .
}
```
and now I'm getting this compiler error:

> error: type 'Signal<(), NoError>' has no member 'timer'; did you mean 'timeout'?

I can see that `SignalProducer` has a similar `.timer` function to the one you're using, but it gives back a `Disposable` object, which doesn't work.  Note that I'm using ReactiveSwift via Cocoapods (version 4.0.0), in case the APIs you're using are recent additions.  I'll try bringing in the latest code here...

**Comment by mdiep** [comment]
`timer` is defined on `SignalProducer<Date, NoError>`, so you'll need to be explicit and map the value to `()`.

**Comment by bitjeep** [comment]
I've got it working now.  Thanks @mdiep for the help!
