### ISSUE TITLE
Internal NopDisposable

### ISSUE THREAD

**Issue by abekert** [ReactiveCocoa/ReactiveSwift#689]
I want to use `NopDisposable.shared` in my code, why does it have an **internal** modifier?

**Comment by mdiep** [comment]
We default to `internal` until and unless someone makes a compelling argument to make it `public`. That makes breaking changes less likely and prevents the API from growing too large.

**Comment by andersio** [comment]
Achieve the same semantic by creating a global `AnyDisposable` and then disposing of it.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
