### ISSUE TITLE
sample(with:) is not forwarding the latest value from self

### ISSUE THREAD

**Issue by MathieuWhite** [ReactiveCocoa/ReactiveSwift#693]
Hey guys, 

I am having an issue with the `sample(with:)` operator relating to the value forwarded from `self`. I want to make sure this is the operator I should be using, so here is the use case of the app. 

The app loads items through an Action based on a MutableProperty. When the value of the MutableProperty changes, the Action is triggered to get the values for the new property. The idea is that a list of items is being displayed to the user, and one item in that list needs to be selected. When changing the MutableProperty's value, I would like to verify if the currently selected item exists in the new values so that it can remain selected. Otherwise I just want to default to the first item. 

Please see the following code example:

```swift
let placemarkType: MutableProperty<PlacemarkType> = MutableProperty(.restaurant)
let load: Action<Void, [String], NoError>
let selectedIndex = MutableProperty(0)
let currentPlacemark: MutableProperty<String?> = MutableProperty(nil)

load = Action(state: placemarkType) { get(placemarks: $0) }
load <~ placemarkType.signal.map { _ in }

let placemarks = load.values

currentPlacemark <~ placemarks.producer.map { $0.first }

selectedIndex <~ placemarks.producer.sample(with: currentPlacemark).map { placemarks, current in
  guard let current = current, let index = placemarks.index(of: current) else {
    return 0
  }
  return index
}
```

What I'm seeing is that the `currentPlacemark` is being set first, and the `placemarks` value in the map closure is the most recently loaded. Then it sets the `selectedIndex`, however the `placemarks` value in the map closure is not the most recently loaded. It contains the previous value. 

I've also created a playground for additional information. 
Please let me know if there is anything else I can provide. 

Thanks! 

[ReactiveSwiftPlayground.playground.zip](https://github.com/ReactiveCocoa/ReactiveSwift/files/2600666/ReactiveSwiftPlayground.playground.zip)

**Comment by mdiep** [comment]
I think you want `combineLatest`, not `sample`. `sample` isn't going to send you the latest value—it'll send you the value when the right side sends a value.

**Comment by MathieuWhite** [comment]
@mdiep Thanks for the quick response.
In the example above, using `combineLatest` would send two events. The first one when the `currentPlacemark` is updated and the second when the `placemarks` are updated.

What I am looking for is to have the map fire once, and have access to the most recent value for both signals. Using `sample(with:)` did give me the most recent value for the right side, but not the left. 

```swift
placemarks = loadAction.values
currentPlacemark <~ placemarks.producer.map { $0.first } // $0 contains the latest values

selectedIndex <~ placemarks.producer.sample(with: currentPlacemark).map { placemarks, current in
  // current is the most recent value (updated on the line above)
  // placemarks contains the values before the most recent update above
}
```

With the example above, I'm still not entirely sure why the map closure on `placemarks.producer` receives the most recent value, but the map closure on `sample` sends the previous value. The next time `currentPlacemark` sends an event, `placemarks` will have the most recent value.

**Comment by mdiep** [comment]
Since both sides of the `sample` or from the same producer, I don't think there's any guarantee about which will fire first. In the specific example you gave, you could do do `placemarks.producer.map { ($0, $0.first) }` instead.

**Comment by MathieuWhite** [comment]
Thanks @mdiep,
Your comment about not being able to guarantee which would be the first to send an event has helped me better understand the problem.
