### ISSUE TITLE
Swift 5.0 and Result in Standard Library

### ISSUE THREAD

**Issue by larryonoff** [ReactiveCocoa/ReactiveSwift#696]
I think it's time to start preparation for the new features of Swift 5.0, i.e. Result that has been recently accepted to the standard library, see 
https://github.com/apple/swift-evolution/blob/master/proposals/0235-add-result.md.

The issue that I see that migration to the Swift.Result is a breaking change since different signatures.

https://github.com/apple/swift-evolution/blob/master/proposals/0235-add-result.md
```swift
public enum Result<Value, Error: Swift.Error> {
    case value(Value), error(Error)
}
```

when https://github.com/antitypical/Result
```swift
public enum Result<Value, Error: Swift.Error> {
	case success(Value)
	case failure(Error)
}
```

I totally respect to https://github.com/antitypical/Result, but I think that it's better using Standard Library.

Any community thought about?

**Comment by mdiep** [comment]
The accepted proposal is:

```swift
public enum Result<Success, Failure: Error> {
  case success(Success)
  case failure(Failure)
}
```

💯 we should use this.

`antitypical/Result` should also update to be a set of additions to the stdlib `Result`.

**Comment by larryonoff** [comment]
@mdiep the accepted signature 1-by-1 to `antitypical/Result`. This's really great

**Comment by andersio** [comment]
The tricky bit is `NoError` which could have been a typealias to `Never`, had it been conformed to `Error` in stdlib.

**Comment by mdiep** [comment]
> The tricky bit is `NoError` which could have been a typealias to `Never`, had it been conformed to `Error` in stdlib.

`Never` _is_ conformed to `Error` now. 
https://github.com/apple/swift/pull/16857

**Comment by larryonoff** [comment]
Result already updated for Swift 5.0, see antitypical/Result#278

**Comment by andersio** [comment]
Assuming antitypical/Result would just be augmenting the stdlib `Result` since Swift 5, should we consider dropping antitypical/Result as a dependency?

RAS depends on `NoError`, the structural definition of `Result` and `ResultProtocol`. The former two can be sourced from the stdlib in Swift 5. The last one is used only for extension constraint, which can be re-declared in RAS, and later replaced by parameterised extension when it lands.

**Comment by larryonoff** [comment]
I think it can just be extensions in ReactiveSwift without Result dependency.

**Comment by mdiep** [comment]
> Assuming antitypical/Result would just be augmenting the stdlib `Result` since Swift 5, should we consider dropping antitypical/Result as a dependency?

Yes, I think so. 👍

**Comment by NachoSoto** [comment]
Oh I missed this. I started the process: #702. I'm excited to make ReactiveSwift dependency-free :)

**Comment by Kalvin126** [comment]
@larryonoff I think we could close this issue now that #702  `Swift.Result` migration  is merged?

**Comment by NachoSoto** [comment]
👍🏻
