### ISSUE TITLE
Add bind, signal and producer reactive sub-extensions

### ISSUE THREAD

**Issue by ianbytchek** [ReactiveCocoa/ReactiveSwift#704]
I create a lot of custom binding, signal and producer extensions for app-specific cases. When the `Reactive` extension came out awhile ago my life was never the same since then… 😌

But time passes and no doubt there's an elephant in the room when it comes to naming bindings, signals and producers. I'm recalling a few cases (besides [this](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3323) and [this](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/1cb71e98e4aa2319fca54f99e4c259602e489565/Documentation/DesignGuidelines.md#use-descriptive-declarations-for-methods-and-properties-that-return-a-signal)) and constantly find myself struggling designing good reactive api due to naming ambiguity and clumsiness. 

Looking at ReactiveCocoa extensions is kind of the same – some bindings have `Value` suffix, some don't, same for signals. I understand the rationale behind it, but it's not immediately self-explanatory. There's not a lot of producer examples, so coming up with good naming convention is more work for users.

A few months ago I tried the new approach documented in [ReactiveSwift: practical meets elegant with custom extensions](https://medium.com/post-mortem/reactiveswift-practical-meets-elegant-with-custom-extensions-ee682709a8d8). After successfully using it for awhile I want to suggest implementing it into the core to make the api cleaner, reduce the ambiguity and provide easy to grasp on rules for creating custom extensions:

```swift
myControl.reactive.attributedStringValue <~ … // becomes
myControl.reactive.bind.attributedString <~ …

myControl.reactive.attributedStringValues.observe(…) // becomes
myControl.reactive.signal.attributedString.observe(…)

foo.reactive.barProducer.start(…) // becomes
foo.reactive.producer.bar.start(…)
```

What do you think?

**Comment by mdiep** [comment]
I dislike using `producer` and `signal` in the names like this. If you're looking to get an observable with the attributed string values, I don't think you should need to know upfront whether RAC exposes it as a `Signal` or as a `Producer`.

There's been discussion about bundling things like `attributedStringValue` and `attributedStringValues` into a single type (c.f. https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3463). That seems like a better solution to me. It should also be possible to build a property that provides this functionality. I can't remember if we've discussed that before.

**Comment by ianbytchek** [comment]
Good points. I recall using properties awhile ago but something didn't work out, so I abandoned that idea. I'll look into this again, but is there any reason why current api doesn't make use of them? It seems like a perfect candidate for cases like `attributedString`, etc.

**Comment by mdiep** [comment]
> is there any reason why current api doesn't make use of them?

I honestly don't remember. 😅

**Comment by ianbytchek** [comment]
That only makes it more intriguing! 😐 @andersio You did a lot of work around #3463, perhaps you remember why properties are not preferred to binding targets and signals?

**Comment by ianbytchek** [comment]
After migrating a project to use properties in attempt to consolidate separate bindings, signals and producers, the answer why they aren't first citizens seems obvious: 

1. The receiver must store the the property, especially true for mutable properties, which implies altering the code structure and increasing the complexity.
2. Mutable properties are a good solution for also handling atomic values, but up to the point until it needs to be integrated with an existing solution in place, which quickly turns into a mess.
3. The easy integration into existing code with existing property handling features (`willSet`, `didSet`) implies (of course not in all cases) duplicating a property to provide the reactive features, which feels like shooting self in the foot.
4. Even providing a regular non-mutable property in reactive extension feels awkward due to the fact that it's a `class`, not a `struct`, which it doesn't need to be for the concept (more on this below) and considering the performance implications with [reported 50,000,000… 😳 initialization time difference](https://stackoverflow.com/a/24243626/458356).

The fact that ReactiveCocoa doesn't use properties in extensions where they fit organically is a little hypocritical. I propose to consider adding new lightweight proxying property types,  which would take care of three simple tasks: 

1. Provide signal
2. Provide producer
3. Provide binding target (if mutable)

It would differ from existing implementation by not storing the value and not being concerned with the thread safety. This would also allow to use `struct` over `class` and provide reactive property behaviour as extension-only feature without the need to store them in the `Reactive` base object.

The implementation I experimented with is based around Swift `KeyPath`:

```swift
public struct KeyPathProperty<Target: AnyObject, Value>: BindingSource, BindingTargetProvider {
    public init(_ target: Target, _ keyPath: ReferenceWritableKeyPath<Target, Value>, _ signal: Signal<Value, NoError>) {
        self.target = target
        self.keyPath = keyPath
        self.signal = signal
    }

    public let target: Target
    public let keyPath: ReferenceWritableKeyPath<Target, Value>
    public let signal: Signal<Value, NoError>
    public var producer: SignalProducer<Value, NoError> { return signal.producer.prefix(value: self.value) }

    public var value: Value {
        get { return self.target[keyPath: self.keyPath] }
        set { self.target[keyPath: self.keyPath] = newValue }
    }

    public var bindingTarget: BindingTarget<Value> {
        return BindingTarget(lifetime: Lifetime.of(self.target)) { [weak target, keyPath] value in target?[keyPath: keyPath] = value }
    }
}

extension Reactive where Base: Foo {
    internal var myProperty: KeyPathProperty<Base, Bool> { 
        return KeyPathProperty(self.base, \. myProperty, self.base.pipe.myProperty.output)
    }
}
```

@mdiep What do you think?
