### ISSUE TITLE
Is there a book to learn ReactiveSwift?

### ISSUE THREAD

**Issue by anbarasu0504** [ReactiveCocoa/ReactiveSwift#709]
Am new to FRP, after long thought have decided to use ReactiveSwift in my project. I want to learn the basics of ReactiveSwift, but am unable to find a good resource.

If any one know of any book or online material to get started, please recommend.

Thanks.

**Comment by mdiep** [comment]
The Xcode playgrounds that are in the repo are a very good resource for that.

@eimantas has also written [a book](https://leanpub.com/reactivecocoa-book).

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
