### ISSUE TITLE
What is an adequate ReactiveSwift solution for bidirectional binding?

### ISSUE THREAD

**Issue by markvasiv** [ReactiveCocoa/ReactiveSwift#710]
What is an adequate ReactiveSwift solution for bidirectional binding?

Let's say I have a ViewModel which holds username property:

```swift
class ViewModel {
    let userName: MutableProperty<String?>
}
```

And a view, which holds a text field where the user enters username:
```swift
class ViewController {
    let viewModel: ViewModel
    var textField: TextField!
}
```

This view model is repososible for **editing** the User , which means that `userName` is set when current User loads and then when the user types new username in the field.

Doing something like that will result in a deadlock:
```swift
textField.text.producer.startWithValues { [weak self] (userName) in
    if self?.viewModel.userName.value != userName {
        self?.viewModel.userName.value = userName
    } 
}
    
viewModel.userName.producer.startWithValues { [weak self] (userName) in
    if self?.textField.text != userName {
        self?.textField.text = userName
    } 
}
 ```

I think that this example illustrates a somewhat common functionality among apps, so what is an adequate ReactiveSwift technique to implement it?

I was thinking of storing multiple properties inside of ViewModel (`userName` and `loadedUserName` in this example) but that increases amount of code for more complex forms and is far from elegant solution.

**Comment by mdiep** [comment]
You should be able to do this:

```swift
textField.reactive.text <~ viewModel.userName
viewModel.userName <~ textField.reactive.continuousTextValues
```

Note that this uses [ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveCocoa).

**Comment by markvasiv** [comment]
Thank you! Is that possible to do the same but with any arbitrary mutable property?

**Comment by mdiep** [comment]
No, it's not: one needs to be the source of truth. This works with text fields (and other controls) because it doesn't update when the text field changes—only when it's edited.

But you could share a property?

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
