### ISSUE TITLE
Bag performance improvement

### ISSUE THREAD

**Issue by trimonovds** [ReactiveCocoa/ReactiveSwift#714]
Hi! I don't understand why Bag `public struct Bag<Element>` is implemented using 2 ContigiousArrays for tokens and for elements. I wrote simple implementation using Dictionary and simple test for insertion/removal
```swift
    func testPerformanceExample() {
        // This is an example of a performance test case.
        self.measure {
            var bag = Bag<String>()
            var tokens: [Bag<String>.Token] = []
            for i in 0...100000 {
                let token = bag.insert("abracadabra\(i)")
                tokens.append(token)
            }
            for i in 0...100000 {
                let token = tokens[i]
                bag.remove(using: token)
            }
        }
    }
```
and started it for 10000 and 100000 iterations. 
For 10000 iterations Dictionary-based implementation test took 0.414 sec while Array-based implementation took 0.861 sec.
For 100000 - Dictionary-based implementation result is 2.364 while Array-based result is about 50 sec. 
Am i miss something? Thanks) I know... there must be some reason

**Comment by andersio** [comment]
`Bag` is not optimised for insertion and removal performance and arbitrarily large number of elements. Its target is best iteration performance and a small number of elements, i.e. the most common scenario with RAS primitive use cases.
