### ISSUE TITLE
rac_textSignal() does not seem to work

### ISSUE THREAD

**Issue by danstepanov** [ReactiveCocoa/ReactiveSwift#72]
I'm using Xcode version 8.1, Reactive Swift pre-release version 1.0.0 alpha 3, Carthage version 0.11.0, and I don't think this matters but macOS Sierra version 10.12.1. 

I have successfully added `ReactiveSwift.framework` and `Result.framework` to my project as specified in the `Getting Started` section. However, when following the first code example on the README of this project, that is:

```
let searchStrings = textField.rac_textSignal()
    .toSignalProducer()
    .map { text in text as! String }
```

I am getting an error on the first line. The error reads:

```
Value of type 'UITextField' has no member 'rac_textSignal'
```

When right-clicking on `rac_textSignal()`, I am not taken anywhere and thus, I assume that this function has been removed. My implementation is as follows:

```
let textField = UITextField()

let textSignal = textField.rac_textSignal() {
  .toSignalProducer()
  .map { text in text as! String }
}
```

It concerns me that the first example in the README of this project doesn't work so I am hoping that I am just doing something wrong here. Any help would be greatly appreciated, thanks!

**Comment by andersio** [comment]
The readme hasn't been updated yet. Another thing to note is that you'd need ReactiveCocoa if you want Cocoa extensions.

https://github.com/ReactiveCocoa/ReactiveCocoa/blob/97af74d330bcb6f5e7a22fd2f8479e46ea67e9e1/README.md
