### ISSUE TITLE
ReactiveSwift-UIExamples Playground Doesn't Run - Possible Xcode 10.2 Issue

### ISSUE THREAD

**Issue by Steven0351** [ReactiveCocoa/ReactiveSwift#730]
I was going to make a PR for this as there were some compilation errors related to the replacement of the Result library with Swift.Result that were not addressed. However, after fixing the compilation issues the playground ultimately output "expression failed to parse, unknown error". I tinkered around a bit and found that when I commented out the body of `ViewController`'s `viewDidLoad()` implementation, the playground would display the UI (and obviously would do nothing else). I also tried selectively commenting out individual lines of code in `viewDidLoad()` to see if there was any particular culprit, but it always failed to run when any binding or assignment was performed.

I found a [similar issue](https://forums.developer.apple.com/thread/115766) that someone else posted on the Apple Developer Forums that seems to point to a potential issue with Xcode 10.2. I'm more or less opening this so it's on the project's radar in case ya'll weren't aware of it. I didn't see a point in opening a PR to fix the compilation issues if it can't be verified by running the Playground.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
