### ISSUE TITLE
Xcode 10.2.1 warning on deprecated functions since iOS 10.0

### ISSUE THREAD

**Issue by cwoloszynski** [ReactiveCocoa/ReactiveSwift#732]
I'm building ReactiveSwift 6.0.0 on XCODE 10.2.1 with a iOS target of iOS12+.

I am seeing the following error.
'OSAtomicDecrement32' was deprecated in iOS 10.0: Use atomic_fetch_sub_explicit(memory_order_relaxed) from <stdatomic.h> instead

Is this a known issue and is there any fix for this?

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
