### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by codyrobb** [ReactiveCocoa/ReactiveSwift#74]
Hi, 

I am running into a deadlock issue. I’m not entirely sure why it is happening yet. Here is my setup (dumbed down as this is the only part breaking, can provide more if needed).

```swift
class ActionController {
	var delay: NSTimeInterval = 0.0
	let undoable = MutableProperty<Bool>(false)

	func start() {
		if delay > 0.0 {
			undoable.value = true
		}
		
		// More stuff
		// Eventually will commit once delay is hit
		// Can provide more if needed.
	}
	
	func undo() {
		guard undoable.value else {
			return
		}
		
		// Do some stuff
		
		/***** DEADLOCK HAPPENS ON LINE BELOW *******/
		undoable.value = false
		/********************************************/
	}
}
```

```swift
class MyViewModel {

	private let currentAction = MutableProperty<ActionController?>(nil)
	
	let undoEnabled = MutableProperty<Bool>(false)
	
	init() {
		undoEnabled <~ currentAction.producer
			.flatMap(.Concat) { action in
				guard let action = action else {
					return SignalProducer<Bool, NoError>(value: false)
				}
				
				return action.undoable.producer
			}
			.skipRepeats()
	}
	
	func commitAction() {
		let action = ActionController()
		action.delay = 10
		action.start()
	}
	
	func undoCurrentAction() {
		currentAction.value?.undo()
	}

	 func onActionCompleted() {
		// Method gets called when ActionController completes    
		currentAction.value = nil
	}

}
```

Both `commitAction()` and `undoCurrentAction()` get called from a `UIViewController` that the `MyViewModel` is powering and has subscribers to `undoEnabled`.

Example for testing:

```swift
        viewModel.undoEnabled.producer.startWithNext { [unowned self] enabled in
            if enabled {
                self.viewModel.undoCurrentAction()
            }
        }
```

The deadlock seems to be happening when calling `undo` and setting `undoable`’s `value` to `false`.

**Comment by codyrobb** [comment]
After setting a breakpoint on `_NSLockError()`, it looks like it is line 66 in `Signal.swift` causing the lock and eventual breakdown.

This is one of my first bigger stabs at RAC4 after coming from RAC2.X. I might be misusing some things. Please let me know!

**Comment by codyrobb** [comment]
Another note: I am using ReactiveCocoa 4.2.2, but this seemed to be a better place to post the issue as it appeared you guys were trying to get the Swift API oriented issues over here.

If I need to move this just let me know.

**Comment by codyrobb** [comment]
Hmmm... interesting.... The root of the problem appears to be this code:

```swift
        viewModel.undoEnabled.producer.startWithNext { [unowned self] enabled in
            if enabled {
                self.viewModel.undoCurrentAction()
            }
        }
```

If I do this:

```swift
viewModel.undoEnabled.producer.startWithNext { [unowned self] enabled in
    if enabled {
        // undoPressed simply calls viewModel.undoCurrentAction()
        self.navigationItem.rightBarButtonItem =
            UIBarButtonItem(title: "UNDO", style: .Plain, target: self, action: #selector(self.undoPressed))
    } else {
        self.navigationItem.rightBarButtonItem = nil
    }
}
```

Everything works fine. Can anyone elaborate on this?

**Comment by andersio** [comment]
It seems you are having a signal recursion. `undoCurrentAction` is being called when `undoEnabled` changes, while `undoEnabled` is bound to `action.undoable`, which is being modified in `undoCurrentAction`.

**Comment by chuganzy** [comment]
This is just a simple example, but this is not actually technically infinite loop, so I feel it makes more sense to change Lock to be recursive. 

```swift
enum Event {
    case a
    case b
}

let pipe = Signal<Event, NoError>.pipe()
pipe.output.filterMap { $0 == .a ? Event.b : nil }.observe(pipe.input)
pipe.output.observeValues { event in
    print("value: \(event)")
}
pipe.input.send(value: .a)
```

**Comment by inamiy** [comment]
> 
> ```swift
> pipe.output.filterMap { $0 == .a ? Event.b : nil }.observe(pipe.input)
> ```

Nice example :) 
I also think this kind of data-flow should be accepted, i.e. let's use recursive lock.

**Comment by mdiep** [comment]
I think that organization should be discouraged. FRP is all about unidirectional data flow, so I don't think it makes sense to support cycles.

**Comment by chuganzy** [comment]
Let me give you more concrete example:

```swift
class View {
    enum Event {
        case textChanged(text: String)
        case buttonPressed
    }
    private let eventIO = Signal<Event, NoError>.pipe()
    private let textField = UITextField()
    private let button = UIButton()

    private func bind() {
        textField.reactive.continuousTextValues
            .map { Event.textChanged(text: $0) }
            .observe(eventIO.input)
        button.reactive.controlEvents(.touchUpInside)
            .map { _ in Event.buttonPressed }
            .observe(eventIO.input)
    }

    func observe(action: @escaping (Event) -> Void) {
        eventIO.output.observeValues {
            action($0)
        }
    }
}

class ViewController {
    let someView = View()

    private func bind() {
        someView.observe { [weak self] event in
            switch event {
                case .textChanged(let text): 
                    // do something
                case .buttonPressed:
                    // do something that eventually invoke below
                    self?.view.endEditing(false)
            }
        }
    }
}
```

When it invokes `self?.view.endEditing(false)` (or just call `textField.resignFirstResponder()`) UIKit sometimes sends `UITextView.textDidChangeNotification` so `continuousTextValues` sends new value.

**Comment by inamiy** [comment]
### FYI

- Queue-drain model without RecursiveLock: https://github.com/ReactiveCocoa/ReactiveSwift/pull/540
    - IMO interesting approach, but impl is quite complicated so I still prefer simple RecursiveLock
- RxSwift impl: [Rx.swift#L89-L122](https://github.com/ReactiveX/RxSwift/blob/fc6030ea9fe9b8af0351fe195b4095a9f2339757/RxSwift/Rx.swift#L89-L122)
    - Uses RecursiveLock
    - `fatalError` with friendly message when `#if DEBUG`
    - Prints warning message at console when non-DEBUG

Since detecting cyclic dependency is hard in general and requires a lot of runtime test, I prefer the approach RxSwift is taking: **prompt a message and use RecursiveLock**.

And IMO "discouraged" only works when the problem is **predictable** and preventable beforehand.
But as far as I see many unexpected deadlock examples here, I would say the problem is overall "unpredictable".

Also, without reentrancy, I think many other potential operators e.g. #308 `retryWhen` can't be implemented in ReactiveSwift.

**Comment by chuganzy** [comment]
@mdiep @andersio Can we start from reopening this issue? We might be able to gather more opinions.

**Comment by mdiep** [comment]
In that particular case, the pipe is an unnecessary level of indirection.

This seems like it'd work:

```swift
class View {
    enum Event {
        case textChanged(text: String)
        case buttonPressed
    }
    private let textField = UITextField()
    private let button = UIButton()

    func observe(action: @escaping (Event) -> Void) {
        textField.reactive.continuousTextValues
            .map { Event.textChanged(text: $0) }
            .observe(action)
        button.reactive.controlEvents(.touchUpInside)
            .map { _ in Event.buttonPressed }
            .observe(action)
    }
}

class ViewController {
    let someView = View()

    private func bind() {
        someView.observe { [weak self] event in
            switch event {
                case .textChanged(let text): 
                    // do something
                case .buttonPressed:
                    // do something that eventually invoke below
                    self?.view.endEditing(false)
            }
        }
    }
}
```

I don't think that the RxSwift behavior of not crashing but violating the contract is better.

**Comment by chuganzy** [comment]
That is right, but as commented in the code, we do have a view model that has some logics inside, so we do need this pipe.

Also even if we *did not* use pipe, if we want to do something like below, same thing will happen.

```swift
textView.reactive.continuousTextValues
  .filter { $0 == "resign" }
  .observe { [weak textView] textView?.resignFirstResponder() }
```

**Comment by mdiep** [comment]
It should be possible to detect cycles when you're constructing the signal chain. 🤔

**Comment by chuganzy** [comment]
```swift
textView.reactive.continuousTextValues
  .filter { $0 == "resign" }
  .observe { [weak textView] _ in textView?.resignFirstResponder() }
```

How can you solve this? `resignFirstResponder()` sometimes sends new value though. I think there is no way other than switching the scheduler..

**Comment by mdiep** [comment]
Oh, good point! 🤔

**Comment by chuganzy** [comment]
Yeah.. 
Not only UITextView specific, this kind of thing can easily happen as some methods have unexpected side effect sometimes..

**Comment by inamiy** [comment]
FYI here's a flipflop example that won't crash our real world:
https://gist.github.com/inamiy/bd7d82a77a4df70b3b4a367a2d014ca9

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄

**Comment by chuganzy** [comment]
Just for sharing, we have been patching RAS internally to workaround this.

**Comment by RuiAAPeres** [comment]
@chuganzy do you think you could open a PR with the fix?
