### ISSUE TITLE
Use of undeclared type 'Observer' on ReactiveSwift (5.0.1) Xcode 10.1

### ISSUE THREAD

**Issue by amolpict-ios** [ReactiveCocoa/ReactiveSwift#740]
We have recently update libraries as below : 
Using ReactiveCocoa (9.0.0)
Using ReactiveObjC (3.1.1)
Using ReactiveSwift (5.0.1)
Using Result (4.1.0)

On: Xcode 10.1

 fileprivate var userLocationObservers: [WeakContainer<Observer<CLLocation?, ApplicationError>>] = []
For this line we are getting error : **Use of undeclared type 'Observer'.**
Any one has idea, how to fix this ?

**Comment by brow** [comment]
In recent versions of ReactiveSwift, you need to write `Signal<CLLocation?, ApplicationError>.Observer` instead of `Observer<CLLocation?, ApplicationError>`.

**Comment by amolpict-ios** [comment]
Thanks @brow . I have update to new syntax. Below is my function and now its pointing with new error. 

 static func createErrorProducer(startHandler: @escaping (Signal<Value, Error>.Observer, CompositeDisposable) -> ()) -> SignalProducer {
        let signalProducer = SignalProducer(startHandler) **// Error on this line :: Cannot invoke initializer for type 'SignalProducer<Value, Error>' with an argument list of type '((Signal<SignalProducer<Value, Error>.Value, SignalProducer<Value, Error>.Error>.Observer, CompositeDisposable) -> ())'**
}

Not sure how to modify SignalProducer(startHandler) to match with new expected format.

**Comment by ikesyo** [comment]
Plaese check this: https://github.com/ReactiveCocoa/ReactiveSwift/releases/tag/3.0.0

You should use a `Lifetime` for the second parameter of `startHandler`.

**Comment by amolpict-ios** [comment]
Hi @ikesyo ,
Thanks for your input.
I have added LifeTime for second param of startHandler as below :

static func createErrorProducer(startHandler: @escaping (Signal<Value, Error>.Observer, **Lifetime**, CompositeDisposable) -> ()) -> SignalProducer {
        let disposable = CompositeDisposable()
        let (signal, observer) = Signal<Value, Error>.pipe(disposable: disposable)
        let signalProducer = SignalProducer(startHandler, **Lifetime(disposable))**
        // **_Getting error as : Cannot convert value of type 'CompositeDisposable' to expected argument           type 'Lifetime.Token'. So I tried below line_**
        let signalProducer = SignalProducer(startHandler, Lifetime.make().token)
       // **_And now its failed to compile with 
Cannot invoke initializer for type 'SignalProducer<Value, Error>' with an argument list of type '((Signal<SignalProducer<Value, Error>.Value, SignalProducer<Value, Error>.Error>.Observer, Lifetime, CompositeDisposable) -> (), Lifetime.Token)'_**


        return signalProducer.on(failed: { (error) in
           // Custom message
        }
}
As I mentioned I am using Swift 5.0.

**Comment by ikesyo** [comment]
I recommend you to check the pull request to understand how it works: https://github.com/ReactiveCocoa/ReactiveSwift/pull/334/files

```swift
static func createErrorProducer(startHandler: @escaping (Signal<Value, Error>.Observer, Lifetime) -> ()) -> SignalProducer {
    let signalProducer = SignalProducer(startHandler)
    return signalProducer.on(failed: { (error) in
        // Custom message
    }
}
```

**Comment by amolpict-ios** [comment]
> I recommend you to check the pull request to understand how it works: https://github.com/ReactiveCocoa/ReactiveSwift/pull/334/files
> 
> ```swift
> static func createErrorProducer(startHandler: @escaping (Signal<Value, Error>.Observer, Lifetime) -> Void) -> SignalProducer {
>     let signalProducer = SignalProducer(startHandler)
>     return signalProducer.on(failed: { (error) in
>         // Custom message
>     }
> }
> ```

@ikesyo 
Thanks providing help on this issue. Link is helpful. 
Solution you provided fixed my compile time errors.
Thanks once again :)
