### ISSUE TITLE
'value' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by asheesh5391** [ReactiveCocoa/ReactiveSwift#760]
I am moving to ReactiveSwift 6.0 to 6.1.0 and facing following issue.

'value' is inaccessible due to 'internal' protection level

can someone help me out?

Thanks.

**Comment by ikesyo** [comment]
Looks like you are hitting #733. `Result.value` was public unintentionally, so it was changed to internal. You could/should add your own extension to `Result`.
