### ISSUE TITLE
Looking fo best practices for Signal creation.

### ISSUE THREAD

**Issue by nservidio** [ReactiveCocoa/ReactiveSwift#767]
Hi! Thanks again for creating ReactiveSwift! I've searched around a bit online and can't find what I'm looking for.

The [APIContracts](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Documentation/APIContracts.md#best-practices) used to include [this](https://github.com/ReactiveCocoa/ReactiveObjC/blob/master/Documentation/DesignGuidelines.md#avoid-using-subjects-when-possible) best practice.

My question is: should [`pipe()`](http://reactivecocoa.io/reactiveswift/docs/latest/Classes/Signal.html#/s:13ReactiveSwift6SignalC4pipe10disposableACyxq_G6output_AC8ObserverCyxq__G5inputtAA10Disposable_pSg_tFZ) be avoided for the same reasons that `RACSubject` should be avoided?

Thanks!

**Comment by gkaimakas** [comment]
Have you tried making the observer `private`/`fileprivate` and have the `signal` public? This way you control the signal and nobody else.

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
