### ISSUE TITLE
Inner signal not "interrupted" on outer signal disposal

### ISSUE THREAD

**Issue by inamiy** [ReactiveCocoa/ReactiveSwift#77]
(Ref: https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2959)

Below gist (SignalProducerSpec's "disposal") passed the test in `ReactiveCocoa v4.2.2` but not in current `ReactiveSwift 1.0.0-alpha.3`.

https://gist.github.com/inamiy/925644779adbfca621ea716770d3865e

It seems `innerSignal.on().observe()` is disposed first before `on()` receives `.interrupted`.
This could be a NEW correct behavior as discussed in https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3075, but if I want to know the interruption of `innerSignal`, what should I do?

**Comment by inamiy** [comment]
Also related: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2949

**Comment by mdiep** [comment]
This seems like a bug to me. 😐

**Comment by andersio** [comment]
Is it limited to a specific strategy?
