### ISSUE TITLE
Is QueueScheduler still necessary?

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#79]
Just wonder if we can conform `DispatchQueue` (or even `OperationQueue`) to the scheduler protocols directly.

These loosen the requirement of serial execution in the Scheduler contract. But then `DispatchQueue` is by default serial, and the users should have been aware of any issue should they own the queue.

**Comment by NachoSoto** [comment]
Serial execution is importan though. I don't remember the exact context, but RAC 2 had many problems as a consequence of that.

**Comment by andersio** [comment]
In RAS we guaranteed the atomicity of the observer call-out. It is still true that things would be delivered nondeterministically, but the behavior is limited only to when a concurrent queue is supplied.

**Comment by mdiep** [comment]
I think we also need to start limiting changes for ReactiveSwift 1.0.

**Comment by andersio** [comment]
@NachoSoto How about creating an internal serial queue that targets the supplied queue?

**Comment by andersio** [comment]
@NachoSoto It seems `RACScheduler` had once allowed concurrent execution, but no longer did. That's said we can accomplish a similar semantic by creating an internal serial queue that targets any arbitrary queue supplied.

**Comment by andersio** [comment]
Tried to prototype it and it wasn't quite ideal. The creation and the retrieval of the RAC internal serial queue needs extra synchronisation that adds overhead on every scheduling attempt.

**Comment by robertjpayne** [comment]
@NachoSoto do you have any more info about why QueueScheduler's need to be serial? I quite frequently have "background" tasks and I just found out that a single QueueScheduler prevents any sort of concurrent execution.

I'm working around this right now by creating a pool of QueueScheduler's and round robin the operators onto them.

It just seems less than ideal…

```
extension QueueScheduler {
    static var concurrent: QueueScheduler {
        // a single QueueScheduler enforces serial FIFO execution of scheduled blocks. To allow for concurrent execution
        // we instead use a pool of QueueSchedulers and rotate them as they are accessed
        return self.concurrentSchedulers.modify { schedulers in
            let scheduler = schedulers.removeFirst()
            schedulers.append(scheduler)
            return scheduler
        }
    }
    
    private static var concurrentSchedulers = Atomic<[QueueScheduler]>([
        QueueScheduler(qos: .default, name: "concurrent"),
        QueueScheduler(qos: .default, name: "concurrent"),
        QueueScheduler(qos: .default, name: "concurrent"),
        QueueScheduler(qos: .default, name: "concurrent"),
        QueueScheduler(qos: .default, name: "concurrent"),
        QueueScheduler(qos: .default, name: "concurrent"),
        QueueScheduler(qos: .default, name: "concurrent"),
        QueueScheduler(qos: .default, name: "concurrent")
    ])
}
```

**Comment by andersio** [comment]
`signal.observe(on: ConcurrentScheduler())` would result in a `Signal` which delivers values in indeterministic order. But it would be an intentional use of concurrent queues, and other than this I was not aware of any context in ReactiveSwift which might oppose such use.
