### ISSUE TITLE
I need help.bro

### ISSUE THREAD

**Issue by wdq123550** [ReactiveCocoa/ReactiveSwift#807]
![image](https://user-images.githubusercontent.com/20955893/95837293-074fc300-0d73-11eb-8f23-c81b72899de6.png)

I don't konw what happen.

**Comment by Marcocanc** [comment]
Please provide more context so we can actually help you.

**Comment by wdq123550** [comment]
![image](https://user-images.githubusercontent.com/20955893/95839508-ae355e80-0d75-11eb-8170-72c8f5b6f1fc.png)

**Comment by wdq123550** [comment]
@Marcocanc please look the pic. I don't konw why the xocde tell me this error. I am poor swifter.Can you help me ?
