### ISSUE TITLE
observing disposed events

### ISSUE THREAD

**Issue by dnadoba** [ReactiveCocoa/ReactiveSwift#821]
Hey,

Is it possible to materialise disposed events too?
The only way I could find to observer disposed events of a signal is using the [`on(event:failed:completed:interrupted:terminated:disposed:value:)`](https://reactivecocoa.io/reactiveswift/docs/latest/Classes/Signal.html#/s:13ReactiveSwift6SignalC2on5event6failed9completed11interrupted10terminated8disposed5valueACyxq_GyAC5EventOyxq__GcSg_yq_cSgyycSgA3RyxcSgtF) method.

Thanks 🙏 
David

**Comment by datwelk** [comment]
What about `disposable.observeEnded` ?
