### ISSUE TITLE
[Pitch, Take 2] Revisiting `observe*` and `start*`

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveSwift#85]
[&raquo; Sandbox](https://gist.github.com/andersio/9906e1e06027a1ff687ad7a61e70d5a2)

### TL;DR
"Extensible enum" based API.

```
producer.start(.all) { event in }
producer.start(.values) { value in }
producer.start(.results) { result in }
producer.start(.completed) {}
producer.start(.interrupted) {}
producer.start(.failed) { error in }

// default value: .all
producer.start { event in }
```

#### Caveats
1. No autocompletion for the extensible enum.
2. Three more characters to observe a `Signal` for `With` being wiped from `SignalProducer.start`.

Well probably keeping things as is would be better, heh. But similar tricks using static members can be considered too, e.g.

```
// Static method on `Observer`.
producer.start(.values { value in })
```

#### How would existing codes be affected?
Unless the default value is anything but `.all`, the existing `observe*` and `start*` can be marked as deprecated and gracefully fade out without name clashes.

**Comment by mdiep** [comment]
I'm 👎 on doing this for 1.0

I don't think it's an obvious improvement over what we have, and I'd like to focus on getting the release out the door.

**Comment by andersio** [comment]
Not aiming for 1.0 though.
