### ISSUE TITLE
Could not find module 'ReactiveSwift' for target 'arm64-apple-ios-simulator'

### ISSUE THREAD

**Issue by tangzzz-fan** [ReactiveCocoa/ReactiveSwift#851]
I am using a m1 chip to build the project based on Carthage. It could build and run well on Intel chip, but cannot pass on m1.
Carthage build script used end up with --use-xcframeworks. 
Error message is :"Could not find module 'ReactiveSwift' for target 'arm64-apple-ios-simulator'"
Anyone meet this issue too?

**Comment by mluisbrown** [comment]
Sounds similar to this issue: https://github.com/ReactiveCocoa/ReactiveSwift/issues/825

If you are building ReactiveSwift into an XCFramework for use with Apple Silicon it also needs to include an `arm64-apple-ios-simulator` slice so it can be used in the simulator on Apple Silicon Macs.

**Comment by tangzzz-fan** [comment]
> Sounds similar to this issue: #825
> 
> If you are building ReactiveSwift into an XCFramework for use with Apple Silicon it also needs to include an `arm64-apple-ios-simulator` slice so it can be used in the simulator on Apple Silicon Macs.

Thank you for your quick reply, I will improve it immediately!
