### ISSUE TITLE
[BUG] XCode 14 beta 3 - bitcode issue 

### ISSUE THREAD

**Issue by salvatoreboemia** [ReactiveCocoa/ReactiveSwift#852]
Hi I have a problem with XCode 14 about bitcode.

XCode tells me to wait for an update for the package, I have already updated ReactiveCocoa and ReactiveSwift to the latest SPM versions

<img width="244" alt="Screenshot 2022-07-22 at 13 37 38" src="https://user-images.githubusercontent.com/20614870/180432021-5dbf93be-7a50-469d-97cb-d4dc166b9495.png">

Works fine on simulatore but not on physical device

Do you have any news about it?

Thanks

**Comment by NachoSoto** [comment]
The default setting in Xcode is Bitcode disabled now, so I recommend disabling that in your target as well: https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes
