### ISSUE TITLE
Is it planned to add count argument to `collect(every:on:skipEmpty:discardWhenCompleted:)`?

### ISSUE THREAD

**Issue by ChaseChoi** [ReactiveCocoa/ReactiveSwift#853]
I'm trying to find a built-in operator similar to [bufferWithTimeOrCount(timeSpan, count, [scheduler])](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/bufferwithtimeorcount.js) in RxJS, but I only found `collect(every:on:skipEmpty:discardWhenCompleted:)` and `collect(count:)`. Should I create my own operator?

**Comment by mluisbrown** [comment]
There are no plans to add this. I would be better to create your own operator.
