### ISSUE TITLE
EXC_BAD_ACCESS Crashes occur in xcode15

### ISSUE THREAD

**Issue by eunyongeom** [ReactiveCocoa/ReactiveSwift#879]
After updating to xcode15, the following crashes occur.
Due to these problems, I am unable to update to xcode15.
I would greatly appreciate your help.

1. `duringLifetimeOf` crash
```swift
extension Signal {
	/// Forward events from `self` until `object` deinitializes, at which point the
	/// returned signal will complete.
	///
	/// - parameters:
	///   - object: An object of which the deinitialization would complete the returned
	///             `Signal`. Both Objective-C and native Swift objects are supported.
	///
	/// - returns: A signal that will deliver events until `object` deinitializes.
	public func take(duringLifetimeOf object: AnyObject) -> Signal<Value, Error> {
		return take(during: Lifetime.of(object))
	}
}
```
<img width="1052" alt="Screenshot 2023-10-05 at 11 40 07 PM" src="https://github.com/ReactiveCocoa/ReactiveSwift/assets/22745436/aa7a8cbb-e2c5-4d29-a32b-7205a7aaae6a">

2. `tryToDisposeSilentlyIfQualified` crash
<img width="1394" alt="Screenshot 2023-10-07 at 1 25 52 PM" src="https://github.com/ReactiveCocoa/ReactiveSwift/assets/22745436/af5cc0a6-351f-4245-a366-f1204192b8a1">

**Comment by eunyongeom** [comment]
I think the problem occurred because I built it incorrectly.
After rebuilding it, the crash problem went away.

**Comment by mluisbrown** [comment]
Thanks for the update @eunyongeom. There is a known issue with incremental compilation of Swift since Xcode 14 which can cause random `EXC_BAD_ACCESS` crashes if a struct or other data type is altered to occupy more memory (eg adding an extra field) than before. The solution is to do a clean build.

**Comment by eunyongeom** [comment]
@mluisbrown 
Thank you for your reply.
Does this issue only occur in `ReactSwift`? 
Or is it a problem that other libraries can also occur?
