### ISSUE TITLE
Action: What is it good for

### ISSUE THREAD

**Issue by mdiep** [ReactiveCocoa/ReactiveSwift#88]
_This has all spawned from @sharplet's #22._

`Action` is based on RAC 2's `RACCommand`, which is itself based on [ReactiveUI](https://github.com/reactiveui/ReactiveUI)'s `ReactiveCommand`. The model was originally created to model UI actions—which are serial and occur on the main thread. But `Action` was meant to be decoupled from this dependency. The RAC 3 changelog says:

> Unlike commands, actions are not bound to or dependent upon the main thread, making it easier to reason about when they can be executed and when they will generate notifications.

I think this is incomplete: `Action`s aren't truly thread safe.

The `enabledIf` property is one of the key features of actions. However, that property is inherently racey with the body of the action itself. If the property is altered on a different thread/scheduler, it can switch to `false` after `Action` checks the value but before the body of the action executes. You can't trust that the world hasn't changed in the execute closure.

`RACCommand` and ReactiveUI's `ReactiveCommand` don't suffer from this issue because they're tied to the main thread. Altering the world on a background thread is prohibited.

I think we should do something to address this: either explicitly document this limitation or modify `Action` so that it's truly thread safe and reactive.

One we could achieve the later would be to base `Action`'s inputs on signals. Currently, `Action`s often read external properties (i.e. state), rather than relying solely on their input. In the typical login example, the login action would read the username and password properties directly from the view model:

```swift
class LoginViewModel {
    let username = Property<String>()
    let password = Property<String>()
    let action: Action<(), (), LoginError>

    init() {
        let enabled = Property
            .combineLatest(username, password)
            .map { !$0.isEmpty && !$1.isEmpty }
        action = Action(enabledIf: enabled) { _ in
          let username = self.username // These could be empty, even though they should be disabled
          let password = self.password // The perils of reading state
          …
        }
    }
}

// elsewhere
loginViewModel.action.apply(())
```

But actions could be restructured like so:

```

class LoginViewModel {
    let username = Property<String>()
    let password = Property<String>()
    let action: Action<(), LoginError> // input type isn't part of the type

    init() {
        let input = Property.combineLatest(username, password)
        action = Action(input, enabledIf: { !$0.isEmpty && !$1.isEmpty }) { (username, password) in
          …
        }
    }
}


// elsewhere
loginViewModel.action.apply()
```

This would have a few benefits that I see:

1. Value consistency between `enabledIf` and `execute`
1. `apply()` can easily be bound to a trigger signal
1. `Action`s become usable only in the reactive model

But this does require (1) removing the input type from `Action` and (2) removing the input parameter from `apply()`. (2) could be especially problematic, depending on how people are currently using `Action`. But in the standard bind-this-action-to-a-button case, this model seems like it would be simpler.

I'm curious what people think. @ReactiveCocoa/reactiveswift

**Comment by andersio** [comment]
+1. This makes `Action`s operate on immutable snapshots of the input, and aligns better with the spirits of FP.

The only downside is, as you might have implied, that it is less ideal as a bridge to the imperative world, that can still be called imperatively while having all the derived signals.

**Comment by mdiep** [comment]
This definitely limits the applicablility of `Action`. The question is whether the eliminated applications are useful and good, or whether this clarifies the role of actions.

**Comment by andersio** [comment]
One question though - does `apply` capture the input at its call time, or would `apply` return a producer that operates on the current value when it starts?

**Comment by sharplet** [comment]
I don't know how widely-used `Action` is. To me, it feels harder to use than it should be (in the sense that it's super useful and things that are super useful should also be easy to use).

Here's what I get out of it:

- **Serialisation**: I know that when the action's producer is executing, it is the only one executing. I can trust that side effects won't be executed more than I expect.
- **Command-Query Separation**: Signal producers execute their side effects for every observer, and so it can become quite difficult to reason about what side effects will occur, and when. Actions give me a way to separate the work to be done from observing the progress or effect of that work.

On the other hand, there's a really great symmetry between these two type signatures:

```swift
let execute: (Input) -> SignalProducer<Output, Error>
let task: Action<Input, Output, Error>

task = Action(execute)
```

I wonder if there's two different concepts here? And maybe one could be composed from the other?

I'm still trying to think this through...

**Comment by dmcrodrigues** [comment]
`Action` is a concept super useful and powerful to me especially, when used at UI layer.

> But this does require (1) removing the input type from Action and (2) removing the input parameter from apply(). (2) could be especially problematic, depending on how people are currently using Action. But in the standard bind-this-action-to-a-button case, this model seems like it would be simpler.

@mdiep I like how your proposal aims for immutability which is definitely a good thing. Unfortunately, personally speaking about my use of actions, I have a few cases where the input is dynamic, e.g. according to the value of a `UISwitch`, and others where my `enabledIf` property is not related at all with my input. 

But doing a more philosophical analysis, can we really avoid this kind of bad usage? I mean, this definetly makes it more harder but it's still possible to ignore the input and access a shared state while defining the executing block (which can be the body of a `SignalProducer`).

But I'm still reflecting about this, it's definitely not an easy one.

**Comment by mdiep** [comment]
> Unfortunately, personally speaking about my use of actions, I have a few cases where the input is dynamic, e.g. according to the value of a UISwitch

You could still achieve that.

```swift
let switch = UISwitch()
let property = Property<Bool>(value: false, then: switch.reactive.isOnValues)
let action = Action(input) { ... }
```

**Comment by erichoracek** [comment]
We use the RAC2 equivalent of `Action` (`RACCommand`) extensively in our ReactiveObjC codebase, so I think I can speak to our usage of `RACCommand`'s `enabled` property and how we tend to use it in practice.

In cases where an Action's enabled-ness depends exclusively on its inputs, a pattern like the proposed makes total sense. We have definitely been frustrated by the fact that the state that changes to the enabled-ness of an Action is not read at the same time as the `apply()` closure of the action is invoked (and thus can introduce inconsistencies).

However, this use is not the only way that we use Action. In our codebase, approximately 2 of every 3 Actions use input values. As a specific example from our codebase, say that we have an Action that presents a modal when `apply()` is invoked. The action has the following signature:
```swift
Action<Bool, ModalViewModel>
```
Where the input `Bool` value is whether or not the presentation is animated, and the `apply` `SignalProducer` sends values of type `ModalViewModel` for the view model backing the presentation. Additionally, this Action is enabled when the presentation can occur, and disabled for the entirety of the presentation (until the modal is dismissed).

In this case, if the input type was removed, there would be no way for a consumer (such a as a button) to indicate whether or not the presentation would be animated. Additionally, the enabled-ness of this Action does not depend on its inputs, which (as far as I can tell) is incompatible with the proposed changes to action.

Following from the above, perhaps this behavior could be built in a way where it is available as an option when creating Actions, but is not the only way to work with them (somewhat like #22). Throwing out the ability for `Action` to have an `InputType` would (in my mind) be a much greater loss than the current frustration of having to deal with enabled-ness of Actions not necessarily being in sync with invocations of `apply()`.

**Comment by mdiep** [comment]
> Where the input Bool value is whether or not the presentation is animated

Could you share a bit more about where the `Bool` value comes from?

**Comment by erichoracek** [comment]
Sure—the Bool value can come from a number of places:
- The `UIViewController` that consumes the view can decide to perform an animated presentation, and executes the Action with `true` (in the case of a cell or button being tapped)
- Within the view model itself, if a presentation is triggered as a side-effect of another action.
- A consumer of the view model that wants to perform a presentation non-animatedly (in the case of a deep link that synchronously creates a stack of presented modals at launch-time)

**Comment by sharplet** [comment]
So it seems clear that there's some value to both ideas: a) `Action` having an `Input` type, and b) `Action` being able to observe some external state in a thread-safe way.

Earlier on in #22 I had an idea to make (b) happen, but never got it to work. This conversation inspired me to take another crack at it, and I think I've got it: https://github.com/ReactiveCocoa/ReactiveSwift/pull/22/commits/fea3dc61596a6f3c5a6e38eddfc4884b59e30608.

@mdiep's original example can now work, with only a slight change to preserve the `Input` parameter:

```swift
class LoginViewModel {
    let username = Property<String>()
    let password = Property<String>()
    let action: Action<(), Void, LoginError> // input type is still part of the type

    init() {
        let form = Property.combineLatest(username, password)

        // this is still a little messy, but I think we can
        // layer some nicer convenience initialisers on top of this API
        action = Action(_internalState: input, enabledIf: { !$0.isEmpty && !$1.isEmpty }) { (username, password), _ in
          …
        }
    }
}


// elsewhere
loginViewModel.action.apply()
```

**Comment by mdiep** [comment]
That approach looks fine to me!
