### ISSUE TITLE
Is there any plan for future releases?

### ISSUE THREAD

**Issue by nickell-andrew** [ReactiveCocoa/ReactiveSwift#882]
A colleague and I collaborated on a GC improvement to this library ~6 months ago after getting the PR merged pinned to that merged commit in cocoa pods. Now we're looking at migrating to SPM and it's forcing folks to discuss forking and maintaining our own copy of ReactiveSwift which I'd prefer to avoid.

I think @mluisbrown is the maintainer who reviewed and merged our PR.

**Comment by mluisbrown** [comment]
One for @RuiAAPeres @NachoSoto and @andersio to answer.

**Comment by mluisbrown** [comment]
Although if it's the lack of a release tag that's prompting your discussion of creating a fork, you can still use ReactiveSwift from SPM by pointing to a specific commit or branch.

**Comment by mluisbrown** [comment]
@nickell-andrew [7.2.0](https://github.com/ReactiveCocoa/ReactiveSwift/releases/tag/7.2.0) was just released. That includes your fix. 

More generally, new releases of ReactiveSwift will be sporadic at best, and only to maintain compatibility with newer versions of Swift / Xcode, or to fix bugs.
