### ISSUE TITLE
Make Reactive.init(_ base:) public.

### ISSUE THREAD

**Issue by calebd** [ReactiveCocoa/ReactiveSwift#91]
It would be nice to be able to add custom `reactive` extensions to types that are outside the scope of ReactiveSwift. The only way to achieve that currently is to declare an accessible initializer in the consuming module that can assign `base` since the current initializer is marked as `fileprivate`.

**Comment by sharplet** [comment]
You should already be able to do that by conforming to `ReactiveExtensionProviding` on your class.

**Comment by calebd** [comment]
Oh cool I totally missed that. Thanks!
