### ISSUE TITLE
Question about Signal leak / memory managment

### ISSUE THREAD

**Issue by emuye** [ReactiveCocoa/ReactiveSwift#92]
I'm seeing some leaks with ReactiveSwift. I'm using the alpha so wondering if this is known, or if I'm missing something.

Using ReactiveCocoa (5.0.0-alpha.3)
Using ReactiveSwift (1.0.0-alpha.3)
Using Result (3.0.0)

Why does this code leak a Signal?

<img width="815" alt="screen shot 2016-11-10 at 11 45 50 am" src="https://cloud.githubusercontent.com/assets/1182729/20192046/0d6829e4-a73d-11e6-9981-20c4932934bf.png">

 ```
  var disposable = CompositeDisposable()  
   deinit {
        disposable.dispose()
    }

    @IBAction func load(_ sender: Any) {
        disposable += SignalProducer<Void, NSError> { sink, disposable in
            disposable.add {
                print("dispose")
            }
            
            sink.send(value: ())
            sink.sendCompleted()
        }.startWithCompleted {
            print("completed")
        }
    }
```

Also a similar example with a Disposable
```
       var disposable: Disposable?
       deinit {
            disposable?.dispose()
        }

       disposable = SignalProducer<Void, NSError> { sink, disposable in
            sink.send(value: ())
            sink.sendCompleted()
        }.startWithCompleted {
            print("completed")
        }

```

**Comment by andersio** [comment]
It doesn't seem leaking. While I did manage to reproduce this with the instrument, a weak reference to the produced signal (via `startWithSignal`) tells otherwise.

**Comment by andersio** [comment]
If you obtain a reference to the produced signal, it does turn `nil` after completion. It seems the weak reference implementation is the cause here, since the signal got released only when at the time the weak reference is touched.

I remember I have read about the differences between Swift and Objective-C's zeroing weak pointer implementation, and this is probably a consequence of those.

**Comment by emuye** [comment]
@andersio Thanks for responding so quicky. Can you show me the code for seeing the reference go to nil after completion?

**Comment by andersio** [comment]
Caught a leak, but the signal is freed after accessing the weak `signal`.
```
    weak var signal: Signal<(), NoError>?
    @IBAction func buttonTouchedUpInside(_ sender: Any) {
       SignalProducer<(), NoError>.empty.startWithSignal { signal, _ 
           self.signal = signal
       }
    }
```

No leak was caught.
```
    @IBAction func buttonTouchedUpInside(_ sender: Any) {
       SignalProducer<(), NoError>.empty.startWithCompleted {}
    }
```

Caught a leak, but the signal should be freed after the disposable is thrown away.
```
    var disposable: Disposable?
    @IBAction func buttonTouchedUpInside(_ sender: Any) {
       disposable = SignalProducer<(), NoError>.empty.startWithCompleted {}
    }
```
