### ISSUE TITLE
Question regarding memory/resource management

### ISSUE THREAD

**Issue by TheArtOfEngineering** [ReactiveCocoa/ReactiveSwift#94]
I'm reading through the source code, and it looks like the only way to break the retain cycle for a Signal is to remove all of it's observers. So it seems strange to me that the method `observe` would be decorated with `@discardableResult`. It seems as though if any one of the returned `ActionDisposable` results was discarded, a retain cycle would be guaranteed (since there would be no way to remove it from the `Bag` of observers). I just wanted to ask if someone might be able to help me understand what's going on here.

**Comment by andersio** [comment]
I am not sure what you mean by "breaking retain cycle" without any context.

[As said in the design contract](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Documentation/DesignGuidelines.md#a-signal-is-alive-as-long-as-it-is-publicly-reachable-or-is-being-observed), `Signal` cleans up all associated resources when it is terminated explicitly via any terminating event, or it silently disposes of itself.

**Comment by andersio** [comment]
That is just one tidbit of the implementation, if you mean `SignalState` retaining the `Signal`. It would still be released when it gets a termination event.

**Comment by TheArtOfEngineering** [comment]
Specifically I am confused about is [this](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Signal.swift#L168). Each signal maintains a reference to itself via its `SignalState` if there is at least one observer added to the signal. So basically if I had a function like:

```swift
func f() {
    let (signal, observer) = Signal<String, NoError>.pipe()
    signal.observeNext { next in print(next) }

    observer.sendNext("a")
}

f()
```

wouldn't I be leaking `signal` after calling `f`, since it has a reference to its itself?

**Comment by TheArtOfEngineering** [comment]
Could you point me to where the Signal is released when a terminating event is sent though? It would have to break this retain cycle, right?

**Comment by andersio** [comment]
You have to look at the bigger picture. We swap out, dispose of the generator disposable and throw away the `SignalState` when a termination event is received.

https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Signal.swift#L80

**Comment by TheArtOfEngineering** [comment]
Ah I see. That's a neat trick there. I would still have the leak in the above example though since no interrupt, nor other terminating signal was sent, correct?

**Comment by andersio** [comment]
Yes, unless you detach the observer.

This probably falls into the caveats of this design. https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2959#issuecomment-236131149.

**Comment by andersio** [comment]
In general, `Signal`s should be terminated.

Even in the case where they don't, they are usually a derived stream from something that's really permanent, and can be disposed of when no observers remain, e.g. a signal of `Notification`.

**Comment by TheArtOfEngineering** [comment]
Oh, awesome, thanks for the link! That's very helpful. I'm not sure there is any other way to do it really. I have been playing around with making [this](https://github.com/SwiftOnEdge/Reflex) to get a better understanding of FRP and ReactiveCocoa and to play around with different possible APIs. I ended up with basically the same solution although it looks slightly different and mine will definitely leak if there is no terminating event even if there are no observers on the signal. You can see what I did [here](https://github.com/SwiftOnEdge/Reflex/blob/master/Sources/Signal.swift#L30).

**Comment by TheArtOfEngineering** [comment]
Actually I lied, in the case above, with my implementation the `Signal` would be properly deallocated since I don't care whether or not there are any observers on the `Signal`. Since no one holds a reference to input observer after `f()`, and the input observer holds the only strong reference to the `signal`, there is no cycle and the `Signal` will be dealloc'd. Not sure of the full ramifications of a design like this are, but in this *specific* case something like it wouldn't leak.

**Comment by andersio** [comment]
I won't comment on any other implementations. But I'd suggest you modelling the expected behavior in test cases. That would definitely help the iterative process towards the final goal.
