### ISSUE TITLE
Replaying success but not errors

### ISSUE THREAD

**Issue by sharplet** [ReactiveCocoa/ReactiveSwift#97]
In my current project I have a 3-step process where the output of each signal producer becomes the input of the next. This process should externally behave like a single atomic operation, essentially a state machine. If any step fails, then retrying the process should start again from the failed step, but use the cached output from previously successful steps.

I'd really like to use `replayLazily()` for this, but can't because it will also replay failures. I haven't been able to work out a way to compose existing operators to get the semantics I'm looking for.

Is this something that could use a new operator? Is there a way I can get this with existing operators?

I kind of want `replayLazily`, only failure events should invalidate the cache instead of being replayed.

**Comment by andersio** [comment]
A similar issue: https://github.com/ReactiveCocoa/ReactiveSwift/issues/83

**Comment by mdiep** [comment]
Can you give a little more detail about what you're trying to do?

**Comment by sharplet** [comment]
The idea is basically to create a state machine, where an action will restart from the last point it failed:

```swift
let step1: SignalProducer<A, AnyError>
let step2: (A) -> SignalProducer<B, AnyError>
let step3: (B) -> SignalProducer<C, AnyError>

let task = step1
  .replaySuccessLazily() // don't love this name
  .flatMap(.concat, transform: step2)
  .replaySuccessLazily()
  .flatMap(.concat, transform: step3)
  .replaySuccessLazily()

let action = Action { _ in task }
```

**Comment by andersio** [comment]
It seems the prominent need here is a mean to "fail gracefully" by invalidating the cached values and restarting the producer. Composing with`retry(upTo:)` can do the later but not the former.

It is like how #83 asked for a producer that invalidates the cached image upon a timeout event, and restart the underlying producer.

I'd say we may introduce a specialized `replayLazily` overload on `SignalProducerProtocol where Error == ReplayCacheInvalidation`.

**Comment by mdiep** [comment]
It seems like you should move the retries into the steps.

```swift
let step1: SignalProducer<A, AnyError>
let step2: (A) -> SignalProducer<B, AnyError>
let step3: (B) -> SignalProducer<C, AnyError>

let task = step1
  .retry(upTo: 3)
  .flatMap(.concat) { step2($0).retry(upTo: 3) }
  .flatMap(.concat) { step3($0).retry(upTo: 3) }

let action = Action { _ in task }
```

Would that work?

**Comment by sharplet** [comment]
I don't think `retry()` does what I want here, because it retries the producer automatically. What I'm after is a way to have a producer replay values and completion on start, but if the multicasted producer has failed then the cached events should be discarded and it should be like starting the producer for the first time.

**Comment by mdiep** [comment]
In my snippet above, `step3` will be retried automatically—without restarting steps 1 or 2—if it fails, reusing the value from step 2. It sounded like that was what you wanted.

But if you really want to replay all values, then you'd need a custom operator like that. I can't think of a better name for it, so I'd probably add it like that to your project until/unless a it solidifies into something more clear.

**Comment by sharplet** [comment]
I'll be honest, I'm a little daunted by the complexity of `replayLazily`, and the idea of largely duplicating that in a new operator (or multiple!).

I've been doing some thinking about introducing the notion of a caching policy, and I'd like to spitball a possible approach here. I think it would be possible to extend `replayLazily` to take an optional parameter `policy`:

```swift
// current behaviour, and the default value
replayLazily(upTo: Int.max, policy: .alwaysReplay)

// behaviour described in this issue
replayLazily(upTo: Int.max, policy: .replayCompleted)

// behaviour described in #83
replayLazily(upTo: Int.max, policy: .timeout(after: .seconds(1), on: QueueScheduler()))
```

The policy would be defined something like this: 

```swift
enum ReplayAction {
  case replay
  case invalidate
}

/// A function that allows responding to any event by invalidating the cache asynchronously
struct ReplayCachePolicy<Value, Error: Swift.Error> {
  let action: (_ event: Event<Value, Error>) -> SignalProducer<ReplayAction, NoError>
}

extension ReplayCachePolicy {
  static var alwaysReplay: ReplayCachePolicy {
    return .init { _ in
      SignalProducer(value: .replay)
    }
  }
  
  static func timeout(after interval: DispatchTimeInterval, on scheduler: DateScheduler) -> ReplayCachePolicy {
    return .init { event in
      guard event.isTerminating else {
        return SignalProducer(value: .replay)
      }
      
      return SignalProducer(value: .invalidate)
        .delay(interval, on: scheduler)
    }
  }
  
  static var replayCompleted: ReplayCachePolicy {
    return .init { event in
      switch event {
      case .value, .completed:
        return SignalProducer(value: .replay)
      case .failed .interrupted:
        return SignalProducer(value: .invalidate)
      }
    }
  }
}
```

Then, when starting the multicasted, replayed producer, observe the cache policy events something like this:

```swift
multicastedSignal
  .materialize()
  .flatMap(.merge) { policy.action($0).take(first: 1) }
  .filter { $0 == .invalidate }
  .take(first: 1)
  .observeValues { _ in
    // ensure replay state is reset, so that next time the producer is started, the underlying producer will be restarted instead of replayed
  }
```

What do you think? Would something like this be an appropriate change? Does it belong in a separate operator? Is it not worth the additional complexity?

**Comment by andersio** [comment]
As I might have mentioned, a separated operator might not be necessary. Since for both your case and #83 the requirement is replaying on failure, we may provide a overload that acts differently with a specific instance of error.

```swift
// current behaviour, and the default value
producer.replayLazily(upTo: Int.max)

// behaviour described in this issue
producer
    .mapError { _ in ReplayCacheInvalidation() }
    .replayLazily(upTo: Int.max)

// behaviour described in #83
producer
    .timeout(10.0, raising: ReplayCacheInvalidation(), on: UIScheduler())
    .replayLazily(upTo: Int.max)
```

So for this overload, upon receiving `failure`, it purges the cached values - so that new observers do not see the old values - and restarts the producer.

**Comment by mdiep** [comment]
> I've been doing some thinking about introducing the notion of a caching policy, and I'd like to spitball a possible approach here. I think it would be possible to extend replayLazily to take an optional parameter policy:

That seems sensible to me. 👍

**Comment by gbrhaz** [comment]
@andersio  What is `ReplayCacheInvalidation` and how does it invalidate the cache on failures?

**Comment by RuiAAPeres** [comment]
Hello. 👋  Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
